-- Lists Disposition · BATCH 2 + 2.5 · INTRA_REALM updates + deferred container inserts
-- Date: 2026-05-19
-- 334 INTRA_REALM UPDATEs (depth-ordered via the VALUES order) + 4 deferred INSERTs.

DO $$
DECLARE total int;
BEGIN
  SELECT count(*) INTO total FROM atoms;
  IF total <> 4978 THEN RAISE EXCEPTION 'BATCH-2 PRE-FLIGHT FAIL: expected 4978 atoms, found %', total; END IF;
  RAISE NOTICE 'BATCH-2 PRE-FLIGHT OK';
END$$;

WITH moves(old_id, new_id, new_path) AS (VALUES
  ('history-lists-historical-sites', 'history-historical-sites', 'History / Historical sites'),
  ('culture-literature-lists-electronic-literature', 'culture-literature-electronic-literature', 'Culture / Literature / Electronic literature'),
  ('culture-literature-lists-publishers', 'culture-literature-publishers', 'Culture / Literature / Publishers'),
  ('culture-sports-lists-climbing', 'culture-sports-climbing', 'Culture / Sports / Climbing'),
  ('health-lists-reference-ranges-for-common-blood-tests', 'health-health-sciences-reference-ranges-for-common-blood-tests', 'Health / Health sciences / Reference ranges for common blood tests'),
  ('health-lists-acronyms-in-healthcare', 'health-medicine-acronyms-in-healthcare', 'Health / Medicine / Acronyms in healthcare'),
  ('health-lists-alternative-medicine-modalities', 'health-medicine-alternative-medicine-modalities', 'Health / Medicine / Alternative medicine modalities'),
  ('health-lists-medical-abbreviations', 'health-medicine-medical-abbreviations', 'Health / Medicine / Medical abbreviations'),
  ('health-lists-surgical-procedures', 'health-medicine-surgical-procedures', 'Health / Medicine / Surgical procedures'),
  ('health-lists-psychotherapies', 'health-mental-health-psychotherapies', 'Health / Mental health / Psychotherapies'),
  ('history-lists-historians-by-subfield', 'history-historians-by-subfield', 'History / Historians / By subfield'),
  ('history-lists-coups-and-coup-attempts', 'history-historical-events-coups-and-coup-attempts', 'History / Historical events / Coups and coup attempts'),
  ('history-lists-disasters', 'history-historical-events-disasters', 'History / Historical events / Disasters'),
  ('history-lists-epidemics', 'history-historical-events-epidemics', 'History / Historical events / Epidemics'),
  ('history-lists-famous-deaths-by-cause', 'history-historical-events-famous-deaths-by-cause', 'History / Historical events / Famous deaths by cause'),
  ('history-lists-famous-speeches', 'history-historical-events-famous-speeches', 'History / Historical events / Famous speeches'),
  ('history-lists-helicopter-prison-escapes', 'history-historical-events-helicopter-prison-escapes', 'History / Historical events / Helicopter prison escapes'),
  ('history-lists-inventions', 'history-historical-events-inventions', 'History / Historical events / Inventions'),
  ('history-lists-inventors-killed-by-their-own-inventions', 'history-historical-events-inventors-killed-by-their-own-inventions', 'History / Historical events / Inventors killed by their own inventions'),
  ('history-lists-kidnappings', 'history-historical-events-kidnappings', 'History / Historical events / Kidnappings'),
  ('history-lists-missing-treasure', 'history-historical-events-missing-treasure', 'History / Historical events / Missing treasure'),
  ('history-lists-nobel-prizes', 'history-historical-events-nobel-prizes', 'History / Historical events / Nobel Prizes'),
  ('history-lists-recessions', 'history-historical-events-recessions', 'History / Historical events / Recessions'),
  ('history-lists-revolutions-and-rebellions', 'history-historical-events-revolutions-and-rebellions', 'History / Historical events / Revolutions and rebellions'),
  ('history-lists-riots', 'history-historical-events-riots', 'History / Historical events / Riots'),
  ('history-lists-ticker-tape-parades-in-new-york-city', 'history-historical-events-ticker-tape-parades-in-new-york-city', 'History / Historical events / Ticker-tape parades in New York City'),
  ('history-lists-treaties', 'history-historical-events-treaties', 'History / Historical events / Treaties'),
  ('history-lists-former-sovereign-states', 'history-historical-states-former-sovereign-states', 'History / Historical states / Former sovereign states'),
  ('history-lists-battles', 'history-military-history-battles', 'History / Military history / Battles'),
  ('history-lists-military-disasters', 'history-military-history-disasters', 'History / Military history / Disasters'),
  ('history-lists-guerrilla-movements', 'history-military-history-guerrilla-movements', 'History / Military history / Guerrilla movements'),
  ('history-lists-invasions', 'history-military-history-invasions', 'History / Military history / Invasions'),
  ('history-lists-military-operations', 'history-military-history-operations', 'History / Military history / Operations'),
  ('history-lists-sieges', 'history-military-history-sieges', 'History / Military history / Sieges'),
  ('history-lists-civil-wars-list', 'history-wars-civil-wars', 'History / Wars / Civil wars'),
  ('justice-lists-investigative-journalism-outlets', 'justice-evidence-investigative-journalism-outlets', 'Justice / Evidence / Investigative journalism outlets'),
  ('justice-lists-notable-whistleblowers-reference', 'justice-evidence-notable-whistleblowers', 'Justice / Evidence / Notable whistleblowers'),
  ('justice-lists-whistleblower-support-organizations', 'justice-evidence-whistleblower-support-organizations', 'Justice / Evidence / Whistleblower support organizations'),
  ('justice-lists-truth-commissions-historical', 'justice-progress-truth-commissions', 'Justice / Progress / Truth commissions'),
  ('justice-lists-notable-accountability-cases-reference', 'justice-prosecutions-notable-accountability-cases', 'Justice / Prosecutions / Notable accountability cases'),
  ('math-lists-games-mathematical', 'math-concepts-mathematical-games', 'Math / Concepts / Mathematical games'),
  ('math-lists-principia-mathematica-glossary-items', 'math-foundations-and-meta-mathematics-principia-mathematica-glossary', 'Math / Foundations and meta-mathematics / Principia Mathematica glossary'),
  ('math-lists-integrals', 'math-mathematical-objects-integrals', 'Math / Mathematical objects / Integrals'),
  ('math-lists-mathematical-series', 'math-mathematical-objects-mathematical-series', 'Math / Mathematical objects / Mathematical series'),
  ('math-lists-prime-numbers-list', 'math-mathematical-objects-prime-numbers', 'Math / Mathematical objects / Prime numbers'),
  ('math-lists-shapes-with-metaphorical-names', 'math-mathematical-objects-shapes-with-metaphorical-names', 'Math / Mathematical objects / Shapes with metaphorical names'),
  ('religion-lists-angels-list', 'religion-beings-angels', 'Religion / Beings / Angels'),
  ('religion-lists-deities-list', 'religion-beings-deities', 'Religion / Beings / Deities'),
  ('religion-lists-demons-list', 'religion-beings-demons', 'Religion / Beings / Demons'),
  ('religion-lists-people-claimed-to-be-jesus', 'religion-issues-and-debates-messianic-claimants', 'Religion / Issues and debates / Messianic claimants'),
  ('religion-lists-founders-religious-list', 'religion-religious-roles-founders', 'Religion / Religious roles / Founders'),
  ('religion-lists-popes-list', 'religion-religious-roles-popes', 'Religion / Religious roles / Popes'),
  ('religion-lists-saints-list', 'religion-religious-roles-saints', 'Religion / Religious roles / Saints'),
  ('science-lists-astronomy-lists-astronomical-catalogues', 'science-astronomy-and-space-science-astronomical-catalogues', 'Science / Astronomy and space science / Astronomical catalogues'),
  ('science-lists-astronomy-lists-astronomical-objects-named-after-people', 'science-astronomy-and-space-science-astronomical-objects-named-after-people', 'Science / Astronomy and space science / Astronomical objects named after people'),
  ('science-lists-astronomy-lists-astronomical-societies', 'science-astronomy-and-space-science-astronomical-societies', 'Science / Astronomy and space science / Astronomical societies'),
  ('science-lists-astronomy-lists-astronomical-symbols', 'science-astronomy-and-space-science-astronomical-symbols', 'Science / Astronomy and space science / Astronomical symbols'),
  ('science-lists-astronomy-lists-future-astronomical-events', 'science-astronomy-and-space-science-future-astronomical-events', 'Science / Astronomy and space science / Future astronomical events'),
  ('science-lists-astronomy-lists-most-distant-astronomical-objects', 'science-astronomy-and-space-science-most-distant-astronomical-objects', 'Science / Astronomy and space science / Most distant astronomical objects'),
  ('science-lists-astronomy-lists-space-telescopes', 'science-astronomy-and-space-science-space-telescopes', 'Science / Astronomy and space science / Space telescopes'),
  ('science-lists-astronomy-lists-telescopes', 'science-astronomy-and-space-science-telescopes', 'Science / Astronomy and space science / Telescopes'),
  ('science-lists-biological-journals', 'science-biology-biological-journals', 'Science / Biology / Biological journals'),
  ('science-lists-physics-lists-laws-in-science', 'science-scientific-method-and-meta-science-laws-in-science', 'Science / Scientific method and meta-science / Laws in science'),
  ('science-lists-physics-lists-letters-used-in-mathematics-and-science', 'science-scientific-method-and-meta-science-letters-used-in-mathematics-and-science', 'Science / Scientific method and meta-science / Letters used in mathematics and science'),
  ('self-lists-disappeared-mysteriously', 'self-person-disappeared-mysteriously', 'Self / Person / Disappeared mysteriously'),
  ('self-lists-eponymous-laws', 'self-person-eponymous-laws', 'Self / Person / Eponymous laws'),
  ('self-lists-eponyms', 'self-person-eponyms', 'Self / Person / Eponyms'),
  ('society-lists-cooperatives-list', 'society-economy-and-business-cooperatives', 'Society / Economy and business / Cooperatives'),
  ('society-lists-corporate-assets', 'society-economy-and-business-corporate-assets', 'Society / Economy and business / Corporate assets'),
  ('society-lists-economists', 'society-economy-and-business-economists', 'Society / Economy and business / Economists'),
  ('society-lists-employer-associations-list', 'society-economy-and-business-employer-associations', 'Society / Economy and business / Employer associations'),
  ('society-lists-academic-fields', 'society-education-system-academic-fields', 'Society / Education (system) / Academic fields'),
  ('society-lists-admissions-tests', 'society-education-system-admissions-tests', 'Society / Education (system) / Admissions tests'),
  ('society-lists-fields-of-doctoral-studies', 'society-education-system-fields-of-doctoral-studies', 'Society / Education (system) / Fields of doctoral studies'),
  ('society-lists-micronations', 'society-government-micronations', 'Society / Government / Micronations'),
  ('society-lists-national-legislatures', 'society-government-national-legislatures', 'Society / Government / National legislatures'),
  ('society-lists-case-law-list', 'society-law-case-law', 'Society / Law / Case law'),
  ('society-lists-acronyms', 'society-linguistics-acronyms', 'Society / Linguistics / Acronyms'),
  ('society-lists-shibboleths', 'society-linguistics-shibboleths', 'Society / Linguistics / Shibboleths'),
  ('society-lists-symbols-list', 'society-linguistics-symbols', 'Society / Linguistics / Symbols'),
  ('society-lists-intelligence-agencies-list', 'society-military-and-security-intelligence-agencies', 'Society / Military and security / Intelligence agencies'),
  ('society-lists-secret-police-organizations', 'society-military-and-security-secret-police-organizations', 'Society / Military and security / Secret police organizations'),
  ('society-lists-civic-fraternal-service-professional-organizations', 'society-social-institutions-civic-fraternal-service-professional-organizations', 'Society / Social institutions / Civic, fraternal, service, professional organizations'),
  ('society-lists-environmental-organizations', 'society-social-institutions-environmental-organizations', 'Society / Social institutions / Environmental organizations'),
  ('society-lists-guide-dog-schools', 'society-social-institutions-guide-dog-schools', 'Society / Social institutions / Guide dog schools'),
  ('society-lists-honorary-societies', 'society-social-institutions-honorary-societies', 'Society / Social institutions / Honorary societies'),
  ('society-lists-think-tanks', 'society-social-institutions-think-tanks', 'Society / Social institutions / Think tanks'),
  ('society-lists-feminism-list', 'society-social-movements-feminism', 'Society / Social movements / Feminism'),
  ('society-lists-social-science-journals', 'society-social-sciences-journals', 'Society / Social sciences / Journals'),
  ('society-lists-lifestyles', 'society-society-concepts-lifestyles', 'Society / Society concepts / Lifestyles'),
  ('society-lists-prizes-medals-and-awards', 'society-society-concepts-prizes-medals-and-awards', 'Society / Society concepts / Prizes, medals, and awards'),
  ('society-lists-scandals-with-gate-suffix', 'society-society-concepts-scandals-with-gate-suffix', 'Society / Society concepts / Scandals with "-gate" suffix'),
  ('tech-lists-character-sets-and-encodings', 'tech-computing-character-encoding', 'Tech / Computing / Character encoding'),
  ('tech-lists-demolished-landmarks', 'tech-construction-and-built-environment-demolished-landmarks', 'Tech / Construction and built environment / Demolished landmarks'),
  ('tech-lists-heritage-registers', 'tech-construction-and-built-environment-heritage-registers', 'Tech / Construction and built environment / Heritage registers'),
  ('tech-lists-tallest-buildings', 'tech-construction-and-built-environment-tallest-buildings', 'Tech / Construction and built environment / Tallest buildings'),
  ('tech-lists-largest-energy-infrastructure', 'tech-energy-technology-largest-energy-infrastructure', 'Tech / Energy technology / Largest energy infrastructure'),
  ('tech-lists-wikis-list', 'tech-internet-and-web-wikis', 'Tech / Internet and Web / Wikis'),
  ('tech-lists-missile-list', 'tech-military-technology-missiles', 'Tech / Military technology / Missiles'),
  ('tech-lists-nato-reporting-names', 'tech-military-technology-nato-reporting-names', 'Tech / Military technology / NATO reporting names'),
  ('culture-games-lists-japanese-board-games', 'culture-games-board-games-japanese-board-games', 'Culture / Games / Board games / Japanese board games'),
  ('culture-games-lists-mancala-variants', 'culture-games-board-games-mancala-variants', 'Culture / Games / Board games / Mancala variants'),
  ('culture-games-lists-miniature-wargames', 'culture-games-tabletop-games-miniature-wargames', 'Culture / Games / Tabletop games / Miniature wargames'),
  ('culture-games-video-games-lists-arcade-games', 'culture-games-video-games-arcade-games', 'Culture / Games / Video games / Arcade games'),
  ('culture-games-video-games-lists-console-palettes', 'culture-games-video-games-console-palettes', 'Culture / Games / Video games / Console palettes'),
  ('culture-literature-lists-books-banned-books', 'culture-literature-books-banned-books', 'Culture / Literature / Books / Banned books'),
  ('culture-literature-lists-books-best-selling-books', 'culture-literature-books-best-selling', 'Culture / Literature / Books / Best-selling'),
  ('culture-literature-lists-books-literary-awards', 'culture-literature-books-literary-awards', 'Culture / Literature / Books / Literary awards'),
  ('culture-literature-lists-electronic-literature-electronic-literature-authors-critics-and-works', 'culture-literature-electronic-literature-authors-critics-and-works', 'Culture / Literature / Electronic literature / Authors, critics, and works'),
  ('culture-literature-lists-fiction-comics', 'culture-literature-fiction-comics', 'Culture / Literature / Fiction / Comics'),
  ('culture-literature-lists-fiction-fairy-tales', 'culture-literature-fiction-fairy-tales', 'Culture / Literature / Fiction / Fairy tales'),
  ('culture-literature-lists-fiction-fictional-characters', 'culture-literature-fiction-fictional-characters', 'Culture / Literature / Fiction / Fictional characters'),
  ('culture-literature-lists-fiction-fictional-computers', 'culture-literature-fiction-fictional-computers', 'Culture / Literature / Fiction / Fictional computers'),
  ('culture-literature-lists-fiction-fictional-places', 'culture-literature-fiction-fictional-places', 'Culture / Literature / Fiction / Fictional places'),
  ('culture-literature-lists-fiction-fictional-robots-and-androids', 'culture-literature-fiction-fictional-robots-and-androids', 'Culture / Literature / Fiction / Fictional robots and androids'),
  ('culture-literature-lists-fiction-major-themes', 'culture-literature-fiction-major-themes', 'Culture / Literature / Fiction / Major themes'),
  ('culture-mass-media-film-and-cinema-lists-film-awards', 'culture-mass-media-film-and-cinema-awards', 'Culture / Mass media / Film and cinema / Awards'),
  ('culture-mass-media-film-and-cinema-lists-film-festivals', 'culture-mass-media-film-and-cinema-festivals', 'Culture / Mass media / Film and cinema / Festivals'),
  ('culture-mass-media-film-and-cinema-lists-film-institutes', 'culture-mass-media-film-and-cinema-institutes', 'Culture / Mass media / Film and cinema / Institutes'),
  ('culture-performing-arts-music-lists-concert-tours', 'culture-performing-arts-music-concert-tours', 'Culture / Performing arts / Music / Concert tours'),
  ('culture-performing-arts-music-lists-electronic-music-lists', 'culture-performing-arts-music-electronic-music', 'Culture / Performing arts / Music / Electronic music'),
  ('culture-performing-arts-music-lists-music-genres', 'culture-performing-arts-music-genres', 'Culture / Performing arts / Music / Genres'),
  ('culture-performing-arts-music-lists-musical-events', 'culture-performing-arts-music-musical-events', 'Culture / Performing arts / Music / Musical events'),
  ('culture-performing-arts-music-lists-opera-houses', 'culture-performing-arts-music-opera-houses', 'Culture / Performing arts / Music / Opera houses'),
  ('culture-performing-arts-music-lists-schools-of-music', 'culture-performing-arts-music-schools-of-music', 'Culture / Performing arts / Music / Schools of music'),
  ('culture-performing-arts-music-lists-video-game-music', 'culture-performing-arts-music-video-game-music', 'Culture / Performing arts / Music / Video game music'),
  ('culture-sports-lists-gay-athletes', 'culture-sports-notable-athletes-gay-athletes', 'Culture / Sports / Notable athletes / Gay athletes'),
  ('culture-sports-lists-sports-leagues-defunct-sports-leagues', 'culture-sports-sports-leagues-defunct', 'Culture / Sports / Sports leagues / Defunct'),
  ('history-lists-roman-sites', 'history-ancient-civilizations-roman-sites', 'History / Ancient civilizations / Roman / Sites'),
  ('history-lists-fires', 'history-historical-events-disasters-fires', 'History / Historical events / Disasters / Fires'),
  ('history-lists-industrial-disasters', 'history-historical-events-disasters-industrial', 'History / Historical events / Disasters / Industrial'),
  ('history-lists-natural-disasters', 'history-historical-events-disasters-natural', 'History / Historical events / Disasters / Natural'),
  ('history-lists-nuclear-accidents', 'history-historical-events-disasters-nuclear-accidents', 'History / Historical events / Disasters / Nuclear accidents'),
  ('history-lists-power-outages', 'history-historical-events-disasters-power-outages', 'History / Historical events / Disasters / Power outages'),
  ('history-lists-cyclones-list', 'history-historical-events-natural-disasters-cyclones', 'History / Historical events / Natural disasters / Cyclones'),
  ('history-lists-earthquakes', 'history-historical-events-natural-disasters-earthquakes', 'History / Historical events / Natural disasters / Earthquakes'),
  ('history-lists-archaeological-sites', 'history-historical-sciences-archaeology-archaeological-sites', 'History / Historical sciences / Archaeology / Archaeological sites'),
  ('human-activities-lists-schools', 'human-activities-views-education-practice-schools', 'Human activities / Views / Education (practice) / Schools'),
  ('justice-lists-government-oversight-bodies', 'justice-patterns-institutional-capture-government-oversight-bodies', 'Justice / Patterns / Institutional capture / Government oversight bodies'),
  ('math-lists-tensor-theory', 'math-branches-of-mathematics-pure-mathematics-tensor-theory', 'Math / Branches of mathematics / Pure mathematics / Tensor theory'),
  ('religion-lists-christian-denominations-list', 'religion-major-religions-christianity-denominations', 'Religion / Major religions / Christianity / Denominations'),
  ('religion-lists-indigetes-roman-gods-and-goddesses-list', 'religion-mythologies-roman-mythology-indigetes', 'Religion / Mythologies / Roman mythology / Indigetes'),
  ('religion-lists-patriarchs-of-antioch', 'religion-religious-roles-patriarchs-antioch', 'Religion / Religious roles / Patriarchs / Antioch'),
  ('religion-lists-patriarchs-of-constantinople', 'religion-religious-roles-patriarchs-constantinople', 'Religion / Religious roles / Patriarchs / Constantinople'),
  ('religion-lists-biblical-names', 'religion-sacred-texts-bible-names', 'Religion / Sacred texts / Bible / Names'),
  ('religion-lists-bible-stories', 'religion-sacred-texts-bible-stories', 'Religion / Sacred texts / Bible / Stories'),
  ('religion-lists-biblical-nameless', 'religion-sacred-texts-bible-unnamed-figures', 'Religion / Sacred texts / Bible / Unnamed figures'),
  ('science-lists-astronomy-lists-meteor-showers-list', 'science-astronomy-and-space-science-solar-system-meteor-showers', 'Science / Astronomy and space science / Solar System / Meteor showers'),
  ('science-lists-astronomy-lists-possible-dwarf-planets-list', 'science-astronomy-and-space-science-solar-system-possible-dwarf-planets', 'Science / Astronomy and space science / Solar System / Possible dwarf planets'),
  ('science-lists-plants-lists-famous-trees', 'science-biology-botany-famous-trees', 'Science / Biology / Botany / Famous trees'),
  ('science-lists-plants-lists-sequoia-groves', 'science-biology-botany-sequoia-groves', 'Science / Biology / Botany / Sequoia groves'),
  ('science-lists-species-and-specimens-world-s-25-most-endangered-primates', 'science-biology-conservation-worlds-25-most-endangered-primates', 'Science / Biology / Conservation / World''s 25 Most Endangered Primates'),
  ('science-lists-species-and-specimens-organisms-by-population', 'science-biology-ecology-organisms-by-population', 'Science / Biology / Ecology / Organisms by population'),
  ('science-lists-feeding-behaviours', 'science-biology-ethology-feeding-behaviours', 'Science / Biology / Ethology / Feeding behaviours'),
  ('science-lists-latin-and-greek-systematic-names', 'science-biology-taxonomy-latin-and-greek-systematic-names', 'Science / Biology / Taxonomy / Latin and Greek systematic names'),
  ('science-lists-species-and-specimens-organisms-named-after-famous-people', 'science-biology-taxonomy-organisms-named-after-famous-people', 'Science / Biology / Taxonomy / Organisms named after famous people'),
  ('science-lists-species-and-specimens-organisms-named-after-works-of-fiction', 'science-biology-taxonomy-organisms-named-after-works-of-fiction', 'Science / Biology / Taxonomy / Organisms named after works of fiction'),
  ('science-lists-chemistry-lists-biomolecules', 'science-chemistry-biochemistry-biomolecules', 'Science / Chemistry / Biochemistry / Biomolecules'),
  ('science-lists-chemistry-lists-standard-electrode-potentials', 'science-chemistry-electrochemistry-standard-electrode-potentials', 'Science / Chemistry / Electrochemistry / Standard electrode potentials'),
  ('science-lists-chemistry-lists-isotope-table', 'science-chemistry-elements-isotopes', 'Science / Chemistry / Elements / Isotopes'),
  ('science-lists-chemistry-lists-functional-groups', 'science-chemistry-organic-chemistry-functional-groups', 'Science / Chemistry / Organic chemistry / Functional groups'),
  ('science-lists-chemistry-lists-enthalpy-change-of-formation', 'science-chemistry-thermodynamics-enthalpy-change-of-formation', 'Science / Chemistry / Thermodynamics / Enthalpy change of formation'),
  ('science-lists-earth-sciences-lists-landforms-list', 'science-earth-science-geology-landforms', 'Science / Earth science / Geology / Landforms'),
  ('science-lists-earth-sciences-lists-oil-fields', 'science-earth-science-geology-oil-fields', 'Science / Earth science / Geology / Oil fields'),
  ('science-lists-earth-sciences-lists-tectonic-plates-list', 'science-earth-science-geology-tectonic-plates', 'Science / Earth science / Geology / Tectonic plates'),
  ('science-lists-earth-sciences-lists-uranium-mines', 'science-earth-science-geology-uranium-mines', 'Science / Earth science / Geology / Uranium mines'),
  ('science-lists-earth-sciences-lists-tropical-cyclone-names', 'science-earth-science-meteorology-tropical-cyclone-names', 'Science / Earth science / Meteorology / Tropical cyclone names'),
  ('science-lists-physics-lists-resistivities', 'science-physics-electromagnetism-resistivities', 'Science / Physics / Electromagnetism / Resistivities'),
  ('science-lists-physics-lists-artificial-radiation-belts', 'science-physics-nuclear-physics-artificial-radiation-belts', 'Science / Physics / Nuclear physics / Artificial radiation belts'),
  ('science-lists-physics-lists-particles-list', 'science-physics-particle-physics-particles', 'Science / Physics / Particle physics / Particles'),
  ('science-lists-physics-lists-colors-list', 'science-physics-physics-concepts-colors', 'Science / Physics / Physics concepts / Colors'),
  ('science-lists-physics-lists-cycles-physics', 'science-physics-physics-concepts-cycles', 'Science / Physics / Physics concepts / Cycles'),
  ('science-lists-physics-lists-noise-types', 'science-physics-physics-concepts-noise-types', 'Science / Physics / Physics concepts / Noise types'),
  ('science-lists-physics-lists-quantum-field-theories', 'science-physics-quantum-field-theory-theories', 'Science / Physics / Quantum field theory / Theories'),
  ('science-lists-physics-lists-relativistic-equations', 'science-physics-relativity-equations', 'Science / Physics / Relativity / Equations'),
  ('self-lists-wartime-cross-dressers', 'self-identity-dimensions-gender-wartime-cross-dressers', 'Self / Identity dimensions / Gender / Wartime cross-dressers'),
  ('self-lists-families-by-tree', 'self-relationships-family-family-trees', 'Self / Relationships / Family / Family trees'),
  ('society-lists-business-theorists', 'society-economy-and-business-business-administration-business-theorists', 'Society / Economy and business / Business administration / Business theorists'),
  ('society-lists-employee-owned-companies', 'society-economy-and-business-companies-employee-owned', 'Society / Economy and business / Companies / Employee-owned'),
  ('society-lists-feminist-economists', 'society-economy-and-business-economists-feminist-economists', 'Society / Economy and business / Economists / Feminist economists'),
  ('society-lists-stock-market-indices', 'society-economy-and-business-finance-stock-market-indices', 'Society / Economy and business / Finance / Stock market indices'),
  ('society-lists-traded-commodities', 'society-economy-and-business-finance-traded-commodities', 'Society / Economy and business / Finance / Traded commodities'),
  ('society-lists-store-brands', 'society-economy-and-business-retail-store-brands', 'Society / Economy and business / Retail / Store brands'),
  ('society-lists-national-anthems', 'society-government-national-symbols-anthems', 'Society / Government / National symbols / Anthems'),
  ('society-lists-united-states-federal-agencies', 'society-government-united-states-federal-agencies', 'Society / Government / United States / Federal agencies'),
  ('society-lists-united-states-mints', 'society-government-united-states-mints', 'Society / Government / United States / Mints'),
  ('society-lists-consonants', 'society-linguistics-phonetics-consonants', 'Society / Linguistics / Phonetics / Consonants'),
  ('society-lists-vowels-table', 'society-linguistics-phonetics-vowels', 'Society / Linguistics / Phonetics / Vowels'),
  ('society-lists-generic-names-of-political-parties', 'society-politics-political-parties-generic-names', 'Society / Politics / Political parties / Generic names'),
  ('society-lists-british-professional-bodies', 'society-social-institutions-professional-bodies-british', 'Society / Social institutions / Professional bodies / British'),
  ('society-lists-lgbt-related-organizations', 'society-social-movements-lgbt-organizations', 'Society / Social movements / LGBT / Organizations'),
  ('society-lists-california-suffragists', 'society-social-movements-suffragists-california', 'Society / Social movements / Suffragists / California'),
  ('society-lists-women-s-organizations', 'society-social-movements-women-organizations', 'Society / Social movements / Women / Organizations'),
  ('society-lists-clinical-psychologists', 'society-social-sciences-psychology-clinical-psychologists', 'Society / Social sciences / Psychology / Clinical psychologists'),
  ('society-lists-credentials-in-psychology', 'society-social-sciences-psychology-credentials', 'Society / Social sciences / Psychology / Credentials'),
  ('society-lists-psychology-disciplines', 'society-social-sciences-psychology-disciplines', 'Society / Social sciences / Psychology / Disciplines'),
  ('society-lists-emotions-list', 'society-social-sciences-psychology-emotions', 'Society / Social sciences / Psychology / Emotions'),
  ('society-lists-memory-biases-list', 'society-social-sciences-psychology-memory-biases', 'Society / Social sciences / Psychology / Memory biases'),
  ('society-lists-psychologists', 'society-social-sciences-psychology-psychologists', 'Society / Social sciences / Psychology / Psychologists'),
  ('society-lists-psychological-schools', 'society-social-sciences-psychology-schools-of-thought', 'Society / Social sciences / Psychology / Schools of thought'),
  ('society-lists-scientific-journals-in-psychology', 'society-social-sciences-psychology-scientific-journals', 'Society / Social sciences / Psychology / Scientific journals'),
  ('society-lists-social-psychologists', 'society-social-sciences-psychology-social-psychologists', 'Society / Social sciences / Psychology / Social psychologists'),
  ('society-lists-sociologists', 'society-social-sciences-sociology-sociologists', 'Society / Social sciences / Sociology / Sociologists'),
  ('society-lists-subfields-of-sociology-list', 'society-social-sciences-sociology-subfields', 'Society / Social sciences / Sociology / Subfields'),
  ('tech-lists-ascii', 'tech-computing-character-encoding-ascii', 'Tech / Computing / Character encoding / ASCII'),
  ('tech-lists-unicode', 'tech-computing-character-encoding-unicode', 'Tech / Computing / Character encoding / Unicode'),
  ('tech-lists-utf-8', 'tech-computing-character-encoding-utf-8', 'Tech / Computing / Character encoding / UTF-8'),
  ('tech-lists-xml-and-html-characters', 'tech-computing-character-encoding-xml-and-html-character-entities', 'Tech / Computing / Character encoding / XML and HTML character entities'),
  ('tech-lists-graphics-file-formats', 'tech-computing-file-formats-graphics', 'Tech / Computing / File formats / Graphics'),
  ('tech-lists-software-bugs-list', 'tech-computing-software-notable-software-bugs', 'Tech / Computing / Software / Notable software bugs'),
  ('tech-lists-operating-systems-list', 'tech-computing-software-operating-systems', 'Tech / Computing / Software / Operating systems'),
  ('tech-lists-canals-list', 'tech-construction-and-built-environment-civil-engineering-canals', 'Tech / Construction and built environment / Civil engineering / Canals'),
  ('tech-lists-civil-engineering-landmarks', 'tech-construction-and-built-environment-civil-engineering-landmarks', 'Tech / Construction and built environment / Civil engineering / Landmarks'),
  ('tech-lists-reservoirs-and-dams-list', 'tech-construction-and-built-environment-civil-engineering-reservoirs-and-dams', 'Tech / Construction and built environment / Civil engineering / Reservoirs and dams'),
  ('tech-lists-tcp-and-udp-port-numbers', 'tech-internet-and-web-protocols-tcp-and-udp-port-numbers', 'Tech / Internet and Web / Protocols / TCP and UDP port numbers'),
  ('tech-lists-famous-trains', 'tech-transport-technology-rail-transport-famous-trains', 'Tech / Transport technology / Rail transport / Famous trains'),
  ('culture-games-board-games-chess-lists-chess-books', 'culture-games-board-games-chess-books', 'Culture / Games / Board games / Chess / Books'),
  ('culture-games-board-games-chess-lists-fairy-pieces', 'culture-games-board-games-chess-fairy-pieces', 'Culture / Games / Board games / Chess / Fairy pieces'),
  ('culture-games-board-games-chess-lists-chess-games', 'culture-games-board-games-chess-notable-games', 'Culture / Games / Board games / Chess / Notable games'),
  ('culture-games-board-games-chess-lists-chess-openings', 'culture-games-board-games-chess-openings', 'Culture / Games / Board games / Chess / Openings'),
  ('culture-games-board-games-chess-lists-chess-players', 'culture-games-board-games-chess-players', 'Culture / Games / Board games / Chess / Players'),
  ('culture-games-board-games-chess-lists-chess-terms', 'culture-games-board-games-chess-terms', 'Culture / Games / Board games / Chess / Terms'),
  ('culture-games-board-games-chess-lists-chess-tournaments', 'culture-games-board-games-chess-tournaments', 'Culture / Games / Board games / Chess / Tournaments'),
  ('culture-games-board-games-chess-lists-world-championship-matches', 'culture-games-board-games-chess-world-championship-matches', 'Culture / Games / Board games / Chess / World Championship matches'),
  ('culture-games-board-games-chess-lists-chess-world-records', 'culture-games-board-games-chess-world-records', 'Culture / Games / Board games / Chess / World records'),
  ('culture-literature-lists-fiction-comics-comic-books', 'culture-literature-fiction-comics-comic-books', 'Culture / Literature / Fiction / Comics / Comic books'),
  ('culture-literature-lists-fiction-comics-comic-strips', 'culture-literature-fiction-comics-comic-strips', 'Culture / Literature / Fiction / Comics / Comic strips'),
  ('culture-literature-lists-fiction-comics-manga', 'culture-literature-fiction-comics-manga', 'Culture / Literature / Fiction / Comics / Manga'),
  ('culture-literature-lists-fiction-fictional-places-fictional-countries', 'culture-literature-fiction-fictional-places-countries', 'Culture / Literature / Fiction / Fictional places / Countries'),
  ('culture-literature-lists-fiction-fictional-places-imaginary-universes', 'culture-literature-fiction-fictional-places-imaginary-universes', 'Culture / Literature / Fiction / Fictional places / Imaginary universes'),
  ('culture-literature-lists-fiction-fictional-places-fictional-planets', 'culture-literature-fiction-fictional-places-planets', 'Culture / Literature / Fiction / Fictional places / Planets'),
  ('culture-literature-lists-fiction-major-themes-science-fiction', 'culture-literature-fiction-genres-science-fiction', 'Culture / Literature / Fiction / Genres / Science fiction'),
  ('culture-literature-lists-fiction-major-themes-adultery', 'culture-literature-fiction-major-themes-adultery', 'Culture / Literature / Fiction / Major themes / Adultery'),
  ('culture-literature-lists-fiction-major-themes-family', 'culture-literature-fiction-major-themes-family', 'Culture / Literature / Fiction / Major themes / Family'),
  ('culture-literature-lists-fiction-major-themes-sadomasochism', 'culture-literature-fiction-major-themes-sadomasochism', 'Culture / Literature / Fiction / Major themes / Sadomasochism'),
  ('culture-literature-lists-fiction-major-themes-travel', 'culture-literature-fiction-major-themes-travel', 'Culture / Literature / Fiction / Major themes / Travel'),
  ('culture-mass-media-film-and-cinema-lists-films-computer-animated-films', 'culture-mass-media-film-and-cinema-films-computer-animated', 'Culture / Mass media / Film and cinema / Films / Computer-animated'),
  ('culture-mass-media-film-and-cinema-lists-films-film-series', 'culture-mass-media-film-and-cinema-films-film-series', 'Culture / Mass media / Film and cinema / Films / Film series'),
  ('culture-mass-media-film-and-cinema-lists-films-greatest', 'culture-mass-media-film-and-cinema-films-greatest', 'Culture / Mass media / Film and cinema / Films / Greatest'),
  ('culture-mass-media-film-and-cinema-lists-films-highest-grossing', 'culture-mass-media-film-and-cinema-films-highest-grossing', 'Culture / Mass media / Film and cinema / Films / Highest-grossing'),
  ('culture-mass-media-film-and-cinema-lists-films-most-expensive', 'culture-mass-media-film-and-cinema-films-most-expensive', 'Culture / Mass media / Film and cinema / Films / Most expensive'),
  ('culture-mass-media-film-and-cinema-lists-films-preserved-films', 'culture-mass-media-film-and-cinema-films-preserved-films', 'Culture / Mass media / Film and cinema / Films / Preserved films'),
  ('culture-mass-media-film-and-cinema-lists-films-rated-nc-17', 'culture-mass-media-film-and-cinema-films-rated-nc-17', 'Culture / Mass media / Film and cinema / Films / Rated NC-17'),
  ('culture-mass-media-film-and-cinema-lists-films-trilogies', 'culture-mass-media-film-and-cinema-films-trilogies', 'Culture / Mass media / Film and cinema / Films / Trilogies'),
  ('culture-mass-media-film-and-cinema-lists-films-worst', 'culture-mass-media-film-and-cinema-films-worst', 'Culture / Mass media / Film and cinema / Films / Worst'),
  ('culture-literature-lists-magazines-anomalous-phenomena-magazines', 'culture-mass-media-print-media-magazines-anomalous-phenomena', 'Culture / Mass media / Print media / Magazines / Anomalous phenomena'),
  ('culture-literature-lists-magazines-men-s-magazines', 'culture-mass-media-print-media-magazines-mens-magazines', 'Culture / Mass media / Print media / Magazines / Men''s magazines'),
  ('culture-literature-lists-magazines-teen-magazines', 'culture-mass-media-print-media-magazines-teen-magazines', 'Culture / Mass media / Print media / Magazines / Teen magazines'),
  ('culture-literature-lists-magazines-women-s-magazines', 'culture-mass-media-print-media-magazines-womens-magazines', 'Culture / Mass media / Print media / Magazines / Women''s magazines'),
  ('culture-performing-arts-music-lists-electronic-music-lists-record-labels', 'culture-performing-arts-music-electronic-music-record-labels', 'Culture / Performing arts / Music / Electronic music / Record labels'),
  ('culture-performing-arts-music-lists-electronic-music-lists-music-genres', 'culture-performing-arts-music-electronic-music-sub-genres', 'Culture / Performing arts / Music / Electronic music / Sub-genres'),
  ('culture-performing-arts-music-lists-songs-and-compositions-christmas-carols', 'culture-performing-arts-music-songs-and-compositions-christmas-carols', 'Culture / Performing arts / Music / Songs and compositions / Christmas carols'),
  ('culture-performing-arts-music-lists-songs-and-compositions-christmas-number-one-singles-uk', 'culture-performing-arts-music-songs-and-compositions-christmas-number-one-singles-uk', 'Culture / Performing arts / Music / Songs and compositions / Christmas number-one singles (UK)'),
  ('culture-performing-arts-music-lists-songs-and-compositions-famous-operas', 'culture-performing-arts-music-songs-and-compositions-famous-operas', 'Culture / Performing arts / Music / Songs and compositions / Famous operas'),
  ('culture-performing-arts-music-lists-songs-and-compositions-operettas', 'culture-performing-arts-music-songs-and-compositions-operettas', 'Culture / Performing arts / Music / Songs and compositions / Operettas'),
  ('culture-performing-arts-music-lists-video-game-music-video-game-musicians', 'culture-performing-arts-music-video-game-music-composers', 'Culture / Performing arts / Music / Video game music / Composers'),
  ('culture-sports-ball-games-association-football-lists-100-greatest-living-football-players', 'culture-sports-ball-games-association-football-100-greatest-living-football-players', 'Culture / Sports / Ball games / Association football / 100 Greatest Living Football Players'),
  ('culture-sports-ball-games-baseball-lists-highest-paid-baseball-players', 'culture-sports-ball-games-baseball-highest-paid-players', 'Culture / Sports / Ball games / Baseball / Highest-paid players'),
  ('culture-sports-ball-games-baseball-lists-lifetime-home-run-leaders', 'culture-sports-ball-games-baseball-lifetime-home-run-leaders', 'Culture / Sports / Ball games / Baseball / Lifetime home run leaders'),
  ('culture-sports-ball-games-baseball-lists-triple-crown', 'culture-sports-ball-games-baseball-triple-crown', 'Culture / Sports / Ball games / Baseball / Triple Crown'),
  ('culture-sports-combat-sports-martial-arts-lists-martial-arts-weapons', 'culture-sports-combat-sports-martial-arts-weapons', 'Culture / Sports / Combat sports / Martial arts / Weapons'),
  ('culture-sports-lists-ski-areas', 'culture-sports-winter-sports-skiing-ski-areas', 'Culture / Sports / Winter sports / Skiing / Ski areas'),
  ('history-lists-roman-governorships-of-britain', 'history-ancient-civilizations-roman-britain-governorships', 'History / Ancient civilizations / Roman / Britain / Governorships'),
  ('science-lists-muscles', 'science-biology-branches-of-biology-anatomy-muscles', 'Science / Biology / Branches of biology / Anatomy / Muscles'),
  ('science-lists-chemistry-lists-stable-isotopes', 'science-chemistry-elements-isotopes-stable', 'Science / Chemistry / Elements / Isotopes / Stable'),
  ('science-lists-physics-lists-equations-in-classical-mechanics', 'science-physics-branches-of-physics-classical-mechanics-equations', 'Science / Physics / Branches of physics / Classical mechanics / Equations'),
  ('society-lists-european-sovereign-debt-crisis-acronyms', 'society-economy-and-business-finance-european-sovereign-debt-crisis-acronyms', 'Society / Economy and business / Finance / European sovereign-debt crisis / Acronyms'),
  ('society-lists-current-members-of-the-united-states-congress', 'society-government-united-states-congress-current-members', 'Society / Government / United States / Congress / Current members'),
  ('society-lists-english-words-list', 'society-linguistics-languages-english-words', 'Society / Linguistics / Languages / English / Words'),
  ('tech-lists-amd-microprocessors', 'tech-computing-hardware-microprocessors-amd', 'Tech / Computing / Hardware / Microprocessors / AMD'),
  ('tech-lists-intel-microprocessors', 'tech-computing-hardware-microprocessors-intel', 'Tech / Computing / Hardware / Microprocessors / Intel'),
  ('tech-lists-screen-readers', 'tech-computing-software-accessibility-screen-readers', 'Tech / Computing / Software / Accessibility / Screen readers'),
  ('tech-lists-test-automation', 'tech-computing-software-software-engineering-test-automation', 'Tech / Computing / Software / Software engineering / Test automation'),
  ('tech-lists-html-editors', 'tech-computing-software-web-development-html-editors', 'Tech / Computing / Software / Web development / HTML editors'),
  ('tech-lists-largest-bridges', 'tech-construction-and-built-environment-civil-engineering-bridges-largest', 'Tech / Construction and built environment / Civil engineering / Bridges / Largest'),
  ('tech-lists-longest-tunnels', 'tech-construction-and-built-environment-civil-engineering-tunnels-longest', 'Tech / Construction and built environment / Civil engineering / Tunnels / Longest'),
  ('tech-lists-http-status-codes', 'tech-internet-and-web-protocols-http-status-codes', 'Tech / Internet and Web / Protocols / HTTP / Status codes'),
  ('tech-lists-busiest-airports', 'tech-transport-technology-aircraft-airports-busiest-airports', 'Tech / Transport technology / Aircraft / Airports / Busiest airports'),
  ('culture-literature-lists-fiction-comics-comic-books-dc-comics', 'culture-literature-fiction-comics-comic-books-dc-comics', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics'),
  ('culture-literature-lists-fiction-comics-comic-books-marvel-comics', 'culture-literature-fiction-comics-comic-books-marvel-comics', 'Culture / Literature / Fiction / Comics / Comic books / Marvel Comics'),
  ('culture-literature-lists-fiction-comics-best-selling-manga', 'culture-literature-fiction-comics-manga-best-selling', 'Culture / Literature / Fiction / Comics / Manga / Best-selling'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-animated-series', 'culture-mass-media-broadcast-media-television-programs-animated-series', 'Culture / Mass media / Broadcast media / Television / Programs / Animated series'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-anime-lists', 'culture-mass-media-broadcast-media-television-programs-anime', 'Culture / Mass media / Broadcast media / Television / Programs / Anime'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-bl-dramas', 'culture-mass-media-broadcast-media-television-programs-bl-dramas', 'Culture / Mass media / Broadcast media / Television / Programs / BL dramas'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-british-tv-shows-remade-for-the-american-market', 'culture-mass-media-broadcast-media-television-programs-british-shows-remade-for-american-market', 'Culture / Mass media / Broadcast media / Television / Programs / British shows remade for American market'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-children-s-television-series', 'culture-mass-media-broadcast-media-television-programs-childrens-series', 'Culture / Mass media / Broadcast media / Television / Programs / Children''s series'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-comedies', 'culture-mass-media-broadcast-media-television-programs-comedies', 'Culture / Mass media / Broadcast media / Television / Programs / Comedies'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-cult-television-shows', 'culture-mass-media-broadcast-media-television-programs-cult-shows', 'Culture / Mass media / Broadcast media / Television / Programs / Cult shows'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-dramedies', 'culture-mass-media-broadcast-media-television-programs-dramedies', 'Culture / Mass media / Broadcast media / Television / Programs / Dramedies'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-most-watched-television-episodes', 'culture-mass-media-broadcast-media-television-programs-most-watched-episodes', 'Culture / Mass media / Broadcast media / Television / Programs / Most-watched episodes'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-sci-fi-tv-programs', 'culture-mass-media-broadcast-media-television-programs-sci-fi', 'Culture / Mass media / Broadcast media / Television / Programs / Sci-fi'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-soap-operas', 'culture-mass-media-broadcast-media-television-programs-soap-operas', 'Culture / Mass media / Broadcast media / Television / Programs / Soap operas'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-spin-off-shows', 'culture-mass-media-broadcast-media-television-programs-spin-off-shows', 'Culture / Mass media / Broadcast media / Television / Programs / Spin-off shows'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-uk-television-series', 'culture-mass-media-broadcast-media-television-programs-uk-series', 'Culture / Mass media / Broadcast media / Television / Programs / UK series'),
  ('culture-mass-media-broadcast-media-television-lists-tv-stations-in-north-america', 'culture-mass-media-broadcast-media-television-stations-north-america', 'Culture / Mass media / Broadcast media / Television / Stations / North America'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-bands-hardcore-punk-bands', 'culture-performing-arts-music-musicians-and-groups-bands-hardcore-punk', 'Culture / Performing arts / Music / Musicians and groups / Bands / Hardcore punk'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-composers-classical-music-composers', 'culture-performing-arts-music-musicians-and-groups-composers-classical', 'Culture / Performing arts / Music / Musicians and groups / Composers / Classical'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-composers-songwriters-hall-of-fame', 'culture-performing-arts-music-musicians-and-groups-composers-songwriters-hall-of-fame', 'Culture / Performing arts / Music / Musicians and groups / Composers / Songwriters Hall of Fame'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-alternative-music-artists', 'culture-performing-arts-music-musicians-and-groups-musicians-alternative', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Alternative'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-ambient-artists', 'culture-performing-arts-music-musicians-and-groups-musicians-ambient', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Ambient'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-best-selling-music-artists', 'culture-performing-arts-music-musicians-and-groups-musicians-best-selling', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Best-selling'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-disco-artists', 'culture-performing-arts-music-musicians-and-groups-musicians-disco', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Disco'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-grammy-hall-of-fame-award-recipients', 'culture-performing-arts-music-musicians-and-groups-musicians-grammy-hall-of-fame-recipients', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Grammy Hall of Fame recipients'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-hip-hop-artists', 'culture-performing-arts-music-musicians-and-groups-musicians-hip-hop', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Hip hop'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-r-b-musicians', 'culture-performing-arts-music-musicians-and-groups-musicians-r-and-b', 'Culture / Performing arts / Music / Musicians and groups / Musicians / R&B'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-soul-musicians', 'culture-performing-arts-music-musicians-and-groups-musicians-soul', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Soul'),
  ('culture-performing-arts-music-lists-songs-and-compositions-compositions-of-johann-sebastian-bach', 'culture-performing-arts-music-songs-and-compositions-by-composer-j-s-bach', 'Culture / Performing arts / Music / Songs and compositions / By composer / J.S. Bach'),
  ('culture-sports-ball-games-association-football-lists-football-clubs-in-france', 'culture-sports-ball-games-association-football-clubs-france', 'Culture / Sports / Ball games / Association football / Clubs / France'),
  ('culture-sports-ball-games-association-football-lists-women-s-association-football-clubs', 'culture-sports-ball-games-association-football-clubs-womens', 'Culture / Sports / Ball games / Association football / Clubs / Women''s'),
  ('culture-sports-ball-games-association-football-lists-national-association-football-teams-by-nickname', 'culture-sports-ball-games-association-football-national-teams-by-nickname', 'Culture / Sports / Ball games / Association football / National teams / By nickname'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners'),
  ('culture-sports-lists-judo-techniques', 'culture-sports-combat-sports-martial-arts-judo-techniques', 'Culture / Sports / Combat sports / Martial arts / Judo / Techniques'),
  ('culture-literature-lists-fiction-comics-comic-books-dc-comics-elseworlds', 'culture-literature-fiction-comics-comic-books-dc-comics-elseworlds', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Elseworlds'),
  ('culture-literature-lists-fiction-comics-comic-books-dc-comics-dc-universe-locations', 'culture-literature-fiction-comics-comic-books-dc-comics-universe-locations', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Universe locations'),
  ('culture-literature-lists-fiction-comics-comic-books-marvel-comics-avengers', 'culture-literature-fiction-comics-comic-books-marvel-comics-avengers', 'Culture / Literature / Fiction / Comics / Comic books / Marvel Comics / Avengers'),
  ('culture-literature-lists-fiction-comics-comic-books-marvel-comics-x-men', 'culture-literature-fiction-comics-comic-books-marvel-comics-x-men', 'Culture / Literature / Fiction / Comics / Comic books / Marvel Comics / X-Men'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-1st-base', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-1st-base', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / 1st Base'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-2nd-base', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-2nd-base', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / 2nd Base'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-3rd-base', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-3rd-base', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / 3rd Base'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-catcher', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-catcher', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / Catcher'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-outfield', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-outfield', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / Outfield'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-pitcher', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-pitcher', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / Pitcher'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-shortstop', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-shortstop', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / Shortstop'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-1st-base', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-1st-base', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / 1st Base'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-2nd-base', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-2nd-base', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / 2nd Base'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-3rd-base', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-3rd-base', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / 3rd Base'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-catcher', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-catcher', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / Catcher'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-outfield', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-outfield', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / Outfield'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-pitcher', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-pitcher', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / Pitcher'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-shortstop', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-shortstop', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / Shortstop'),
  ('culture-literature-lists-fiction-comics-comic-books-dc-comics-justice-league-members', 'culture-literature-fiction-comics-comic-books-dc-comics-justice-league-members', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Justice League / Members'),
  ('culture-literature-lists-fiction-comics-comic-books-dc-comics-legion-of-super-heroes-members', 'culture-literature-fiction-comics-comic-books-dc-comics-legion-of-super-heroes-members', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Legion of Super-Heroes / Members'),
  ('culture-literature-lists-fiction-comics-comic-books-dc-comics-superman-enemies', 'culture-literature-fiction-comics-comic-books-dc-comics-superman-enemies', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Superman / Enemies')
)
UPDATE atoms a SET
  id = m.new_id,
  name = (string_to_array(m.new_path, ' / '))[array_length(string_to_array(m.new_path, ' / '), 1)],
  path = m.new_path,
  path_parts = string_to_array(m.new_path, ' / '),
  depth = array_length(string_to_array(m.new_path, ' / '), 1),
  updated_at = now()
FROM moves m
WHERE a.id = m.old_id;

-- Batch 2.5: insert 4 deferred deep containers (parents created by Batch 2 above)
INSERT INTO atoms (id, name, path, path_parts, realm_id, realm_name, depth, type, kettle, is_leaf, theme_tags, realm_tags, pillar_tags, skin_tags, meta, created_at, updated_at) VALUES
  ('culture-literature-fiction-comics-comic-books-dc-comics-justice-league', 'Justice League', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Justice League', ARRAY['Culture','Literature','Fiction','Comics','Comic books','DC Comics','Justice League']::text[], 'culture', 'Culture', 7, 'event', 'Accepted', false, ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], '{}'::jsonb, now(), now()),
  ('culture-literature-fiction-comics-comic-books-dc-comics-legion-of-super-heroes', 'Legion of Super-Heroes', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Legion of Super-Heroes', ARRAY['Culture','Literature','Fiction','Comics','Comic books','DC Comics','Legion of Super-Heroes']::text[], 'culture', 'Culture', 7, 'event', 'Accepted', false, ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], '{}'::jsonb, now(), now()),
  ('culture-literature-fiction-comics-comic-books-dc-comics-superman', 'Superman', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Superman', ARRAY['Culture','Literature','Fiction','Comics','Comic books','DC Comics','Superman']::text[], 'culture', 'Culture', 7, 'event', 'Accepted', false, ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], '{}'::jsonb, now(), now()),
  ('culture-performing-arts-music-songs-and-compositions-by-composer', 'By composer', 'Culture / Performing arts / Music / Songs and compositions / By composer', ARRAY['Culture','Performing arts','Music','Songs and compositions','By composer']::text[], 'culture', 'Culture', 5, 'event', 'Accepted', false, ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], '{}'::jsonb, now(), now())
ON CONFLICT (id) DO NOTHING;

DO $$
DECLARE
  new_total int; expected int := 4978 + 4;
  leaf_with_children int; depth_mismatch int; skipped_level int; dup_id int;
BEGIN
  SELECT count(*) INTO new_total FROM atoms;
  IF new_total <> expected THEN RAISE EXCEPTION 'BATCH-2 FAIL: expected % atoms, found %', expected, new_total; END IF;
  SELECT count(*) INTO leaf_with_children FROM atoms p WHERE p.is_leaf=true AND EXISTS (SELECT 1 FROM atoms c WHERE c.depth>p.depth AND c.path_parts[1:p.depth]=p.path_parts);
  IF leaf_with_children <> 0 THEN RAISE EXCEPTION 'BATCH-2 FAIL: leaf-with-children=%', leaf_with_children; END IF;
  SELECT count(*) INTO depth_mismatch FROM atoms WHERE depth <> array_length(path_parts,1);
  IF depth_mismatch <> 0 THEN RAISE EXCEPTION 'BATCH-2 FAIL: depth-mismatch=%', depth_mismatch; END IF;
  SELECT count(*) INTO skipped_level FROM atoms a WHERE a.depth > 1 AND NOT EXISTS (SELECT 1 FROM atoms p WHERE p.path = array_to_string(a.path_parts[1:a.depth-1], ' / '));
  IF skipped_level <> 0 THEN RAISE EXCEPTION 'BATCH-2 FAIL: skipped-level=%', skipped_level; END IF;
  SELECT count(*) INTO dup_id FROM (SELECT id FROM atoms GROUP BY id HAVING count(*)>1) x;
  IF dup_id <> 0 THEN RAISE EXCEPTION 'BATCH-2 FAIL: dup-id=%', dup_id; END IF;
  RAISE NOTICE 'BATCH-2 OK: + % rows', new_total - 4978;
END$$;
