-- Lists Disposition · COMBINED BATCH 2/3/4 + 2.5 · all 437 non-destructive moves
-- Date: 2026-05-19
-- Single transaction: 334 INTRA_REALM + 35 CROSS_REALM + 68 IMPORT_REALIZE + 4 deferred INSERTs + is_leaf recompute.

DO $$
DECLARE total int;
BEGIN
  SELECT count(*) INTO total FROM atoms;
  IF total <> 4978 THEN RAISE EXCEPTION 'BATCH-COMBINED PRE-FLIGHT FAIL: expected 4978 atoms, found %', total; END IF;
END$$;

WITH moves(old_id, new_id, new_path, new_realm_name) AS (VALUES
  ('history-lists-historical-sites', 'history-historical-sites', 'History / Historical sites', 'History'),
  ('philosophy-lists-philosophers-role-category', 'philosophy-philosophers', 'Philosophy / Philosophers', 'Philosophy'),
  ('culture-literature-lists-books', 'culture-literature-books', 'Culture / Literature / Books', 'Culture'),
  ('culture-literature-lists-electronic-literature', 'culture-literature-electronic-literature', 'Culture / Literature / Electronic literature', 'Culture'),
  ('culture-literature-lists-publishers', 'culture-literature-publishers', 'Culture / Literature / Publishers', 'Culture'),
  ('culture-literature-lists-books-writers', 'culture-literature-writers', 'Culture / Literature / Writers', 'Culture'),
  ('self-lists-entertainer-deaths-while-performing', 'culture-performing-arts-notable-on-stage-deaths', 'Culture / Performing arts / Notable on-stage deaths', 'Culture'),
  ('culture-sports-lists-climbing', 'culture-sports-climbing', 'Culture / Sports / Climbing', 'Culture'),
  ('culture-sports-lists-sports-leagues', 'culture-sports-sports-leagues', 'Culture / Sports / Sports leagues', 'Culture'),
  ('health-lists-reference-ranges-for-common-blood-tests', 'health-health-sciences-reference-ranges-for-common-blood-tests', 'Health / Health sciences / Reference ranges for common blood tests', 'Health'),
  ('health-lists-acronyms-in-healthcare', 'health-medicine-acronyms-in-healthcare', 'Health / Medicine / Acronyms in healthcare', 'Health'),
  ('health-lists-alternative-medicine-modalities', 'health-medicine-alternative-medicine-modalities', 'Health / Medicine / Alternative medicine modalities', 'Health'),
  ('health-lists-medical-abbreviations', 'health-medicine-medical-abbreviations', 'Health / Medicine / Medical abbreviations', 'Health'),
  ('health-lists-surgical-procedures', 'health-medicine-surgical-procedures', 'Health / Medicine / Surgical procedures', 'Health'),
  ('society-lists-diagnostic-classification-and-rating-scales', 'health-mental-health-diagnostic-classification-and-rating-scales', 'Health / Mental health / Diagnostic classification and rating scales', 'Health'),
  ('health-lists-psychotherapies', 'health-mental-health-psychotherapies', 'Health / Mental health / Psychotherapies', 'Health'),
  ('science-lists-causes-of-death', 'health-public-health-causes-of-death', 'Health / Public health / Causes of death', 'Health'),
  ('history-lists-historians-by-subfield', 'history-historians-by-subfield', 'History / Historians / By subfield', 'History'),
  ('history-lists-coups-and-coup-attempts', 'history-historical-events-coups-and-coup-attempts', 'History / Historical events / Coups and coup attempts', 'History'),
  ('history-lists-disasters', 'history-historical-events-disasters', 'History / Historical events / Disasters', 'History'),
  ('human-activities-lists-environmental-disasters-list', 'history-historical-events-environmental-disasters', 'History / Historical events / Environmental disasters', 'History'),
  ('history-lists-epidemics', 'history-historical-events-epidemics', 'History / Historical events / Epidemics', 'History'),
  ('history-lists-famous-deaths-by-cause', 'history-historical-events-famous-deaths-by-cause', 'History / Historical events / Famous deaths by cause', 'History'),
  ('history-lists-famous-speeches', 'history-historical-events-famous-speeches', 'History / Historical events / Famous speeches', 'History'),
  ('history-lists-helicopter-prison-escapes', 'history-historical-events-helicopter-prison-escapes', 'History / Historical events / Helicopter prison escapes', 'History'),
  ('history-lists-inventions', 'history-historical-events-inventions', 'History / Historical events / Inventions', 'History'),
  ('history-lists-inventors-killed-by-their-own-inventions', 'history-historical-events-inventors-killed-by-their-own-inventions', 'History / Historical events / Inventors killed by their own inventions', 'History'),
  ('history-lists-kidnappings', 'history-historical-events-kidnappings', 'History / Historical events / Kidnappings', 'History'),
  ('history-lists-missing-treasure', 'history-historical-events-missing-treasure', 'History / Historical events / Missing treasure', 'History'),
  ('history-lists-nobel-prizes', 'history-historical-events-nobel-prizes', 'History / Historical events / Nobel Prizes', 'History'),
  ('self-lists-political-self-immolations', 'history-historical-events-political-self-immolations', 'History / Historical events / Political self-immolations', 'History'),
  ('history-lists-recessions', 'history-historical-events-recessions', 'History / Historical events / Recessions', 'History'),
  ('history-lists-revolutions-and-rebellions', 'history-historical-events-revolutions-and-rebellions', 'History / Historical events / Revolutions and rebellions', 'History'),
  ('history-lists-riots', 'history-historical-events-riots', 'History / Historical events / Riots', 'History'),
  ('tech-lists-terrorist-incidents', 'history-historical-events-terrorist-incidents', 'History / Historical events / Terrorist incidents', 'History'),
  ('history-lists-ticker-tape-parades-in-new-york-city', 'history-historical-events-ticker-tape-parades-in-new-york-city', 'History / Historical events / Ticker-tape parades in New York City', 'History'),
  ('history-lists-treaties', 'history-historical-events-treaties', 'History / Historical events / Treaties', 'History'),
  ('history-lists-former-sovereign-states', 'history-historical-states-former-sovereign-states', 'History / Historical states / Former sovereign states', 'History'),
  ('history-lists-battles', 'history-military-history-battles', 'History / Military history / Battles', 'History'),
  ('human-activities-lists-battles-by-casualties', 'history-military-history-battles-by-casualties', 'History / Military history / Battles by casualties', 'History'),
  ('history-lists-military-disasters', 'history-military-history-disasters', 'History / Military history / Disasters', 'History'),
  ('history-lists-guerrilla-movements', 'history-military-history-guerrilla-movements', 'History / Military history / Guerrilla movements', 'History'),
  ('history-lists-invasions', 'history-military-history-invasions', 'History / Military history / Invasions', 'History'),
  ('history-lists-military-operations', 'history-military-history-operations', 'History / Military history / Operations', 'History'),
  ('history-lists-sieges', 'history-military-history-sieges', 'History / Military history / Sieges', 'History'),
  ('human-activities-lists-wars-by-death-toll', 'history-wars-by-death-toll', 'History / Wars / By death toll', 'History'),
  ('history-lists-civil-wars-list', 'history-wars-civil-wars', 'History / Wars / Civil wars', 'History'),
  ('justice-lists-investigative-journalism-outlets', 'justice-evidence-investigative-journalism-outlets', 'Justice / Evidence / Investigative journalism outlets', 'Justice'),
  ('justice-lists-notable-whistleblowers-reference', 'justice-evidence-notable-whistleblowers', 'Justice / Evidence / Notable whistleblowers', 'Justice'),
  ('justice-lists-whistleblower-support-organizations', 'justice-evidence-whistleblower-support-organizations', 'Justice / Evidence / Whistleblower support organizations', 'Justice'),
  ('justice-lists-truth-commissions-historical', 'justice-progress-truth-commissions', 'Justice / Progress / Truth commissions', 'Justice'),
  ('human-activities-lists-methods-of-capital-punishment', 'justice-prosecutions-methods-of-capital-punishment', 'Justice / Prosecutions / Methods of capital punishment', 'Justice'),
  ('justice-lists-notable-accountability-cases-reference', 'justice-prosecutions-notable-accountability-cases', 'Justice / Prosecutions / Notable accountability cases', 'Justice'),
  ('math-lists-games-mathematical', 'math-concepts-mathematical-games', 'Math / Concepts / Mathematical games', 'Math'),
  ('math-lists-principia-mathematica-glossary-items', 'math-foundations-and-meta-mathematics-principia-mathematica-glossary', 'Math / Foundations and meta-mathematics / Principia Mathematica glossary', 'Math'),
  ('math-lists-integrals', 'math-mathematical-objects-integrals', 'Math / Mathematical objects / Integrals', 'Math'),
  ('math-lists-mathematical-series', 'math-mathematical-objects-mathematical-series', 'Math / Mathematical objects / Mathematical series', 'Math'),
  ('math-lists-prime-numbers-list', 'math-mathematical-objects-prime-numbers', 'Math / Mathematical objects / Prime numbers', 'Math'),
  ('math-lists-shapes-with-metaphorical-names', 'math-mathematical-objects-shapes-with-metaphorical-names', 'Math / Mathematical objects / Shapes with metaphorical names', 'Math'),
  ('religion-lists-angels-list', 'religion-beings-angels', 'Religion / Beings / Angels', 'Religion'),
  ('religion-lists-deities-list', 'religion-beings-deities', 'Religion / Beings / Deities', 'Religion'),
  ('religion-lists-demons-list', 'religion-beings-demons', 'Religion / Beings / Demons', 'Religion'),
  ('human-activities-lists-mudras', 'religion-concepts-mudras', 'Religion / Concepts / Mudras', 'Religion'),
  ('religion-lists-people-claimed-to-be-jesus', 'religion-issues-and-debates-messianic-claimants', 'Religion / Issues and debates / Messianic claimants', 'Religion'),
  ('religion-lists-founders-religious-list', 'religion-religious-roles-founders', 'Religion / Religious roles / Founders', 'Religion'),
  ('religion-lists-popes-list', 'religion-religious-roles-popes', 'Religion / Religious roles / Popes', 'Religion'),
  ('religion-lists-saints-list', 'religion-religious-roles-saints', 'Religion / Religious roles / Saints', 'Religion'),
  ('science-lists-astronomy-lists-astronomical-catalogues', 'science-astronomy-and-space-science-astronomical-catalogues', 'Science / Astronomy and space science / Astronomical catalogues', 'Science'),
  ('science-lists-astronomy-lists-astronomical-objects-named-after-people', 'science-astronomy-and-space-science-astronomical-objects-named-after-people', 'Science / Astronomy and space science / Astronomical objects named after people', 'Science'),
  ('science-lists-astronomy-lists-astronomical-societies', 'science-astronomy-and-space-science-astronomical-societies', 'Science / Astronomy and space science / Astronomical societies', 'Science'),
  ('science-lists-astronomy-lists-astronomical-symbols', 'science-astronomy-and-space-science-astronomical-symbols', 'Science / Astronomy and space science / Astronomical symbols', 'Science'),
  ('science-lists-astronomy-lists-future-astronomical-events', 'science-astronomy-and-space-science-future-astronomical-events', 'Science / Astronomy and space science / Future astronomical events', 'Science'),
  ('science-lists-astronomy-lists-most-distant-astronomical-objects', 'science-astronomy-and-space-science-most-distant-astronomical-objects', 'Science / Astronomy and space science / Most distant astronomical objects', 'Science'),
  ('science-lists-astronomy-lists-space-telescopes', 'science-astronomy-and-space-science-space-telescopes', 'Science / Astronomy and space science / Space telescopes', 'Science'),
  ('science-lists-astronomy-lists-telescopes', 'science-astronomy-and-space-science-telescopes', 'Science / Astronomy and space science / Telescopes', 'Science'),
  ('science-lists-biological-journals', 'science-biology-biological-journals', 'Science / Biology / Biological journals', 'Science'),
  ('science-lists-chemistry-lists-compounds-list', 'science-chemistry-compounds', 'Science / Chemistry / Compounds', 'Science'),
  ('science-lists-physics-lists-laws-in-science', 'science-scientific-method-and-meta-science-laws-in-science', 'Science / Scientific method and meta-science / Laws in science', 'Science'),
  ('science-lists-physics-lists-letters-used-in-mathematics-and-science', 'science-scientific-method-and-meta-science-letters-used-in-mathematics-and-science', 'Science / Scientific method and meta-science / Letters used in mathematics and science', 'Science'),
  ('culture-literature-lists-scientific-journals', 'science-scientific-method-and-meta-science-scientific-journals', 'Science / Scientific method and meta-science / Scientific journals', 'Science'),
  ('self-lists-disappeared-mysteriously', 'self-person-disappeared-mysteriously', 'Self / Person / Disappeared mysteriously', 'Self'),
  ('self-lists-eponymous-laws', 'self-person-eponymous-laws', 'Self / Person / Eponymous laws', 'Self'),
  ('self-lists-eponyms', 'self-person-eponyms', 'Self / Person / Eponyms', 'Self'),
  ('society-lists-banks-list', 'society-economy-and-business-banks', 'Society / Economy and business / Banks', 'Society'),
  ('society-lists-companies-list', 'society-economy-and-business-companies', 'Society / Economy and business / Companies', 'Society'),
  ('society-lists-cooperatives-list', 'society-economy-and-business-cooperatives', 'Society / Economy and business / Cooperatives', 'Society'),
  ('society-lists-corporate-assets', 'society-economy-and-business-corporate-assets', 'Society / Economy and business / Corporate assets', 'Society'),
  ('society-lists-economists', 'society-economy-and-business-economists', 'Society / Economy and business / Economists', 'Society'),
  ('society-lists-employer-associations-list', 'society-economy-and-business-employer-associations', 'Society / Economy and business / Employer associations', 'Society'),
  ('history-lists-tariffs', 'society-economy-and-business-tariffs', 'Society / Economy and business / Tariffs', 'Society'),
  ('society-lists-academic-fields', 'society-education-system-academic-fields', 'Society / Education (system) / Academic fields', 'Society'),
  ('society-lists-admissions-tests', 'society-education-system-admissions-tests', 'Society / Education (system) / Admissions tests', 'Society'),
  ('society-lists-fields-of-doctoral-studies', 'society-education-system-fields-of-doctoral-studies', 'Society / Education (system) / Fields of doctoral studies', 'Society'),
  ('society-lists-universities-and-colleges-list', 'society-education-system-universities-and-colleges', 'Society / Education (system) / Universities and colleges', 'Society'),
  ('society-lists-micronations', 'society-government-micronations', 'Society / Government / Micronations', 'Society'),
  ('society-lists-national-legislatures', 'society-government-national-legislatures', 'Society / Government / National legislatures', 'Society'),
  ('society-lists-case-law-list', 'society-law-case-law', 'Society / Law / Case law', 'Society'),
  ('history-lists-united-states-supreme-court-cases', 'society-law-united-states-supreme-court-cases', 'Society / Law / United States Supreme Court cases', 'Society'),
  ('society-lists-acronyms', 'society-linguistics-acronyms', 'Society / Linguistics / Acronyms', 'Society'),
  ('society-lists-shibboleths', 'society-linguistics-shibboleths', 'Society / Linguistics / Shibboleths', 'Society'),
  ('society-lists-symbols-list', 'society-linguistics-symbols', 'Society / Linguistics / Symbols', 'Society'),
  ('self-lists-terms-for-men', 'society-linguistics-terms-for-men', 'Society / Linguistics / Terms for men', 'Society'),
  ('society-lists-intelligence-agencies-list', 'society-military-and-security-intelligence-agencies', 'Society / Military and security / Intelligence agencies', 'Society'),
  ('society-lists-secret-police-organizations', 'society-military-and-security-secret-police-organizations', 'Society / Military and security / Secret police organizations', 'Society'),
  ('tech-lists-terrorist-groups', 'society-military-and-security-terrorist-groups', 'Society / Military and security / Terrorist groups', 'Society'),
  ('tech-lists-military-weapons-list', 'society-military-and-security-weapons', 'Society / Military and security / Weapons', 'Society'),
  ('society-lists-political-parties', 'society-politics-political-parties', 'Society / Politics / Political parties', 'Society'),
  ('society-lists-civic-fraternal-service-professional-organizations', 'society-social-institutions-civic-fraternal-service-professional-organizations', 'Society / Social institutions / Civic, fraternal, service, professional organizations', 'Society'),
  ('society-lists-environmental-organizations', 'society-social-institutions-environmental-organizations', 'Society / Social institutions / Environmental organizations', 'Society'),
  ('society-lists-guide-dog-schools', 'society-social-institutions-guide-dog-schools', 'Society / Social institutions / Guide dog schools', 'Society'),
  ('society-lists-honorary-societies', 'society-social-institutions-honorary-societies', 'Society / Social institutions / Honorary societies', 'Society'),
  ('society-lists-think-tanks', 'society-social-institutions-think-tanks', 'Society / Social institutions / Think tanks', 'Society'),
  ('society-lists-feminism-list', 'society-social-movements-feminism', 'Society / Social movements / Feminism', 'Society'),
  ('history-lists-strikes', 'society-social-movements-strikes', 'Society / Social movements / Strikes', 'Society'),
  ('society-lists-social-science-journals', 'society-social-sciences-journals', 'Society / Social sciences / Journals', 'Society'),
  ('society-lists-lifestyles', 'society-society-concepts-lifestyles', 'Society / Society concepts / Lifestyles', 'Society'),
  ('society-lists-prizes-medals-and-awards', 'society-society-concepts-prizes-medals-and-awards', 'Society / Society concepts / Prizes, medals, and awards', 'Society'),
  ('society-lists-scandals-with-gate-suffix', 'society-society-concepts-scandals-with-gate-suffix', 'Society / Society concepts / Scandals with "-gate" suffix', 'Society'),
  ('tech-lists-character-sets-and-encodings', 'tech-computing-character-encoding', 'Tech / Computing / Character encoding', 'Tech'),
  ('tech-lists-demolished-landmarks', 'tech-construction-and-built-environment-demolished-landmarks', 'Tech / Construction and built environment / Demolished landmarks', 'Tech'),
  ('tech-lists-heritage-registers', 'tech-construction-and-built-environment-heritage-registers', 'Tech / Construction and built environment / Heritage registers', 'Tech'),
  ('tech-lists-tallest-buildings', 'tech-construction-and-built-environment-tallest-buildings', 'Tech / Construction and built environment / Tallest buildings', 'Tech'),
  ('tech-lists-largest-energy-infrastructure', 'tech-energy-technology-largest-energy-infrastructure', 'Tech / Energy technology / Largest energy infrastructure', 'Tech'),
  ('society-lists-emoticons', 'tech-internet-and-web-emoticons', 'Tech / Internet and Web / Emoticons', 'Tech'),
  ('tech-lists-wikis-list', 'tech-internet-and-web-wikis', 'Tech / Internet and Web / Wikis', 'Tech'),
  ('tech-lists-missile-list', 'tech-military-technology-missiles', 'Tech / Military technology / Missiles', 'Tech'),
  ('tech-lists-nato-reporting-names', 'tech-military-technology-nato-reporting-names', 'Tech / Military technology / NATO reporting names', 'Tech'),
  ('culture-games-lists-japanese-board-games', 'culture-games-board-games-japanese-board-games', 'Culture / Games / Board games / Japanese board games', 'Culture'),
  ('culture-games-lists-mancala-variants', 'culture-games-board-games-mancala-variants', 'Culture / Games / Board games / Mancala variants', 'Culture'),
  ('culture-games-lists-board-game-publishers', 'culture-games-board-games-publishers', 'Culture / Games / Board games / Publishers', 'Culture'),
  ('culture-games-lists-miniature-wargames', 'culture-games-tabletop-games-miniature-wargames', 'Culture / Games / Tabletop games / Miniature wargames', 'Culture'),
  ('culture-games-video-games-lists-arcade-games', 'culture-games-video-games-arcade-games', 'Culture / Games / Video games / Arcade games', 'Culture'),
  ('culture-games-video-games-lists-console-palettes', 'culture-games-video-games-console-palettes', 'Culture / Games / Video games / Console palettes', 'Culture'),
  ('science-lists-earth-sciences-lists-birthstones', 'culture-gastronomy-materials-birthstones', 'Culture / Gastronomy / Materials / Birthstones', 'Culture'),
  ('culture-literature-lists-books-banned-books', 'culture-literature-books-banned-books', 'Culture / Literature / Books / Banned books', 'Culture'),
  ('culture-literature-lists-books-best-selling-books', 'culture-literature-books-best-selling', 'Culture / Literature / Books / Best-selling', 'Culture'),
  ('culture-literature-lists-books-literary-awards', 'culture-literature-books-literary-awards', 'Culture / Literature / Books / Literary awards', 'Culture'),
  ('culture-literature-lists-electronic-literature-electronic-literature-authors-critics-and-works', 'culture-literature-electronic-literature-authors-critics-and-works', 'Culture / Literature / Electronic literature / Authors, critics, and works', 'Culture'),
  ('culture-literature-lists-fiction-comics', 'culture-literature-fiction-comics', 'Culture / Literature / Fiction / Comics', 'Culture'),
  ('culture-literature-lists-fiction-fairy-tales', 'culture-literature-fiction-fairy-tales', 'Culture / Literature / Fiction / Fairy tales', 'Culture'),
  ('culture-literature-lists-fiction-fictional-characters', 'culture-literature-fiction-fictional-characters', 'Culture / Literature / Fiction / Fictional characters', 'Culture'),
  ('culture-literature-lists-fiction-fictional-computers', 'culture-literature-fiction-fictional-computers', 'Culture / Literature / Fiction / Fictional computers', 'Culture'),
  ('culture-literature-lists-fiction-fictional-places', 'culture-literature-fiction-fictional-places', 'Culture / Literature / Fiction / Fictional places', 'Culture'),
  ('culture-literature-lists-fiction-fictional-robots-and-androids', 'culture-literature-fiction-fictional-robots-and-androids', 'Culture / Literature / Fiction / Fictional robots and androids', 'Culture'),
  ('culture-literature-lists-fiction-major-themes', 'culture-literature-fiction-major-themes', 'Culture / Literature / Fiction / Major themes', 'Culture'),
  ('society-lists-fictional-psychiatrists', 'culture-literature-fictional-characters-fictional-psychiatrists', 'Culture / Literature / Fictional characters / Fictional psychiatrists', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-actors', 'culture-mass-media-film-and-cinema-actors', 'Culture / Mass media / Film and cinema / Actors', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-film-awards', 'culture-mass-media-film-and-cinema-awards', 'Culture / Mass media / Film and cinema / Awards', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-directors', 'culture-mass-media-film-and-cinema-directors', 'Culture / Mass media / Film and cinema / Directors', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-film-festivals', 'culture-mass-media-film-and-cinema-festivals', 'Culture / Mass media / Film and cinema / Festivals', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films', 'culture-mass-media-film-and-cinema-films', 'Culture / Mass media / Film and cinema / Films', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-film-institutes', 'culture-mass-media-film-and-cinema-institutes', 'Culture / Mass media / Film and cinema / Institutes', 'Culture'),
  ('culture-literature-lists-magazines', 'culture-mass-media-print-media-magazines', 'Culture / Mass media / Print media / Magazines', 'Culture'),
  ('culture-performing-arts-music-lists-concert-tours', 'culture-performing-arts-music-concert-tours', 'Culture / Performing arts / Music / Concert tours', 'Culture'),
  ('culture-performing-arts-music-lists-electronic-music-lists', 'culture-performing-arts-music-electronic-music', 'Culture / Performing arts / Music / Electronic music', 'Culture'),
  ('culture-performing-arts-music-lists-music-genres', 'culture-performing-arts-music-genres', 'Culture / Performing arts / Music / Genres', 'Culture'),
  ('history-lists-musical-events-historical', 'culture-performing-arts-music-historical-musical-events', 'Culture / Performing arts / Music / Historical musical events', 'Culture'),
  ('culture-performing-arts-music-lists-musical-events', 'culture-performing-arts-music-musical-events', 'Culture / Performing arts / Music / Musical events', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups', 'culture-performing-arts-music-musicians-and-groups', 'Culture / Performing arts / Music / Musicians and groups', 'Culture'),
  ('culture-performing-arts-music-lists-opera-houses', 'culture-performing-arts-music-opera-houses', 'Culture / Performing arts / Music / Opera houses', 'Culture'),
  ('culture-performing-arts-music-lists-record-labels', 'culture-performing-arts-music-record-labels', 'Culture / Performing arts / Music / Record labels', 'Culture'),
  ('culture-performing-arts-music-lists-schools-of-music', 'culture-performing-arts-music-schools-of-music', 'Culture / Performing arts / Music / Schools of music', 'Culture'),
  ('culture-performing-arts-music-lists-songs-and-compositions', 'culture-performing-arts-music-songs-and-compositions', 'Culture / Performing arts / Music / Songs and compositions', 'Culture'),
  ('culture-performing-arts-music-lists-video-game-music', 'culture-performing-arts-music-video-game-music', 'Culture / Performing arts / Music / Video game music', 'Culture'),
  ('self-lists-cyclist-race-deaths', 'culture-sports-cycling-notable-deaths', 'Culture / Sports / Cycling / Notable deaths', 'Culture'),
  ('culture-sports-lists-gay-athletes', 'culture-sports-notable-athletes-gay-athletes', 'Culture / Sports / Notable athletes / Gay athletes', 'Culture'),
  ('culture-sports-lists-sports-leagues-defunct-sports-leagues', 'culture-sports-sports-leagues-defunct', 'Culture / Sports / Sports leagues / Defunct', 'Culture'),
  ('health-lists-psychiatric-drugs-by-condition', 'health-substances-psychiatric-drugs-by-condition', 'Health / Substances / Psychiatric drugs / By condition', 'Health'),
  ('history-lists-roman-sites', 'history-ancient-civilizations-roman-sites', 'History / Ancient civilizations / Roman / Sites', 'History'),
  ('history-lists-fires', 'history-historical-events-disasters-fires', 'History / Historical events / Disasters / Fires', 'History'),
  ('history-lists-industrial-disasters', 'history-historical-events-disasters-industrial', 'History / Historical events / Disasters / Industrial', 'History'),
  ('history-lists-natural-disasters', 'history-historical-events-disasters-natural', 'History / Historical events / Disasters / Natural', 'History'),
  ('history-lists-nuclear-accidents', 'history-historical-events-disasters-nuclear-accidents', 'History / Historical events / Disasters / Nuclear accidents', 'History'),
  ('history-lists-power-outages', 'history-historical-events-disasters-power-outages', 'History / Historical events / Disasters / Power outages', 'History'),
  ('religion-lists-monasteries-dissolved-by-henry-viii', 'history-historical-events-english-reformation-monasteries-dissolved-by-henry-viii', 'History / Historical events / English Reformation / Monasteries dissolved by Henry VIII', 'History'),
  ('history-lists-cyclones-list', 'history-historical-events-natural-disasters-cyclones', 'History / Historical events / Natural disasters / Cyclones', 'History'),
  ('history-lists-earthquakes', 'history-historical-events-natural-disasters-earthquakes', 'History / Historical events / Natural disasters / Earthquakes', 'History'),
  ('history-lists-archaeological-sites', 'history-historical-sciences-archaeology-archaeological-sites', 'History / Historical sciences / Archaeology / Archaeological sites', 'History'),
  ('tech-lists-wwii-weapons', 'history-wars-world-war-ii-weapons', 'History / Wars / World War II / Weapons', 'History'),
  ('human-activities-lists-schools', 'human-activities-views-education-practice-schools', 'Human activities / Views / Education (practice) / Schools', 'Human activities'),
  ('society-lists-youth-rights-list', 'justice-legal-frameworks-civil-liberties-youth-rights', 'Justice / Legal Frameworks / Civil liberties / Youth rights', 'Justice'),
  ('justice-lists-government-oversight-bodies', 'justice-patterns-institutional-capture-government-oversight-bodies', 'Justice / Patterns / Institutional capture / Government oversight bodies', 'Justice'),
  ('math-lists-tensor-theory', 'math-branches-of-mathematics-pure-mathematics-tensor-theory', 'Math / Branches of mathematics / Pure mathematics / Tensor theory', 'Math'),
  ('religion-lists-cathedrals', 'religion-concepts-sacred-architecture-cathedrals', 'Religion / Concepts / Sacred architecture / Cathedrals', 'Religion'),
  ('religion-lists-christian-denominations-list', 'religion-major-religions-christianity-denominations', 'Religion / Major religions / Christianity / Denominations', 'Religion'),
  ('religion-lists-indigetes-roman-gods-and-goddesses-list', 'religion-mythologies-roman-mythology-indigetes', 'Religion / Mythologies / Roman mythology / Indigetes', 'Religion'),
  ('religion-lists-patriarchs-of-antioch', 'religion-religious-roles-patriarchs-antioch', 'Religion / Religious roles / Patriarchs / Antioch', 'Religion'),
  ('religion-lists-patriarchs-of-constantinople', 'religion-religious-roles-patriarchs-constantinople', 'Religion / Religious roles / Patriarchs / Constantinople', 'Religion'),
  ('religion-lists-biblical-names', 'religion-sacred-texts-bible-names', 'Religion / Sacred texts / Bible / Names', 'Religion'),
  ('religion-lists-bible-stories', 'religion-sacred-texts-bible-stories', 'Religion / Sacred texts / Bible / Stories', 'Religion'),
  ('religion-lists-biblical-nameless', 'religion-sacred-texts-bible-unnamed-figures', 'Religion / Sacred texts / Bible / Unnamed figures', 'Religion'),
  ('science-lists-astronomy-lists-asteroid-groups', 'science-astronomy-and-space-science-solar-system-asteroid-groups', 'Science / Astronomy and space science / Solar System / Asteroid groups', 'Science'),
  ('science-lists-astronomy-lists-meteor-showers-list', 'science-astronomy-and-space-science-solar-system-meteor-showers', 'Science / Astronomy and space science / Solar System / Meteor showers', 'Science'),
  ('science-lists-astronomy-lists-minor-planets-list', 'science-astronomy-and-space-science-solar-system-minor-planets', 'Science / Astronomy and space science / Solar System / Minor planets', 'Science'),
  ('science-lists-astronomy-lists-possible-dwarf-planets-list', 'science-astronomy-and-space-science-solar-system-possible-dwarf-planets', 'Science / Astronomy and space science / Solar System / Possible dwarf planets', 'Science'),
  ('science-lists-astronomy-lists-trans-neptunian-objects', 'science-astronomy-and-space-science-solar-system-trans-neptunian-objects', 'Science / Astronomy and space science / Solar System / Trans-Neptunian objects', 'Science'),
  ('tech-lists-landings-on-extraterrestrial-bodies', 'science-astronomy-and-space-science-space-exploration-landings-on-extraterrestrial-bodies', 'Science / Astronomy and space science / Space exploration / Landings on extraterrestrial bodies', 'Science'),
  ('tech-lists-solar-system-probes', 'science-astronomy-and-space-science-space-exploration-solar-system-probes', 'Science / Astronomy and space science / Space exploration / Solar System probes', 'Science'),
  ('history-lists-space-shuttle-missions', 'science-astronomy-and-space-science-space-exploration-space-shuttle-missions', 'Science / Astronomy and space science / Space exploration / Space Shuttle missions', 'Science'),
  ('science-lists-plants-lists-domesticated-plants', 'science-biology-botany-domesticated-plants', 'Science / Biology / Botany / Domesticated plants', 'Science'),
  ('science-lists-plants-lists-edible-seeds', 'science-biology-botany-edible-seeds', 'Science / Biology / Botany / Edible seeds', 'Science'),
  ('science-lists-plants-lists-famous-trees', 'science-biology-botany-famous-trees', 'Science / Biology / Botany / Famous trees', 'Science'),
  ('science-lists-plants-lists-fruits-list', 'science-biology-botany-fruits', 'Science / Biology / Botany / Fruits', 'Science'),
  ('science-lists-plants-lists-garden-plants', 'science-biology-botany-garden-plants', 'Science / Biology / Botany / Garden plants', 'Science'),
  ('science-lists-plants-lists-herbs-list', 'science-biology-botany-herbs', 'Science / Biology / Botany / Herbs', 'Science'),
  ('science-lists-plants-lists-sequoia-groves', 'science-biology-botany-sequoia-groves', 'Science / Biology / Botany / Sequoia groves', 'Science'),
  ('science-lists-plants-lists-vegetables-list', 'science-biology-botany-vegetables', 'Science / Biology / Botany / Vegetables', 'Science'),
  ('science-lists-species-and-specimens-world-s-25-most-endangered-primates', 'science-biology-conservation-worlds-25-most-endangered-primates', 'Science / Biology / Conservation / World''s 25 Most Endangered Primates', 'Science'),
  ('science-lists-species-and-specimens-organisms-by-population', 'science-biology-ecology-organisms-by-population', 'Science / Biology / Ecology / Organisms by population', 'Science'),
  ('science-lists-feeding-behaviours', 'science-biology-ethology-feeding-behaviours', 'Science / Biology / Ethology / Feeding behaviours', 'Science'),
  ('science-lists-gene-families', 'science-biology-genetics-gene-families', 'Science / Biology / Genetics / Gene families', 'Science'),
  ('science-lists-latin-and-greek-systematic-names', 'science-biology-taxonomy-latin-and-greek-systematic-names', 'Science / Biology / Taxonomy / Latin and Greek systematic names', 'Science'),
  ('science-lists-species-and-specimens-organisms-named-after-famous-people', 'science-biology-taxonomy-organisms-named-after-famous-people', 'Science / Biology / Taxonomy / Organisms named after famous people', 'Science'),
  ('science-lists-species-and-specimens-organisms-named-after-works-of-fiction', 'science-biology-taxonomy-organisms-named-after-works-of-fiction', 'Science / Biology / Taxonomy / Organisms named after works of fiction', 'Science'),
  ('science-lists-species-and-specimens-domesticated-animals', 'science-biology-zoology-domesticated-animals', 'Science / Biology / Zoology / Domesticated animals', 'Science'),
  ('science-lists-chemistry-lists-biomolecules', 'science-chemistry-biochemistry-biomolecules', 'Science / Chemistry / Biochemistry / Biomolecules', 'Science'),
  ('science-lists-chemistry-lists-standard-electrode-potentials', 'science-chemistry-electrochemistry-standard-electrode-potentials', 'Science / Chemistry / Electrochemistry / Standard electrode potentials', 'Science'),
  ('science-lists-chemistry-lists-elements-by-number', 'science-chemistry-elements-by-atomic-number', 'Science / Chemistry / Elements / By atomic number', 'Science'),
  ('science-lists-chemistry-lists-elements-by-symbol', 'science-chemistry-elements-by-symbol', 'Science / Chemistry / Elements / By symbol', 'Science'),
  ('science-lists-chemistry-lists-isotope-table', 'science-chemistry-elements-isotopes', 'Science / Chemistry / Elements / Isotopes', 'Science'),
  ('science-lists-chemistry-lists-functional-groups', 'science-chemistry-organic-chemistry-functional-groups', 'Science / Chemistry / Organic chemistry / Functional groups', 'Science'),
  ('science-lists-chemistry-lists-enthalpy-change-of-formation', 'science-chemistry-thermodynamics-enthalpy-change-of-formation', 'Science / Chemistry / Thermodynamics / Enthalpy change of formation', 'Science'),
  ('human-activities-lists-greenhouse-gas-emissions-top-contributors', 'science-earth-science-climate-science-greenhouse-gas-emissions-top-contributors', 'Science / Earth science / Climate science / Greenhouse gas emissions, top contributors', 'Science'),
  ('human-activities-lists-greenhouse-gases-ipcc-list', 'science-earth-science-climate-science-greenhouse-gases-ipcc-list', 'Science / Earth science / Climate science / Greenhouse gases (IPCC list)', 'Science'),
  ('science-lists-earth-sciences-lists-landforms-list', 'science-earth-science-geology-landforms', 'Science / Earth science / Geology / Landforms', 'Science'),
  ('science-lists-earth-sciences-lists-oil-fields', 'science-earth-science-geology-oil-fields', 'Science / Earth science / Geology / Oil fields', 'Science'),
  ('science-lists-earth-sciences-lists-tectonic-plates-list', 'science-earth-science-geology-tectonic-plates', 'Science / Earth science / Geology / Tectonic plates', 'Science'),
  ('science-lists-earth-sciences-lists-uranium-mines', 'science-earth-science-geology-uranium-mines', 'Science / Earth science / Geology / Uranium mines', 'Science'),
  ('science-lists-earth-sciences-lists-tropical-cyclone-names', 'science-earth-science-meteorology-tropical-cyclone-names', 'Science / Earth science / Meteorology / Tropical cyclone names', 'Science'),
  ('science-lists-physics-lists-resistivities', 'science-physics-electromagnetism-resistivities', 'Science / Physics / Electromagnetism / Resistivities', 'Science'),
  ('science-lists-physics-lists-artificial-radiation-belts', 'science-physics-nuclear-physics-artificial-radiation-belts', 'Science / Physics / Nuclear physics / Artificial radiation belts', 'Science'),
  ('science-lists-physics-lists-particles-list', 'science-physics-particle-physics-particles', 'Science / Physics / Particle physics / Particles', 'Science'),
  ('science-lists-physics-lists-colors-list', 'science-physics-physics-concepts-colors', 'Science / Physics / Physics concepts / Colors', 'Science'),
  ('science-lists-physics-lists-cycles-physics', 'science-physics-physics-concepts-cycles', 'Science / Physics / Physics concepts / Cycles', 'Science'),
  ('science-lists-physics-lists-noise-types', 'science-physics-physics-concepts-noise-types', 'Science / Physics / Physics concepts / Noise types', 'Science'),
  ('science-lists-physics-lists-quantum-field-theories', 'science-physics-quantum-field-theory-theories', 'Science / Physics / Quantum field theory / Theories', 'Science'),
  ('science-lists-physics-lists-relativistic-equations', 'science-physics-relativity-equations', 'Science / Physics / Relativity / Equations', 'Science'),
  ('history-lists-scientific-discoveries', 'science-scientific-method-and-meta-science-history-of-science-scientific-discoveries', 'Science / Scientific method and meta-science / History of science / Scientific discoveries', 'Science'),
  ('self-lists-wartime-cross-dressers', 'self-identity-dimensions-gender-wartime-cross-dressers', 'Self / Identity dimensions / Gender / Wartime cross-dressers', 'Self'),
  ('self-lists-families-by-tree', 'self-relationships-family-family-trees', 'Self / Relationships / Family / Family trees', 'Self'),
  ('society-lists-business-theorists', 'society-economy-and-business-business-administration-business-theorists', 'Society / Economy and business / Business administration / Business theorists', 'Society'),
  ('society-lists-employee-owned-companies', 'society-economy-and-business-companies-employee-owned', 'Society / Economy and business / Companies / Employee-owned', 'Society'),
  ('society-lists-feminist-economists', 'society-economy-and-business-economists-feminist-economists', 'Society / Economy and business / Economists / Feminist economists', 'Society'),
  ('society-lists-stock-exchanges', 'society-economy-and-business-finance-stock-exchanges', 'Society / Economy and business / Finance / Stock exchanges', 'Society'),
  ('society-lists-stock-market-indices', 'society-economy-and-business-finance-stock-market-indices', 'Society / Economy and business / Finance / Stock market indices', 'Society'),
  ('society-lists-traded-commodities', 'society-economy-and-business-finance-traded-commodities', 'Society / Economy and business / Finance / Traded commodities', 'Society'),
  ('society-lists-department-stores', 'society-economy-and-business-retail-department-stores', 'Society / Economy and business / Retail / Department stores', 'Society'),
  ('society-lists-store-brands', 'society-economy-and-business-retail-store-brands', 'Society / Economy and business / Retail / Store brands', 'Society'),
  ('society-lists-supermarkets', 'society-economy-and-business-retail-supermarkets', 'Society / Economy and business / Retail / Supermarkets', 'Society'),
  ('history-lists-foreign-policy-doctrines', 'society-government-foreign-policy-doctrines', 'Society / Government / Foreign policy / Doctrines', 'Society'),
  ('society-lists-national-anthems', 'society-government-national-symbols-anthems', 'Society / Government / National symbols / Anthems', 'Society'),
  ('society-lists-united-states-federal-agencies', 'society-government-united-states-federal-agencies', 'Society / Government / United States / Federal agencies', 'Society'),
  ('society-lists-united-states-mints', 'society-government-united-states-mints', 'Society / Government / United States / Mints', 'Society'),
  ('society-lists-consonants', 'society-linguistics-phonetics-consonants', 'Society / Linguistics / Phonetics / Consonants', 'Society'),
  ('society-lists-vowels-table', 'society-linguistics-phonetics-vowels', 'Society / Linguistics / Phonetics / Vowels', 'Society'),
  ('society-lists-generic-names-of-political-parties', 'society-politics-political-parties-generic-names', 'Society / Politics / Political parties / Generic names', 'Society'),
  ('society-lists-british-professional-bodies', 'society-social-institutions-professional-bodies-british', 'Society / Social institutions / Professional bodies / British', 'Society'),
  ('society-lists-trade-unions-list', 'society-social-movements-labor-trade-unions', 'Society / Social movements / Labor / Trade unions', 'Society'),
  ('society-lists-lgbt-related-organizations', 'society-social-movements-lgbt-organizations', 'Society / Social movements / LGBT / Organizations', 'Society'),
  ('society-lists-california-suffragists', 'society-social-movements-suffragists-california', 'Society / Social movements / Suffragists / California', 'Society'),
  ('society-lists-women-s-organizations', 'society-social-movements-women-organizations', 'Society / Social movements / Women / Organizations', 'Society'),
  ('society-lists-clinical-psychologists', 'society-social-sciences-psychology-clinical-psychologists', 'Society / Social sciences / Psychology / Clinical psychologists', 'Society'),
  ('society-lists-credentials-in-psychology', 'society-social-sciences-psychology-credentials', 'Society / Social sciences / Psychology / Credentials', 'Society'),
  ('society-lists-psychology-disciplines', 'society-social-sciences-psychology-disciplines', 'Society / Social sciences / Psychology / Disciplines', 'Society'),
  ('society-lists-emotions-list', 'society-social-sciences-psychology-emotions', 'Society / Social sciences / Psychology / Emotions', 'Society'),
  ('society-lists-memory-biases-list', 'society-social-sciences-psychology-memory-biases', 'Society / Social sciences / Psychology / Memory biases', 'Society'),
  ('society-lists-psychologists', 'society-social-sciences-psychology-psychologists', 'Society / Social sciences / Psychology / Psychologists', 'Society'),
  ('society-lists-psychological-schools', 'society-social-sciences-psychology-schools-of-thought', 'Society / Social sciences / Psychology / Schools of thought', 'Society'),
  ('society-lists-scientific-journals-in-psychology', 'society-social-sciences-psychology-scientific-journals', 'Society / Social sciences / Psychology / Scientific journals', 'Society'),
  ('society-lists-social-psychologists', 'society-social-sciences-psychology-social-psychologists', 'Society / Social sciences / Psychology / Social psychologists', 'Society'),
  ('society-lists-sociologists', 'society-social-sciences-sociology-sociologists', 'Society / Social sciences / Sociology / Sociologists', 'Society'),
  ('society-lists-subfields-of-sociology-list', 'society-social-sciences-sociology-subfields', 'Society / Social sciences / Sociology / Subfields', 'Society'),
  ('tech-lists-ascii', 'tech-computing-character-encoding-ascii', 'Tech / Computing / Character encoding / ASCII', 'Tech'),
  ('tech-lists-unicode', 'tech-computing-character-encoding-unicode', 'Tech / Computing / Character encoding / Unicode', 'Tech'),
  ('tech-lists-utf-8', 'tech-computing-character-encoding-utf-8', 'Tech / Computing / Character encoding / UTF-8', 'Tech'),
  ('tech-lists-xml-and-html-characters', 'tech-computing-character-encoding-xml-and-html-character-entities', 'Tech / Computing / Character encoding / XML and HTML character entities', 'Tech'),
  ('tech-lists-graphics-file-formats', 'tech-computing-file-formats-graphics', 'Tech / Computing / File formats / Graphics', 'Tech'),
  ('tech-lists-software-bugs-list', 'tech-computing-software-notable-software-bugs', 'Tech / Computing / Software / Notable software bugs', 'Tech'),
  ('tech-lists-open-source-software-packages', 'tech-computing-software-open-source', 'Tech / Computing / Software / Open source', 'Tech'),
  ('tech-lists-operating-systems-list', 'tech-computing-software-operating-systems', 'Tech / Computing / Software / Operating systems', 'Tech'),
  ('tech-lists-canals-list', 'tech-construction-and-built-environment-civil-engineering-canals', 'Tech / Construction and built environment / Civil engineering / Canals', 'Tech'),
  ('tech-lists-civil-engineering-landmarks', 'tech-construction-and-built-environment-civil-engineering-landmarks', 'Tech / Construction and built environment / Civil engineering / Landmarks', 'Tech'),
  ('tech-lists-reservoirs-and-dams-list', 'tech-construction-and-built-environment-civil-engineering-reservoirs-and-dams', 'Tech / Construction and built environment / Civil engineering / Reservoirs and dams', 'Tech'),
  ('tech-lists-world-heritage-sites', 'tech-construction-and-built-environment-heritage-registers-unesco-world-heritage-sites', 'Tech / Construction and built environment / Heritage registers / UNESCO World Heritage Sites', 'Tech'),
  ('tech-lists-tcp-and-udp-port-numbers', 'tech-internet-and-web-protocols-tcp-and-udp-port-numbers', 'Tech / Internet and Web / Protocols / TCP and UDP port numbers', 'Tech'),
  ('tech-lists-aircraft-manufacturers', 'tech-transport-technology-aircraft-manufacturers', 'Tech / Transport technology / Aircraft / Manufacturers', 'Tech'),
  ('tech-lists-lighthouses', 'tech-transport-technology-maritime-lighthouses', 'Tech / Transport technology / Maritime / Lighthouses', 'Tech'),
  ('tech-lists-famous-trains', 'tech-transport-technology-rail-transport-famous-trains', 'Tech / Transport technology / Rail transport / Famous trains', 'Tech'),
  ('culture-games-board-games-chess-lists-chess-books', 'culture-games-board-games-chess-books', 'Culture / Games / Board games / Chess / Books', 'Culture'),
  ('culture-games-board-games-chess-lists-fairy-pieces', 'culture-games-board-games-chess-fairy-pieces', 'Culture / Games / Board games / Chess / Fairy pieces', 'Culture'),
  ('culture-games-board-games-chess-lists-chess-games', 'culture-games-board-games-chess-notable-games', 'Culture / Games / Board games / Chess / Notable games', 'Culture'),
  ('culture-games-board-games-chess-lists-chess-openings', 'culture-games-board-games-chess-openings', 'Culture / Games / Board games / Chess / Openings', 'Culture'),
  ('culture-games-board-games-chess-lists-chess-players', 'culture-games-board-games-chess-players', 'Culture / Games / Board games / Chess / Players', 'Culture'),
  ('culture-games-board-games-chess-lists-chess-terms', 'culture-games-board-games-chess-terms', 'Culture / Games / Board games / Chess / Terms', 'Culture'),
  ('culture-games-board-games-chess-lists-chess-tournaments', 'culture-games-board-games-chess-tournaments', 'Culture / Games / Board games / Chess / Tournaments', 'Culture'),
  ('culture-games-board-games-chess-lists-world-championship-matches', 'culture-games-board-games-chess-world-championship-matches', 'Culture / Games / Board games / Chess / World Championship matches', 'Culture'),
  ('culture-games-board-games-chess-lists-chess-world-records', 'culture-games-board-games-chess-world-records', 'Culture / Games / Board games / Chess / World records', 'Culture'),
  ('culture-literature-lists-fiction-comics-comic-books', 'culture-literature-fiction-comics-comic-books', 'Culture / Literature / Fiction / Comics / Comic books', 'Culture'),
  ('culture-literature-lists-fiction-comics-comic-strips', 'culture-literature-fiction-comics-comic-strips', 'Culture / Literature / Fiction / Comics / Comic strips', 'Culture'),
  ('culture-literature-lists-fiction-comics-manga', 'culture-literature-fiction-comics-manga', 'Culture / Literature / Fiction / Comics / Manga', 'Culture'),
  ('culture-literature-lists-fiction-fictional-places-fictional-countries', 'culture-literature-fiction-fictional-places-countries', 'Culture / Literature / Fiction / Fictional places / Countries', 'Culture'),
  ('culture-literature-lists-fiction-fictional-places-imaginary-universes', 'culture-literature-fiction-fictional-places-imaginary-universes', 'Culture / Literature / Fiction / Fictional places / Imaginary universes', 'Culture'),
  ('culture-literature-lists-fiction-fictional-places-fictional-planets', 'culture-literature-fiction-fictional-places-planets', 'Culture / Literature / Fiction / Fictional places / Planets', 'Culture'),
  ('culture-literature-lists-fiction-major-themes-science-fiction', 'culture-literature-fiction-genres-science-fiction', 'Culture / Literature / Fiction / Genres / Science fiction', 'Culture'),
  ('culture-literature-lists-fiction-major-themes-adultery', 'culture-literature-fiction-major-themes-adultery', 'Culture / Literature / Fiction / Major themes / Adultery', 'Culture'),
  ('culture-literature-lists-fiction-major-themes-family', 'culture-literature-fiction-major-themes-family', 'Culture / Literature / Fiction / Major themes / Family', 'Culture'),
  ('culture-literature-lists-fiction-major-themes-sadomasochism', 'culture-literature-fiction-major-themes-sadomasochism', 'Culture / Literature / Fiction / Major themes / Sadomasochism', 'Culture'),
  ('culture-literature-lists-fiction-major-themes-travel', 'culture-literature-fiction-major-themes-travel', 'Culture / Literature / Fiction / Major themes / Travel', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-channels', 'culture-mass-media-broadcast-media-television-channels', 'Culture / Mass media / Broadcast media / Television / Channels', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-networks', 'culture-mass-media-broadcast-media-television-networks', 'Culture / Mass media / Broadcast media / Television / Networks', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs', 'culture-mass-media-broadcast-media-television-programs', 'Culture / Mass media / Broadcast media / Television / Programs', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-computer-animated-films', 'culture-mass-media-film-and-cinema-films-computer-animated', 'Culture / Mass media / Film and cinema / Films / Computer-animated', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-film-series', 'culture-mass-media-film-and-cinema-films-film-series', 'Culture / Mass media / Film and cinema / Films / Film series', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-greatest', 'culture-mass-media-film-and-cinema-films-greatest', 'Culture / Mass media / Film and cinema / Films / Greatest', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-highest-grossing', 'culture-mass-media-film-and-cinema-films-highest-grossing', 'Culture / Mass media / Film and cinema / Films / Highest-grossing', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-most-expensive', 'culture-mass-media-film-and-cinema-films-most-expensive', 'Culture / Mass media / Film and cinema / Films / Most expensive', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-preserved-films', 'culture-mass-media-film-and-cinema-films-preserved-films', 'Culture / Mass media / Film and cinema / Films / Preserved films', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-rated-nc-17', 'culture-mass-media-film-and-cinema-films-rated-nc-17', 'Culture / Mass media / Film and cinema / Films / Rated NC-17', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-trilogies', 'culture-mass-media-film-and-cinema-films-trilogies', 'Culture / Mass media / Film and cinema / Films / Trilogies', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-worst', 'culture-mass-media-film-and-cinema-films-worst', 'Culture / Mass media / Film and cinema / Films / Worst', 'Culture'),
  ('religion-lists-dramatic-portrayals-of-jesus-christ', 'culture-mass-media-film-and-cinema-religious-portrayals-jesus-christ', 'Culture / Mass media / Film and cinema / Religious portrayals / Jesus Christ', 'Culture'),
  ('culture-literature-lists-magazines-anomalous-phenomena-magazines', 'culture-mass-media-print-media-magazines-anomalous-phenomena', 'Culture / Mass media / Print media / Magazines / Anomalous phenomena', 'Culture'),
  ('culture-literature-lists-magazines-men-s-magazines', 'culture-mass-media-print-media-magazines-mens-magazines', 'Culture / Mass media / Print media / Magazines / Men''s magazines', 'Culture'),
  ('culture-literature-lists-magazines-teen-magazines', 'culture-mass-media-print-media-magazines-teen-magazines', 'Culture / Mass media / Print media / Magazines / Teen magazines', 'Culture'),
  ('culture-literature-lists-magazines-women-s-magazines', 'culture-mass-media-print-media-magazines-womens-magazines', 'Culture / Mass media / Print media / Magazines / Women''s magazines', 'Culture'),
  ('culture-performing-arts-music-lists-electronic-music-lists-record-labels', 'culture-performing-arts-music-electronic-music-record-labels', 'Culture / Performing arts / Music / Electronic music / Record labels', 'Culture'),
  ('culture-performing-arts-music-lists-electronic-music-lists-music-genres', 'culture-performing-arts-music-electronic-music-sub-genres', 'Culture / Performing arts / Music / Electronic music / Sub-genres', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-bands', 'culture-performing-arts-music-musicians-and-groups-bands', 'Culture / Performing arts / Music / Musicians and groups / Bands', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-composers', 'culture-performing-arts-music-musicians-and-groups-composers', 'Culture / Performing arts / Music / Musicians and groups / Composers', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians', 'culture-performing-arts-music-musicians-and-groups-musicians', 'Culture / Performing arts / Music / Musicians and groups / Musicians', 'Culture'),
  ('culture-performing-arts-music-lists-songs-and-compositions-albums', 'culture-performing-arts-music-songs-and-compositions-albums', 'Culture / Performing arts / Music / Songs and compositions / Albums', 'Culture'),
  ('culture-performing-arts-music-lists-songs-and-compositions-christmas-carols', 'culture-performing-arts-music-songs-and-compositions-christmas-carols', 'Culture / Performing arts / Music / Songs and compositions / Christmas carols', 'Culture'),
  ('culture-performing-arts-music-lists-songs-and-compositions-christmas-number-one-singles-uk', 'culture-performing-arts-music-songs-and-compositions-christmas-number-one-singles-uk', 'Culture / Performing arts / Music / Songs and compositions / Christmas number-one singles (UK)', 'Culture'),
  ('culture-performing-arts-music-lists-songs-and-compositions-famous-operas', 'culture-performing-arts-music-songs-and-compositions-famous-operas', 'Culture / Performing arts / Music / Songs and compositions / Famous operas', 'Culture'),
  ('culture-performing-arts-music-lists-songs-and-compositions-operettas', 'culture-performing-arts-music-songs-and-compositions-operettas', 'Culture / Performing arts / Music / Songs and compositions / Operettas', 'Culture'),
  ('culture-performing-arts-music-lists-video-game-music-video-game-musicians', 'culture-performing-arts-music-video-game-music-composers', 'Culture / Performing arts / Music / Video game music / Composers', 'Culture'),
  ('culture-sports-ball-games-association-football-lists-100-greatest-living-football-players', 'culture-sports-ball-games-association-football-100-greatest-living-football-players', 'Culture / Sports / Ball games / Association football / 100 Greatest Living Football Players', 'Culture'),
  ('self-lists-association-footballer-playing-deaths', 'culture-sports-ball-games-association-football-notable-deaths', 'Culture / Sports / Ball games / Association football / Notable deaths', 'Culture'),
  ('culture-sports-ball-games-association-football-lists-football-teams', 'culture-sports-ball-games-association-football-teams', 'Culture / Sports / Ball games / Association football / Teams', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-highest-paid-baseball-players', 'culture-sports-ball-games-baseball-highest-paid-players', 'Culture / Sports / Ball games / Baseball / Highest-paid players', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-lifetime-home-run-leaders', 'culture-sports-ball-games-baseball-lifetime-home-run-leaders', 'Culture / Sports / Ball games / Baseball / Lifetime home run leaders', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-major-league-baseball-players', 'culture-sports-ball-games-baseball-major-league-players', 'Culture / Sports / Ball games / Baseball / Major League players', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-triple-crown', 'culture-sports-ball-games-baseball-triple-crown', 'Culture / Sports / Ball games / Baseball / Triple Crown', 'Culture'),
  ('culture-sports-combat-sports-martial-arts-lists-martial-arts-weapons', 'culture-sports-combat-sports-martial-arts-weapons', 'Culture / Sports / Combat sports / Martial arts / Weapons', 'Culture'),
  ('culture-sports-lists-ski-areas', 'culture-sports-winter-sports-skiing-ski-areas', 'Culture / Sports / Winter sports / Skiing / Ski areas', 'Culture'),
  ('history-lists-roman-governorships-of-britain', 'history-ancient-civilizations-roman-britain-governorships', 'History / Ancient civilizations / Roman / Britain / Governorships', 'History'),
  ('science-lists-astronomy-lists-comets-by-type', 'science-astronomy-and-space-science-solar-system-comets-by-type', 'Science / Astronomy and space science / Solar System / Comets / By type', 'Science'),
  ('science-lists-diseases-lists-botanical-banana-and-plantain-diseases', 'science-biology-botany-plant-pathology-banana-and-plantain-diseases', 'Science / Biology / Botany / Plant pathology / Banana and plantain diseases', 'Science'),
  ('science-lists-diseases-lists-botanical-sweet-potato-diseases', 'science-biology-botany-plant-pathology-sweet-potato-diseases', 'Science / Biology / Botany / Plant pathology / Sweet potato diseases', 'Science'),
  ('science-lists-plants-lists-acer-species-maples', 'science-biology-botany-species-acer-maples', 'Science / Biology / Botany / Species / Acer (maples)', 'Science'),
  ('science-lists-plants-lists-palm-tree-genera', 'science-biology-botany-species-palm-tree-genera', 'Science / Biology / Botany / Species / Palm tree genera', 'Science'),
  ('science-lists-muscles', 'science-biology-branches-of-biology-anatomy-muscles', 'Science / Biology / Branches of biology / Anatomy / Muscles', 'Science'),
  ('science-lists-species-and-specimens-birds-by-region', 'science-biology-zoology-birds-by-region', 'Science / Biology / Zoology / Birds / By region', 'Science'),
  ('science-lists-species-and-specimens-mammals-by-region', 'science-biology-zoology-mammals-by-region', 'Science / Biology / Zoology / Mammals / By region', 'Science'),
  ('science-lists-species-and-specimens-dinosaur-species', 'science-biology-zoology-paleontology-dinosaur-species', 'Science / Biology / Zoology / Paleontology / Dinosaur species', 'Science'),
  ('science-lists-chemistry-lists-stable-isotopes', 'science-chemistry-elements-isotopes-stable', 'Science / Chemistry / Elements / Isotopes / Stable', 'Science'),
  ('science-lists-physics-lists-equations-in-classical-mechanics', 'science-physics-branches-of-physics-classical-mechanics-equations', 'Science / Physics / Branches of physics / Classical mechanics / Equations', 'Science'),
  ('society-lists-european-sovereign-debt-crisis-acronyms', 'society-economy-and-business-finance-european-sovereign-debt-crisis-acronyms', 'Society / Economy and business / Finance / European sovereign-debt crisis / Acronyms', 'Society'),
  ('history-lists-un-peacekeeping-missions', 'society-government-international-organizations-categories-un-peacekeeping-missions', 'Society / Government / International organizations (categories) / UN / Peacekeeping missions', 'Society'),
  ('society-lists-united-nations-member-states', 'society-government-international-organizations-un-member-states', 'Society / Government / International organizations / UN / Member states', 'Society'),
  ('society-lists-current-members-of-the-united-states-congress', 'society-government-united-states-congress-current-members', 'Society / Government / United States / Congress / Current members', 'Society'),
  ('society-lists-english-words-list', 'society-linguistics-languages-english-words', 'Society / Linguistics / Languages / English / Words', 'Society'),
  ('tech-lists-amd-microprocessors', 'tech-computing-hardware-microprocessors-amd', 'Tech / Computing / Hardware / Microprocessors / AMD', 'Tech'),
  ('tech-lists-intel-microprocessors', 'tech-computing-hardware-microprocessors-intel', 'Tech / Computing / Hardware / Microprocessors / Intel', 'Tech'),
  ('tech-lists-screen-readers', 'tech-computing-software-accessibility-screen-readers', 'Tech / Computing / Software / Accessibility / Screen readers', 'Tech'),
  ('tech-lists-test-automation', 'tech-computing-software-software-engineering-test-automation', 'Tech / Computing / Software / Software engineering / Test automation', 'Tech'),
  ('tech-lists-html-editors', 'tech-computing-software-web-development-html-editors', 'Tech / Computing / Software / Web development / HTML editors', 'Tech'),
  ('tech-lists-largest-bridges', 'tech-construction-and-built-environment-civil-engineering-bridges-largest', 'Tech / Construction and built environment / Civil engineering / Bridges / Largest', 'Tech'),
  ('tech-lists-longest-tunnels', 'tech-construction-and-built-environment-civil-engineering-tunnels-longest', 'Tech / Construction and built environment / Civil engineering / Tunnels / Longest', 'Tech'),
  ('tech-lists-http-status-codes', 'tech-internet-and-web-protocols-http-status-codes', 'Tech / Internet and Web / Protocols / HTTP / Status codes', 'Tech'),
  ('tech-lists-busiest-airports', 'tech-transport-technology-aircraft-airports-busiest-airports', 'Tech / Transport technology / Aircraft / Airports / Busiest airports', 'Tech'),
  ('tech-lists-automobile-manufacturers', 'tech-transport-technology-land-transport-road-transport-automobile-manufacturers', 'Tech / Transport technology / Land transport / Road transport / Automobile manufacturers', 'Tech'),
  ('culture-literature-lists-fiction-comics-comic-books-dc-comics', 'culture-literature-fiction-comics-comic-books-dc-comics', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics', 'Culture'),
  ('culture-literature-lists-fiction-comics-comic-books-marvel-comics', 'culture-literature-fiction-comics-comic-books-marvel-comics', 'Culture / Literature / Fiction / Comics / Comic books / Marvel Comics', 'Culture'),
  ('culture-literature-lists-fiction-comics-best-selling-manga', 'culture-literature-fiction-comics-manga-best-selling', 'Culture / Literature / Fiction / Comics / Manga / Best-selling', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-animated-series', 'culture-mass-media-broadcast-media-television-programs-animated-series', 'Culture / Mass media / Broadcast media / Television / Programs / Animated series', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-anime-lists', 'culture-mass-media-broadcast-media-television-programs-anime', 'Culture / Mass media / Broadcast media / Television / Programs / Anime', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-bl-dramas', 'culture-mass-media-broadcast-media-television-programs-bl-dramas', 'Culture / Mass media / Broadcast media / Television / Programs / BL dramas', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-british-tv-shows-remade-for-the-american-market', 'culture-mass-media-broadcast-media-television-programs-british-shows-remade-for-american-market', 'Culture / Mass media / Broadcast media / Television / Programs / British shows remade for American market', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-children-s-television-series', 'culture-mass-media-broadcast-media-television-programs-childrens-series', 'Culture / Mass media / Broadcast media / Television / Programs / Children''s series', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-comedies', 'culture-mass-media-broadcast-media-television-programs-comedies', 'Culture / Mass media / Broadcast media / Television / Programs / Comedies', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-cult-television-shows', 'culture-mass-media-broadcast-media-television-programs-cult-shows', 'Culture / Mass media / Broadcast media / Television / Programs / Cult shows', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-dramedies', 'culture-mass-media-broadcast-media-television-programs-dramedies', 'Culture / Mass media / Broadcast media / Television / Programs / Dramedies', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-most-watched-television-episodes', 'culture-mass-media-broadcast-media-television-programs-most-watched-episodes', 'Culture / Mass media / Broadcast media / Television / Programs / Most-watched episodes', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-sci-fi-tv-programs', 'culture-mass-media-broadcast-media-television-programs-sci-fi', 'Culture / Mass media / Broadcast media / Television / Programs / Sci-fi', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-soap-operas', 'culture-mass-media-broadcast-media-television-programs-soap-operas', 'Culture / Mass media / Broadcast media / Television / Programs / Soap operas', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-spin-off-shows', 'culture-mass-media-broadcast-media-television-programs-spin-off-shows', 'Culture / Mass media / Broadcast media / Television / Programs / Spin-off shows', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs-uk-television-series', 'culture-mass-media-broadcast-media-television-programs-uk-series', 'Culture / Mass media / Broadcast media / Television / Programs / UK series', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-tv-stations-in-north-america', 'culture-mass-media-broadcast-media-television-stations-north-america', 'Culture / Mass media / Broadcast media / Television / Stations / North America', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-bands-hardcore-punk-bands', 'culture-performing-arts-music-musicians-and-groups-bands-hardcore-punk', 'Culture / Performing arts / Music / Musicians and groups / Bands / Hardcore punk', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-composers-classical-music-composers', 'culture-performing-arts-music-musicians-and-groups-composers-classical', 'Culture / Performing arts / Music / Musicians and groups / Composers / Classical', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-composers-songwriters-hall-of-fame', 'culture-performing-arts-music-musicians-and-groups-composers-songwriters-hall-of-fame', 'Culture / Performing arts / Music / Musicians and groups / Composers / Songwriters Hall of Fame', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-alternative-music-artists', 'culture-performing-arts-music-musicians-and-groups-musicians-alternative', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Alternative', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-ambient-artists', 'culture-performing-arts-music-musicians-and-groups-musicians-ambient', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Ambient', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-best-selling-music-artists', 'culture-performing-arts-music-musicians-and-groups-musicians-best-selling', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Best-selling', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-disco-artists', 'culture-performing-arts-music-musicians-and-groups-musicians-disco', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Disco', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-grammy-hall-of-fame-award-recipients', 'culture-performing-arts-music-musicians-and-groups-musicians-grammy-hall-of-fame-recipients', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Grammy Hall of Fame recipients', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-hip-hop-artists', 'culture-performing-arts-music-musicians-and-groups-musicians-hip-hop', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Hip hop', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-r-b-musicians', 'culture-performing-arts-music-musicians-and-groups-musicians-r-and-b', 'Culture / Performing arts / Music / Musicians and groups / Musicians / R&B', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups-musicians-soul-musicians', 'culture-performing-arts-music-musicians-and-groups-musicians-soul', 'Culture / Performing arts / Music / Musicians and groups / Musicians / Soul', 'Culture'),
  ('culture-performing-arts-music-lists-songs-and-compositions-compositions-of-johann-sebastian-bach', 'culture-performing-arts-music-songs-and-compositions-by-composer-j-s-bach', 'Culture / Performing arts / Music / Songs and compositions / By composer / J.S. Bach', 'Culture'),
  ('culture-sports-ball-games-association-football-lists-football-clubs-in-france', 'culture-sports-ball-games-association-football-clubs-france', 'Culture / Sports / Ball games / Association football / Clubs / France', 'Culture'),
  ('culture-sports-ball-games-association-football-lists-women-s-association-football-clubs', 'culture-sports-ball-games-association-football-clubs-womens', 'Culture / Sports / Ball games / Association football / Clubs / Women''s', 'Culture'),
  ('culture-sports-ball-games-association-football-lists-national-association-football-teams-by-nickname', 'culture-sports-ball-games-association-football-national-teams-by-nickname', 'Culture / Sports / Ball games / Association football / National teams / By nickname', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners', 'Culture'),
  ('culture-sports-lists-judo-techniques', 'culture-sports-combat-sports-martial-arts-judo-techniques', 'Culture / Sports / Combat sports / Martial arts / Judo / Techniques', 'Culture'),
  ('science-lists-fish-lists-fishes-of-the-coral-sea', 'science-biology-zoology-fish-by-region-coral-sea', 'Science / Biology / Zoology / Fish / By region / Coral Sea', 'Science'),
  ('science-lists-fish-lists-fishes-of-great-britain', 'science-biology-zoology-fish-by-region-great-britain', 'Science / Biology / Zoology / Fish / By region / Great Britain', 'Science'),
  ('science-lists-fish-lists-fish-of-ireland', 'science-biology-zoology-fish-by-region-ireland', 'Science / Biology / Zoology / Fish / By region / Ireland', 'Science'),
  ('science-lists-fish-lists-fish-of-montana', 'science-biology-zoology-fish-by-region-montana', 'Science / Biology / Zoology / Fish / By region / Montana', 'Science'),
  ('science-lists-fish-lists-fish-in-sweden', 'science-biology-zoology-fish-by-region-sweden', 'Science / Biology / Zoology / Fish / By region / Sweden', 'Science'),
  ('science-lists-fish-lists-fishes-of-west-virginia', 'science-biology-zoology-fish-by-region-west-virginia', 'Science / Biology / Zoology / Fish / By region / West Virginia', 'Science'),
  ('science-lists-insects-lists-insects-of-britain', 'science-biology-zoology-insects-by-region-britain', 'Science / Biology / Zoology / Insects / By region / Britain', 'Science'),
  ('culture-literature-lists-fiction-comics-comic-books-dc-comics-dc-characters', 'culture-literature-fiction-comics-comic-books-dc-comics-characters', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Characters', 'Culture'),
  ('culture-literature-lists-fiction-comics-comic-books-dc-comics-elseworlds', 'culture-literature-fiction-comics-comic-books-dc-comics-elseworlds', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Elseworlds', 'Culture'),
  ('culture-literature-lists-fiction-comics-comic-books-dc-comics-dc-universe-locations', 'culture-literature-fiction-comics-comic-books-dc-comics-universe-locations', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Universe locations', 'Culture'),
  ('culture-literature-lists-fiction-comics-comic-books-marvel-comics-avengers', 'culture-literature-fiction-comics-comic-books-marvel-comics-avengers', 'Culture / Literature / Fiction / Comics / Comic books / Marvel Comics / Avengers', 'Culture'),
  ('culture-literature-lists-fiction-comics-comic-books-marvel-comics-marvel-characters', 'culture-literature-fiction-comics-comic-books-marvel-comics-characters', 'Culture / Literature / Fiction / Comics / Comic books / Marvel Comics / Characters', 'Culture'),
  ('culture-literature-lists-fiction-comics-comic-books-marvel-comics-x-men', 'culture-literature-fiction-comics-comic-books-marvel-comics-x-men', 'Culture / Literature / Fiction / Comics / Comic books / Marvel Comics / X-Men', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-1st-base', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-1st-base', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / 1st Base', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-2nd-base', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-2nd-base', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / 2nd Base', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-3rd-base', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-3rd-base', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / 3rd Base', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-catcher', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-catcher', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / Catcher', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-outfield', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-outfield', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / Outfield', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-pitcher', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-pitcher', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / Pitcher', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-al-gold-glove-winners-shortstop', 'culture-sports-ball-games-baseball-awards-al-gold-glove-winners-shortstop', 'Culture / Sports / Ball games / Baseball / Awards / AL Gold Glove Winners / Shortstop', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-1st-base', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-1st-base', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / 1st Base', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-2nd-base', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-2nd-base', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / 2nd Base', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-3rd-base', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-3rd-base', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / 3rd Base', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-catcher', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-catcher', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / Catcher', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-outfield', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-outfield', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / Outfield', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-pitcher', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-pitcher', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / Pitcher', 'Culture'),
  ('culture-sports-ball-games-baseball-lists-nl-gold-glove-winners-shortstop', 'culture-sports-ball-games-baseball-awards-nl-gold-glove-winners-shortstop', 'Culture / Sports / Ball games / Baseball / Awards / NL Gold Glove Winners / Shortstop', 'Culture'),
  ('culture-literature-lists-fiction-comics-comic-books-dc-comics-justice-league-members', 'culture-literature-fiction-comics-comic-books-dc-comics-justice-league-members', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Justice League / Members', 'Culture'),
  ('culture-literature-lists-fiction-comics-comic-books-dc-comics-legion-of-super-heroes-members', 'culture-literature-fiction-comics-comic-books-dc-comics-legion-of-super-heroes-members', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Legion of Super-Heroes / Members', 'Culture'),
  ('culture-literature-lists-fiction-comics-comic-books-dc-comics-superman-enemies', 'culture-literature-fiction-comics-comic-books-dc-comics-superman-enemies', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Superman / Enemies', 'Culture')
)
UPDATE atoms a SET
  id = m.new_id,
  name = (string_to_array(m.new_path, ' / '))[array_length(string_to_array(m.new_path, ' / '), 1)],
  path = m.new_path,
  path_parts = string_to_array(m.new_path, ' / '),
  depth = array_length(string_to_array(m.new_path, ' / '), 1),
  realm_name = m.new_realm_name,
  realm_id = lower(replace(replace(m.new_realm_name, ' ', '-'), '''', '')),
  updated_at = now()
FROM moves m
WHERE a.id = m.old_id;

INSERT INTO atoms (id, name, path, path_parts, realm_id, realm_name, depth, type, kettle, is_leaf, theme_tags, realm_tags, pillar_tags, skin_tags, meta, created_at, updated_at) VALUES
  ('culture-literature-fiction-comics-comic-books-dc-comics-justice-league', 'Justice League', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Justice League', ARRAY['Culture','Literature','Fiction','Comics','Comic books','DC Comics','Justice League']::text[], 'culture', 'Culture', 7, 'event', 'Accepted', false, ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], '{}'::jsonb, now(), now()),
  ('culture-literature-fiction-comics-comic-books-dc-comics-legion-of-super-heroes', 'Legion of Super-Heroes', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Legion of Super-Heroes', ARRAY['Culture','Literature','Fiction','Comics','Comic books','DC Comics','Legion of Super-Heroes']::text[], 'culture', 'Culture', 7, 'event', 'Accepted', false, ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], '{}'::jsonb, now(), now()),
  ('culture-literature-fiction-comics-comic-books-dc-comics-superman', 'Superman', 'Culture / Literature / Fiction / Comics / Comic books / DC Comics / Superman', ARRAY['Culture','Literature','Fiction','Comics','Comic books','DC Comics','Superman']::text[], 'culture', 'Culture', 7, 'event', 'Accepted', false, ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], '{}'::jsonb, now(), now()),
  ('culture-performing-arts-music-songs-and-compositions-by-composer', 'By composer', 'Culture / Performing arts / Music / Songs and compositions / By composer', ARRAY['Culture','Performing arts','Music','Songs and compositions','By composer']::text[], 'culture', 'Culture', 5, 'event', 'Accepted', false, ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], ARRAY[]::text[], '{}'::jsonb, now(), now())
ON CONFLICT (id) DO NOTHING;

-- Recompute is_leaf for all atoms based on final state
UPDATE atoms a SET is_leaf = NOT EXISTS (
  SELECT 1 FROM atoms c WHERE c.depth > a.depth AND c.path_parts[1:a.depth] = a.path_parts
);

DO $$
DECLARE
  new_total int; expected int := 4978 + 4;
  leaf_with_children int; depth_mismatch int; skipped_level int; dup_id int;
BEGIN
  SELECT count(*) INTO new_total FROM atoms;
  IF new_total <> expected THEN RAISE EXCEPTION 'BATCH-COMBINED FAIL: expected % atoms, found %', expected, new_total; END IF;
  SELECT count(*) INTO leaf_with_children FROM atoms p WHERE p.is_leaf=true AND EXISTS (SELECT 1 FROM atoms c WHERE c.depth>p.depth AND c.path_parts[1:p.depth]=p.path_parts);
  IF leaf_with_children <> 0 THEN RAISE EXCEPTION 'BATCH-COMBINED FAIL: leaf-with-children=%', leaf_with_children; END IF;
  SELECT count(*) INTO depth_mismatch FROM atoms WHERE depth <> array_length(path_parts,1);
  IF depth_mismatch <> 0 THEN RAISE EXCEPTION 'BATCH-COMBINED FAIL: depth-mismatch=%', depth_mismatch; END IF;
  SELECT count(*) INTO skipped_level FROM atoms a WHERE a.depth > 1 AND NOT EXISTS (SELECT 1 FROM atoms p WHERE p.path = array_to_string(a.path_parts[1:a.depth-1], ' / '));
  IF skipped_level <> 0 THEN RAISE EXCEPTION 'BATCH-COMBINED FAIL: skipped-level=%', skipped_level; END IF;
  SELECT count(*) INTO dup_id FROM (SELECT id FROM atoms GROUP BY id HAVING count(*)>1) x;
  IF dup_id <> 0 THEN RAISE EXCEPTION 'BATCH-COMBINED FAIL: dup-id=%', dup_id; END IF;
  RAISE NOTICE 'BATCH-COMBINED OK: % atoms', new_total;
END$$;
