INSERT INTO _lists_moves_staging (old_id, new_id, new_path, new_realm_name) VALUES
  ('culture-performing-arts-music-lists-record-labels', 'culture-performing-arts-music-record-labels', 'Culture / Performing arts / Music / Record labels', 'Culture'),
  ('culture-performing-arts-music-lists-schools-of-music', 'culture-performing-arts-music-schools-of-music', 'Culture / Performing arts / Music / Schools of music', 'Culture'),
  ('culture-performing-arts-music-lists-songs-and-compositions', 'culture-performing-arts-music-songs-and-compositions', 'Culture / Performing arts / Music / Songs and compositions', 'Culture'),
  ('culture-performing-arts-music-lists-video-game-music', 'culture-performing-arts-music-video-game-music', 'Culture / Performing arts / Music / Video game music', 'Culture'),
  ('self-lists-cyclist-race-deaths', 'culture-sports-cycling-notable-deaths', 'Culture / Sports / Cycling / Notable deaths', 'Culture'),
  ('culture-sports-lists-gay-athletes', 'culture-sports-notable-athletes-gay-athletes', 'Culture / Sports / Notable athletes / Gay athletes', 'Culture'),
  ('culture-sports-lists-sports-leagues-defunct-sports-leagues', 'culture-sports-sports-leagues-defunct', 'Culture / Sports / Sports leagues / Defunct', 'Culture'),
  ('health-lists-psychiatric-drugs-by-condition', 'health-substances-psychiatric-drugs-by-condition', 'Health / Substances / Psychiatric drugs / By condition', 'Health'),
  ('history-lists-roman-sites', 'history-ancient-civilizations-roman-sites', 'History / Ancient civilizations / Roman / Sites', 'History'),
  ('history-lists-fires', 'history-historical-events-disasters-fires', 'History / Historical events / Disasters / Fires', 'History'),
  ('history-lists-industrial-disasters', 'history-historical-events-disasters-industrial', 'History / Historical events / Disasters / Industrial', 'History'),
  ('history-lists-natural-disasters', 'history-historical-events-disasters-natural', 'History / Historical events / Disasters / Natural', 'History'),
  ('history-lists-nuclear-accidents', 'history-historical-events-disasters-nuclear-accidents', 'History / Historical events / Disasters / Nuclear accidents', 'History'),
  ('history-lists-power-outages', 'history-historical-events-disasters-power-outages', 'History / Historical events / Disasters / Power outages', 'History'),
  ('religion-lists-monasteries-dissolved-by-henry-viii', 'history-historical-events-english-reformation-monasteries-dissolved-by-henry-viii', 'History / Historical events / English Reformation / Monasteries dissolved by Henry VIII', 'History'),
  ('history-lists-cyclones-list', 'history-historical-events-natural-disasters-cyclones', 'History / Historical events / Natural disasters / Cyclones', 'History'),
  ('history-lists-earthquakes', 'history-historical-events-natural-disasters-earthquakes', 'History / Historical events / Natural disasters / Earthquakes', 'History'),
  ('history-lists-archaeological-sites', 'history-historical-sciences-archaeology-archaeological-sites', 'History / Historical sciences / Archaeology / Archaeological sites', 'History'),
  ('tech-lists-wwii-weapons', 'history-wars-world-war-ii-weapons', 'History / Wars / World War II / Weapons', 'History'),
  ('human-activities-lists-schools', 'human-activities-views-education-practice-schools', 'Human activities / Views / Education (practice) / Schools', 'Human activities'),
  ('society-lists-youth-rights-list', 'justice-legal-frameworks-civil-liberties-youth-rights', 'Justice / Legal Frameworks / Civil liberties / Youth rights', 'Justice'),
  ('justice-lists-government-oversight-bodies', 'justice-patterns-institutional-capture-government-oversight-bodies', 'Justice / Patterns / Institutional capture / Government oversight bodies', 'Justice'),
  ('math-lists-tensor-theory', 'math-branches-of-mathematics-pure-mathematics-tensor-theory', 'Math / Branches of mathematics / Pure mathematics / Tensor theory', 'Math'),
  ('religion-lists-cathedrals', 'religion-concepts-sacred-architecture-cathedrals', 'Religion / Concepts / Sacred architecture / Cathedrals', 'Religion'),
  ('religion-lists-christian-denominations-list', 'religion-major-religions-christianity-denominations', 'Religion / Major religions / Christianity / Denominations', 'Religion'),
  ('religion-lists-indigetes-roman-gods-and-goddesses-list', 'religion-mythologies-roman-mythology-indigetes', 'Religion / Mythologies / Roman mythology / Indigetes', 'Religion'),
  ('religion-lists-patriarchs-of-antioch', 'religion-religious-roles-patriarchs-antioch', 'Religion / Religious roles / Patriarchs / Antioch', 'Religion'),
  ('religion-lists-patriarchs-of-constantinople', 'religion-religious-roles-patriarchs-constantinople', 'Religion / Religious roles / Patriarchs / Constantinople', 'Religion'),
  ('religion-lists-biblical-names', 'religion-sacred-texts-bible-names', 'Religion / Sacred texts / Bible / Names', 'Religion'),
  ('religion-lists-bible-stories', 'religion-sacred-texts-bible-stories', 'Religion / Sacred texts / Bible / Stories', 'Religion'),
  ('religion-lists-biblical-nameless', 'religion-sacred-texts-bible-unnamed-figures', 'Religion / Sacred texts / Bible / Unnamed figures', 'Religion'),
  ('science-lists-astronomy-lists-asteroid-groups', 'science-astronomy-and-space-science-solar-system-asteroid-groups', 'Science / Astronomy and space science / Solar System / Asteroid groups', 'Science'),
  ('science-lists-astronomy-lists-meteor-showers-list', 'science-astronomy-and-space-science-solar-system-meteor-showers', 'Science / Astronomy and space science / Solar System / Meteor showers', 'Science'),
  ('science-lists-astronomy-lists-minor-planets-list', 'science-astronomy-and-space-science-solar-system-minor-planets', 'Science / Astronomy and space science / Solar System / Minor planets', 'Science'),
  ('science-lists-astronomy-lists-possible-dwarf-planets-list', 'science-astronomy-and-space-science-solar-system-possible-dwarf-planets', 'Science / Astronomy and space science / Solar System / Possible dwarf planets', 'Science'),
  ('science-lists-astronomy-lists-trans-neptunian-objects', 'science-astronomy-and-space-science-solar-system-trans-neptunian-objects', 'Science / Astronomy and space science / Solar System / Trans-Neptunian objects', 'Science'),
  ('tech-lists-landings-on-extraterrestrial-bodies', 'science-astronomy-and-space-science-space-exploration-landings-on-extraterrestrial-bodies', 'Science / Astronomy and space science / Space exploration / Landings on extraterrestrial bodies', 'Science'),
  ('tech-lists-solar-system-probes', 'science-astronomy-and-space-science-space-exploration-solar-system-probes', 'Science / Astronomy and space science / Space exploration / Solar System probes', 'Science'),
  ('history-lists-space-shuttle-missions', 'science-astronomy-and-space-science-space-exploration-space-shuttle-missions', 'Science / Astronomy and space science / Space exploration / Space Shuttle missions', 'Science'),
  ('science-lists-plants-lists-domesticated-plants', 'science-biology-botany-domesticated-plants', 'Science / Biology / Botany / Domesticated plants', 'Science'),
  ('science-lists-plants-lists-edible-seeds', 'science-biology-botany-edible-seeds', 'Science / Biology / Botany / Edible seeds', 'Science'),
  ('science-lists-plants-lists-famous-trees', 'science-biology-botany-famous-trees', 'Science / Biology / Botany / Famous trees', 'Science'),
  ('science-lists-plants-lists-fruits-list', 'science-biology-botany-fruits', 'Science / Biology / Botany / Fruits', 'Science'),
  ('science-lists-plants-lists-garden-plants', 'science-biology-botany-garden-plants', 'Science / Biology / Botany / Garden plants', 'Science'),
  ('science-lists-plants-lists-herbs-list', 'science-biology-botany-herbs', 'Science / Biology / Botany / Herbs', 'Science'),
  ('science-lists-plants-lists-sequoia-groves', 'science-biology-botany-sequoia-groves', 'Science / Biology / Botany / Sequoia groves', 'Science'),
  ('science-lists-plants-lists-vegetables-list', 'science-biology-botany-vegetables', 'Science / Biology / Botany / Vegetables', 'Science'),
  ('science-lists-species-and-specimens-world-s-25-most-endangered-primates', 'science-biology-conservation-worlds-25-most-endangered-primates', 'Science / Biology / Conservation / World''s 25 Most Endangered Primates', 'Science'),
  ('science-lists-species-and-specimens-organisms-by-population', 'science-biology-ecology-organisms-by-population', 'Science / Biology / Ecology / Organisms by population', 'Science'),
  ('science-lists-feeding-behaviours', 'science-biology-ethology-feeding-behaviours', 'Science / Biology / Ethology / Feeding behaviours', 'Science'),
  ('science-lists-gene-families', 'science-biology-genetics-gene-families', 'Science / Biology / Genetics / Gene families', 'Science'),
  ('science-lists-latin-and-greek-systematic-names', 'science-biology-taxonomy-latin-and-greek-systematic-names', 'Science / Biology / Taxonomy / Latin and Greek systematic names', 'Science'),
  ('science-lists-species-and-specimens-organisms-named-after-famous-people', 'science-biology-taxonomy-organisms-named-after-famous-people', 'Science / Biology / Taxonomy / Organisms named after famous people', 'Science'),
  ('science-lists-species-and-specimens-organisms-named-after-works-of-fiction', 'science-biology-taxonomy-organisms-named-after-works-of-fiction', 'Science / Biology / Taxonomy / Organisms named after works of fiction', 'Science'),
  ('science-lists-species-and-specimens-domesticated-animals', 'science-biology-zoology-domesticated-animals', 'Science / Biology / Zoology / Domesticated animals', 'Science'),
  ('science-lists-chemistry-lists-biomolecules', 'science-chemistry-biochemistry-biomolecules', 'Science / Chemistry / Biochemistry / Biomolecules', 'Science'),
  ('science-lists-chemistry-lists-standard-electrode-potentials', 'science-chemistry-electrochemistry-standard-electrode-potentials', 'Science / Chemistry / Electrochemistry / Standard electrode potentials', 'Science'),
  ('science-lists-chemistry-lists-elements-by-number', 'science-chemistry-elements-by-atomic-number', 'Science / Chemistry / Elements / By atomic number', 'Science'),
  ('science-lists-chemistry-lists-elements-by-symbol', 'science-chemistry-elements-by-symbol', 'Science / Chemistry / Elements / By symbol', 'Science'),
  ('science-lists-chemistry-lists-isotope-table', 'science-chemistry-elements-isotopes', 'Science / Chemistry / Elements / Isotopes', 'Science'),
  ('science-lists-chemistry-lists-functional-groups', 'science-chemistry-organic-chemistry-functional-groups', 'Science / Chemistry / Organic chemistry / Functional groups', 'Science'),
  ('science-lists-chemistry-lists-enthalpy-change-of-formation', 'science-chemistry-thermodynamics-enthalpy-change-of-formation', 'Science / Chemistry / Thermodynamics / Enthalpy change of formation', 'Science'),
  ('human-activities-lists-greenhouse-gas-emissions-top-contributors', 'science-earth-science-climate-science-greenhouse-gas-emissions-top-contributors', 'Science / Earth science / Climate science / Greenhouse gas emissions, top contributors', 'Science'),
  ('human-activities-lists-greenhouse-gases-ipcc-list', 'science-earth-science-climate-science-greenhouse-gases-ipcc-list', 'Science / Earth science / Climate science / Greenhouse gases (IPCC list)', 'Science'),
  ('science-lists-earth-sciences-lists-landforms-list', 'science-earth-science-geology-landforms', 'Science / Earth science / Geology / Landforms', 'Science'),
  ('science-lists-earth-sciences-lists-oil-fields', 'science-earth-science-geology-oil-fields', 'Science / Earth science / Geology / Oil fields', 'Science'),
  ('science-lists-earth-sciences-lists-tectonic-plates-list', 'science-earth-science-geology-tectonic-plates', 'Science / Earth science / Geology / Tectonic plates', 'Science'),
  ('science-lists-earth-sciences-lists-uranium-mines', 'science-earth-science-geology-uranium-mines', 'Science / Earth science / Geology / Uranium mines', 'Science'),
  ('science-lists-earth-sciences-lists-tropical-cyclone-names', 'science-earth-science-meteorology-tropical-cyclone-names', 'Science / Earth science / Meteorology / Tropical cyclone names', 'Science'),
  ('science-lists-physics-lists-resistivities', 'science-physics-electromagnetism-resistivities', 'Science / Physics / Electromagnetism / Resistivities', 'Science'),
  ('science-lists-physics-lists-artificial-radiation-belts', 'science-physics-nuclear-physics-artificial-radiation-belts', 'Science / Physics / Nuclear physics / Artificial radiation belts', 'Science'),
  ('science-lists-physics-lists-particles-list', 'science-physics-particle-physics-particles', 'Science / Physics / Particle physics / Particles', 'Science'),
  ('science-lists-physics-lists-colors-list', 'science-physics-physics-concepts-colors', 'Science / Physics / Physics concepts / Colors', 'Science'),
  ('science-lists-physics-lists-cycles-physics', 'science-physics-physics-concepts-cycles', 'Science / Physics / Physics concepts / Cycles', 'Science'),
  ('science-lists-physics-lists-noise-types', 'science-physics-physics-concepts-noise-types', 'Science / Physics / Physics concepts / Noise types', 'Science'),
  ('science-lists-physics-lists-quantum-field-theories', 'science-physics-quantum-field-theory-theories', 'Science / Physics / Quantum field theory / Theories', 'Science'),
  ('science-lists-physics-lists-relativistic-equations', 'science-physics-relativity-equations', 'Science / Physics / Relativity / Equations', 'Science'),
  ('history-lists-scientific-discoveries', 'science-scientific-method-and-meta-science-history-of-science-scientific-discoveries', 'Science / Scientific method and meta-science / History of science / Scientific discoveries', 'Science'),
  ('self-lists-wartime-cross-dressers', 'self-identity-dimensions-gender-wartime-cross-dressers', 'Self / Identity dimensions / Gender / Wartime cross-dressers', 'Self'),
  ('self-lists-families-by-tree', 'self-relationships-family-family-trees', 'Self / Relationships / Family / Family trees', 'Self');