INSERT INTO _lists_moves_staging (old_id, new_id, new_path, new_realm_name) VALUES
  ('self-lists-disappeared-mysteriously', 'self-person-disappeared-mysteriously', 'Self / Person / Disappeared mysteriously', 'Self'),
  ('self-lists-eponymous-laws', 'self-person-eponymous-laws', 'Self / Person / Eponymous laws', 'Self'),
  ('self-lists-eponyms', 'self-person-eponyms', 'Self / Person / Eponyms', 'Self'),
  ('society-lists-banks-list', 'society-economy-and-business-banks', 'Society / Economy and business / Banks', 'Society'),
  ('society-lists-companies-list', 'society-economy-and-business-companies', 'Society / Economy and business / Companies', 'Society'),
  ('society-lists-cooperatives-list', 'society-economy-and-business-cooperatives', 'Society / Economy and business / Cooperatives', 'Society'),
  ('society-lists-corporate-assets', 'society-economy-and-business-corporate-assets', 'Society / Economy and business / Corporate assets', 'Society'),
  ('society-lists-economists', 'society-economy-and-business-economists', 'Society / Economy and business / Economists', 'Society'),
  ('society-lists-employer-associations-list', 'society-economy-and-business-employer-associations', 'Society / Economy and business / Employer associations', 'Society'),
  ('history-lists-tariffs', 'society-economy-and-business-tariffs', 'Society / Economy and business / Tariffs', 'Society'),
  ('society-lists-academic-fields', 'society-education-system-academic-fields', 'Society / Education (system) / Academic fields', 'Society'),
  ('society-lists-admissions-tests', 'society-education-system-admissions-tests', 'Society / Education (system) / Admissions tests', 'Society'),
  ('society-lists-fields-of-doctoral-studies', 'society-education-system-fields-of-doctoral-studies', 'Society / Education (system) / Fields of doctoral studies', 'Society'),
  ('society-lists-universities-and-colleges-list', 'society-education-system-universities-and-colleges', 'Society / Education (system) / Universities and colleges', 'Society'),
  ('society-lists-micronations', 'society-government-micronations', 'Society / Government / Micronations', 'Society'),
  ('society-lists-national-legislatures', 'society-government-national-legislatures', 'Society / Government / National legislatures', 'Society'),
  ('society-lists-case-law-list', 'society-law-case-law', 'Society / Law / Case law', 'Society'),
  ('history-lists-united-states-supreme-court-cases', 'society-law-united-states-supreme-court-cases', 'Society / Law / United States Supreme Court cases', 'Society'),
  ('society-lists-acronyms', 'society-linguistics-acronyms', 'Society / Linguistics / Acronyms', 'Society'),
  ('society-lists-shibboleths', 'society-linguistics-shibboleths', 'Society / Linguistics / Shibboleths', 'Society'),
  ('society-lists-symbols-list', 'society-linguistics-symbols', 'Society / Linguistics / Symbols', 'Society'),
  ('self-lists-terms-for-men', 'society-linguistics-terms-for-men', 'Society / Linguistics / Terms for men', 'Society'),
  ('society-lists-intelligence-agencies-list', 'society-military-and-security-intelligence-agencies', 'Society / Military and security / Intelligence agencies', 'Society'),
  ('society-lists-secret-police-organizations', 'society-military-and-security-secret-police-organizations', 'Society / Military and security / Secret police organizations', 'Society'),
  ('tech-lists-terrorist-groups', 'society-military-and-security-terrorist-groups', 'Society / Military and security / Terrorist groups', 'Society'),
  ('tech-lists-military-weapons-list', 'society-military-and-security-weapons', 'Society / Military and security / Weapons', 'Society'),
  ('society-lists-political-parties', 'society-politics-political-parties', 'Society / Politics / Political parties', 'Society'),
  ('society-lists-civic-fraternal-service-professional-organizations', 'society-social-institutions-civic-fraternal-service-professional-organizations', 'Society / Social institutions / Civic, fraternal, service, professional organizations', 'Society'),
  ('society-lists-environmental-organizations', 'society-social-institutions-environmental-organizations', 'Society / Social institutions / Environmental organizations', 'Society'),
  ('society-lists-guide-dog-schools', 'society-social-institutions-guide-dog-schools', 'Society / Social institutions / Guide dog schools', 'Society'),
  ('society-lists-honorary-societies', 'society-social-institutions-honorary-societies', 'Society / Social institutions / Honorary societies', 'Society'),
  ('society-lists-think-tanks', 'society-social-institutions-think-tanks', 'Society / Social institutions / Think tanks', 'Society'),
  ('society-lists-feminism-list', 'society-social-movements-feminism', 'Society / Social movements / Feminism', 'Society'),
  ('history-lists-strikes', 'society-social-movements-strikes', 'Society / Social movements / Strikes', 'Society'),
  ('society-lists-social-science-journals', 'society-social-sciences-journals', 'Society / Social sciences / Journals', 'Society'),
  ('society-lists-lifestyles', 'society-society-concepts-lifestyles', 'Society / Society concepts / Lifestyles', 'Society'),
  ('society-lists-prizes-medals-and-awards', 'society-society-concepts-prizes-medals-and-awards', 'Society / Society concepts / Prizes, medals, and awards', 'Society'),
  ('society-lists-scandals-with-gate-suffix', 'society-society-concepts-scandals-with-gate-suffix', 'Society / Society concepts / Scandals with "-gate" suffix', 'Society'),
  ('tech-lists-character-sets-and-encodings', 'tech-computing-character-encoding', 'Tech / Computing / Character encoding', 'Tech'),
  ('tech-lists-demolished-landmarks', 'tech-construction-and-built-environment-demolished-landmarks', 'Tech / Construction and built environment / Demolished landmarks', 'Tech'),
  ('tech-lists-heritage-registers', 'tech-construction-and-built-environment-heritage-registers', 'Tech / Construction and built environment / Heritage registers', 'Tech'),
  ('tech-lists-tallest-buildings', 'tech-construction-and-built-environment-tallest-buildings', 'Tech / Construction and built environment / Tallest buildings', 'Tech'),
  ('tech-lists-largest-energy-infrastructure', 'tech-energy-technology-largest-energy-infrastructure', 'Tech / Energy technology / Largest energy infrastructure', 'Tech'),
  ('society-lists-emoticons', 'tech-internet-and-web-emoticons', 'Tech / Internet and Web / Emoticons', 'Tech'),
  ('tech-lists-wikis-list', 'tech-internet-and-web-wikis', 'Tech / Internet and Web / Wikis', 'Tech'),
  ('tech-lists-missile-list', 'tech-military-technology-missiles', 'Tech / Military technology / Missiles', 'Tech'),
  ('tech-lists-nato-reporting-names', 'tech-military-technology-nato-reporting-names', 'Tech / Military technology / NATO reporting names', 'Tech'),
  ('culture-games-lists-japanese-board-games', 'culture-games-board-games-japanese-board-games', 'Culture / Games / Board games / Japanese board games', 'Culture'),
  ('culture-games-lists-mancala-variants', 'culture-games-board-games-mancala-variants', 'Culture / Games / Board games / Mancala variants', 'Culture'),
  ('culture-games-lists-board-game-publishers', 'culture-games-board-games-publishers', 'Culture / Games / Board games / Publishers', 'Culture'),
  ('culture-games-lists-miniature-wargames', 'culture-games-tabletop-games-miniature-wargames', 'Culture / Games / Tabletop games / Miniature wargames', 'Culture'),
  ('culture-games-video-games-lists-arcade-games', 'culture-games-video-games-arcade-games', 'Culture / Games / Video games / Arcade games', 'Culture'),
  ('culture-games-video-games-lists-console-palettes', 'culture-games-video-games-console-palettes', 'Culture / Games / Video games / Console palettes', 'Culture'),
  ('science-lists-earth-sciences-lists-birthstones', 'culture-gastronomy-materials-birthstones', 'Culture / Gastronomy / Materials / Birthstones', 'Culture'),
  ('culture-literature-lists-books-banned-books', 'culture-literature-books-banned-books', 'Culture / Literature / Books / Banned books', 'Culture'),
  ('culture-literature-lists-books-best-selling-books', 'culture-literature-books-best-selling', 'Culture / Literature / Books / Best-selling', 'Culture'),
  ('culture-literature-lists-books-literary-awards', 'culture-literature-books-literary-awards', 'Culture / Literature / Books / Literary awards', 'Culture'),
  ('culture-literature-lists-electronic-literature-electronic-literature-authors-critics-and-works', 'culture-literature-electronic-literature-authors-critics-and-works', 'Culture / Literature / Electronic literature / Authors, critics, and works', 'Culture'),
  ('culture-literature-lists-fiction-comics', 'culture-literature-fiction-comics', 'Culture / Literature / Fiction / Comics', 'Culture'),
  ('culture-literature-lists-fiction-fairy-tales', 'culture-literature-fiction-fairy-tales', 'Culture / Literature / Fiction / Fairy tales', 'Culture'),
  ('culture-literature-lists-fiction-fictional-characters', 'culture-literature-fiction-fictional-characters', 'Culture / Literature / Fiction / Fictional characters', 'Culture'),
  ('culture-literature-lists-fiction-fictional-computers', 'culture-literature-fiction-fictional-computers', 'Culture / Literature / Fiction / Fictional computers', 'Culture'),
  ('culture-literature-lists-fiction-fictional-places', 'culture-literature-fiction-fictional-places', 'Culture / Literature / Fiction / Fictional places', 'Culture'),
  ('culture-literature-lists-fiction-fictional-robots-and-androids', 'culture-literature-fiction-fictional-robots-and-androids', 'Culture / Literature / Fiction / Fictional robots and androids', 'Culture'),
  ('culture-literature-lists-fiction-major-themes', 'culture-literature-fiction-major-themes', 'Culture / Literature / Fiction / Major themes', 'Culture'),
  ('society-lists-fictional-psychiatrists', 'culture-literature-fictional-characters-fictional-psychiatrists', 'Culture / Literature / Fictional characters / Fictional psychiatrists', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-actors', 'culture-mass-media-film-and-cinema-actors', 'Culture / Mass media / Film and cinema / Actors', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-film-awards', 'culture-mass-media-film-and-cinema-awards', 'Culture / Mass media / Film and cinema / Awards', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-directors', 'culture-mass-media-film-and-cinema-directors', 'Culture / Mass media / Film and cinema / Directors', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-film-festivals', 'culture-mass-media-film-and-cinema-festivals', 'Culture / Mass media / Film and cinema / Festivals', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films', 'culture-mass-media-film-and-cinema-films', 'Culture / Mass media / Film and cinema / Films', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-film-institutes', 'culture-mass-media-film-and-cinema-institutes', 'Culture / Mass media / Film and cinema / Institutes', 'Culture'),
  ('culture-literature-lists-magazines', 'culture-mass-media-print-media-magazines', 'Culture / Mass media / Print media / Magazines', 'Culture'),
  ('culture-performing-arts-music-lists-concert-tours', 'culture-performing-arts-music-concert-tours', 'Culture / Performing arts / Music / Concert tours', 'Culture'),
  ('culture-performing-arts-music-lists-electronic-music-lists', 'culture-performing-arts-music-electronic-music', 'Culture / Performing arts / Music / Electronic music', 'Culture'),
  ('culture-performing-arts-music-lists-music-genres', 'culture-performing-arts-music-genres', 'Culture / Performing arts / Music / Genres', 'Culture'),
  ('history-lists-musical-events-historical', 'culture-performing-arts-music-historical-musical-events', 'Culture / Performing arts / Music / Historical musical events', 'Culture'),
  ('culture-performing-arts-music-lists-musical-events', 'culture-performing-arts-music-musical-events', 'Culture / Performing arts / Music / Musical events', 'Culture'),
  ('culture-performing-arts-music-lists-musicians-and-musical-groups', 'culture-performing-arts-music-musicians-and-groups', 'Culture / Performing arts / Music / Musicians and groups', 'Culture'),
  ('culture-performing-arts-music-lists-opera-houses', 'culture-performing-arts-music-opera-houses', 'Culture / Performing arts / Music / Opera houses', 'Culture');