INSERT INTO _lists_moves_staging (old_id, new_id, new_path, new_realm_name) VALUES
  ('history-lists-historical-sites', 'history-historical-sites', 'History / Historical sites', 'History'),
  ('philosophy-lists-philosophers-role-category', 'philosophy-philosophers', 'Philosophy / Philosophers', 'Philosophy'),
  ('culture-literature-lists-books', 'culture-literature-books', 'Culture / Literature / Books', 'Culture'),
  ('culture-literature-lists-electronic-literature', 'culture-literature-electronic-literature', 'Culture / Literature / Electronic literature', 'Culture'),
  ('culture-literature-lists-publishers', 'culture-literature-publishers', 'Culture / Literature / Publishers', 'Culture'),
  ('culture-literature-lists-books-writers', 'culture-literature-writers', 'Culture / Literature / Writers', 'Culture'),
  ('self-lists-entertainer-deaths-while-performing', 'culture-performing-arts-notable-on-stage-deaths', 'Culture / Performing arts / Notable on-stage deaths', 'Culture'),
  ('culture-sports-lists-climbing', 'culture-sports-climbing', 'Culture / Sports / Climbing', 'Culture'),
  ('culture-sports-lists-sports-leagues', 'culture-sports-sports-leagues', 'Culture / Sports / Sports leagues', 'Culture'),
  ('health-lists-reference-ranges-for-common-blood-tests', 'health-health-sciences-reference-ranges-for-common-blood-tests', 'Health / Health sciences / Reference ranges for common blood tests', 'Health'),
  ('health-lists-acronyms-in-healthcare', 'health-medicine-acronyms-in-healthcare', 'Health / Medicine / Acronyms in healthcare', 'Health'),
  ('health-lists-alternative-medicine-modalities', 'health-medicine-alternative-medicine-modalities', 'Health / Medicine / Alternative medicine modalities', 'Health'),
  ('health-lists-medical-abbreviations', 'health-medicine-medical-abbreviations', 'Health / Medicine / Medical abbreviations', 'Health'),
  ('health-lists-surgical-procedures', 'health-medicine-surgical-procedures', 'Health / Medicine / Surgical procedures', 'Health'),
  ('society-lists-diagnostic-classification-and-rating-scales', 'health-mental-health-diagnostic-classification-and-rating-scales', 'Health / Mental health / Diagnostic classification and rating scales', 'Health'),
  ('health-lists-psychotherapies', 'health-mental-health-psychotherapies', 'Health / Mental health / Psychotherapies', 'Health'),
  ('science-lists-causes-of-death', 'health-public-health-causes-of-death', 'Health / Public health / Causes of death', 'Health'),
  ('history-lists-historians-by-subfield', 'history-historians-by-subfield', 'History / Historians / By subfield', 'History'),
  ('history-lists-coups-and-coup-attempts', 'history-historical-events-coups-and-coup-attempts', 'History / Historical events / Coups and coup attempts', 'History'),
  ('history-lists-disasters', 'history-historical-events-disasters', 'History / Historical events / Disasters', 'History'),
  ('human-activities-lists-environmental-disasters-list', 'history-historical-events-environmental-disasters', 'History / Historical events / Environmental disasters', 'History'),
  ('history-lists-epidemics', 'history-historical-events-epidemics', 'History / Historical events / Epidemics', 'History'),
  ('history-lists-famous-deaths-by-cause', 'history-historical-events-famous-deaths-by-cause', 'History / Historical events / Famous deaths by cause', 'History'),
  ('history-lists-famous-speeches', 'history-historical-events-famous-speeches', 'History / Historical events / Famous speeches', 'History'),
  ('history-lists-helicopter-prison-escapes', 'history-historical-events-helicopter-prison-escapes', 'History / Historical events / Helicopter prison escapes', 'History'),
  ('history-lists-inventions', 'history-historical-events-inventions', 'History / Historical events / Inventions', 'History'),
  ('history-lists-inventors-killed-by-their-own-inventions', 'history-historical-events-inventors-killed-by-their-own-inventions', 'History / Historical events / Inventors killed by their own inventions', 'History'),
  ('history-lists-kidnappings', 'history-historical-events-kidnappings', 'History / Historical events / Kidnappings', 'History'),
  ('history-lists-missing-treasure', 'history-historical-events-missing-treasure', 'History / Historical events / Missing treasure', 'History'),
  ('history-lists-nobel-prizes', 'history-historical-events-nobel-prizes', 'History / Historical events / Nobel Prizes', 'History'),
  ('self-lists-political-self-immolations', 'history-historical-events-political-self-immolations', 'History / Historical events / Political self-immolations', 'History'),
  ('history-lists-recessions', 'history-historical-events-recessions', 'History / Historical events / Recessions', 'History'),
  ('history-lists-revolutions-and-rebellions', 'history-historical-events-revolutions-and-rebellions', 'History / Historical events / Revolutions and rebellions', 'History'),
  ('history-lists-riots', 'history-historical-events-riots', 'History / Historical events / Riots', 'History'),
  ('tech-lists-terrorist-incidents', 'history-historical-events-terrorist-incidents', 'History / Historical events / Terrorist incidents', 'History'),
  ('history-lists-ticker-tape-parades-in-new-york-city', 'history-historical-events-ticker-tape-parades-in-new-york-city', 'History / Historical events / Ticker-tape parades in New York City', 'History'),
  ('history-lists-treaties', 'history-historical-events-treaties', 'History / Historical events / Treaties', 'History'),
  ('history-lists-former-sovereign-states', 'history-historical-states-former-sovereign-states', 'History / Historical states / Former sovereign states', 'History'),
  ('history-lists-battles', 'history-military-history-battles', 'History / Military history / Battles', 'History'),
  ('human-activities-lists-battles-by-casualties', 'history-military-history-battles-by-casualties', 'History / Military history / Battles by casualties', 'History'),
  ('history-lists-military-disasters', 'history-military-history-disasters', 'History / Military history / Disasters', 'History'),
  ('history-lists-guerrilla-movements', 'history-military-history-guerrilla-movements', 'History / Military history / Guerrilla movements', 'History'),
  ('history-lists-invasions', 'history-military-history-invasions', 'History / Military history / Invasions', 'History'),
  ('history-lists-military-operations', 'history-military-history-operations', 'History / Military history / Operations', 'History'),
  ('history-lists-sieges', 'history-military-history-sieges', 'History / Military history / Sieges', 'History'),
  ('human-activities-lists-wars-by-death-toll', 'history-wars-by-death-toll', 'History / Wars / By death toll', 'History'),
  ('history-lists-civil-wars-list', 'history-wars-civil-wars', 'History / Wars / Civil wars', 'History'),
  ('justice-lists-investigative-journalism-outlets', 'justice-evidence-investigative-journalism-outlets', 'Justice / Evidence / Investigative journalism outlets', 'Justice'),
  ('justice-lists-notable-whistleblowers-reference', 'justice-evidence-notable-whistleblowers', 'Justice / Evidence / Notable whistleblowers', 'Justice'),
  ('justice-lists-whistleblower-support-organizations', 'justice-evidence-whistleblower-support-organizations', 'Justice / Evidence / Whistleblower support organizations', 'Justice'),
  ('justice-lists-truth-commissions-historical', 'justice-progress-truth-commissions', 'Justice / Progress / Truth commissions', 'Justice'),
  ('human-activities-lists-methods-of-capital-punishment', 'justice-prosecutions-methods-of-capital-punishment', 'Justice / Prosecutions / Methods of capital punishment', 'Justice'),
  ('justice-lists-notable-accountability-cases-reference', 'justice-prosecutions-notable-accountability-cases', 'Justice / Prosecutions / Notable accountability cases', 'Justice'),
  ('math-lists-games-mathematical', 'math-concepts-mathematical-games', 'Math / Concepts / Mathematical games', 'Math'),
  ('math-lists-principia-mathematica-glossary-items', 'math-foundations-and-meta-mathematics-principia-mathematica-glossary', 'Math / Foundations and meta-mathematics / Principia Mathematica glossary', 'Math'),
  ('math-lists-integrals', 'math-mathematical-objects-integrals', 'Math / Mathematical objects / Integrals', 'Math'),
  ('math-lists-mathematical-series', 'math-mathematical-objects-mathematical-series', 'Math / Mathematical objects / Mathematical series', 'Math'),
  ('math-lists-prime-numbers-list', 'math-mathematical-objects-prime-numbers', 'Math / Mathematical objects / Prime numbers', 'Math'),
  ('math-lists-shapes-with-metaphorical-names', 'math-mathematical-objects-shapes-with-metaphorical-names', 'Math / Mathematical objects / Shapes with metaphorical names', 'Math'),
  ('religion-lists-angels-list', 'religion-beings-angels', 'Religion / Beings / Angels', 'Religion'),
  ('religion-lists-deities-list', 'religion-beings-deities', 'Religion / Beings / Deities', 'Religion'),
  ('religion-lists-demons-list', 'religion-beings-demons', 'Religion / Beings / Demons', 'Religion'),
  ('human-activities-lists-mudras', 'religion-concepts-mudras', 'Religion / Concepts / Mudras', 'Religion'),
  ('religion-lists-people-claimed-to-be-jesus', 'religion-issues-and-debates-messianic-claimants', 'Religion / Issues and debates / Messianic claimants', 'Religion'),
  ('religion-lists-founders-religious-list', 'religion-religious-roles-founders', 'Religion / Religious roles / Founders', 'Religion'),
  ('religion-lists-popes-list', 'religion-religious-roles-popes', 'Religion / Religious roles / Popes', 'Religion'),
  ('religion-lists-saints-list', 'religion-religious-roles-saints', 'Religion / Religious roles / Saints', 'Religion'),
  ('science-lists-astronomy-lists-astronomical-catalogues', 'science-astronomy-and-space-science-astronomical-catalogues', 'Science / Astronomy and space science / Astronomical catalogues', 'Science'),
  ('science-lists-astronomy-lists-astronomical-objects-named-after-people', 'science-astronomy-and-space-science-astronomical-objects-named-after-people', 'Science / Astronomy and space science / Astronomical objects named after people', 'Science'),
  ('science-lists-astronomy-lists-astronomical-societies', 'science-astronomy-and-space-science-astronomical-societies', 'Science / Astronomy and space science / Astronomical societies', 'Science'),
  ('science-lists-astronomy-lists-astronomical-symbols', 'science-astronomy-and-space-science-astronomical-symbols', 'Science / Astronomy and space science / Astronomical symbols', 'Science'),
  ('science-lists-astronomy-lists-future-astronomical-events', 'science-astronomy-and-space-science-future-astronomical-events', 'Science / Astronomy and space science / Future astronomical events', 'Science'),
  ('science-lists-astronomy-lists-most-distant-astronomical-objects', 'science-astronomy-and-space-science-most-distant-astronomical-objects', 'Science / Astronomy and space science / Most distant astronomical objects', 'Science'),
  ('science-lists-astronomy-lists-space-telescopes', 'science-astronomy-and-space-science-space-telescopes', 'Science / Astronomy and space science / Space telescopes', 'Science'),
  ('science-lists-astronomy-lists-telescopes', 'science-astronomy-and-space-science-telescopes', 'Science / Astronomy and space science / Telescopes', 'Science'),
  ('science-lists-biological-journals', 'science-biology-biological-journals', 'Science / Biology / Biological journals', 'Science'),
  ('science-lists-chemistry-lists-compounds-list', 'science-chemistry-compounds', 'Science / Chemistry / Compounds', 'Science'),
  ('science-lists-physics-lists-laws-in-science', 'science-scientific-method-and-meta-science-laws-in-science', 'Science / Scientific method and meta-science / Laws in science', 'Science'),
  ('science-lists-physics-lists-letters-used-in-mathematics-and-science', 'science-scientific-method-and-meta-science-letters-used-in-mathematics-and-science', 'Science / Scientific method and meta-science / Letters used in mathematics and science', 'Science'),
  ('culture-literature-lists-scientific-journals', 'science-scientific-method-and-meta-science-scientific-journals', 'Science / Scientific method and meta-science / Scientific journals', 'Science');