INSERT INTO _lists_moves_staging (old_id, new_id, new_path, new_realm_name) VALUES
  ('society-lists-business-theorists', 'society-economy-and-business-business-administration-business-theorists', 'Society / Economy and business / Business administration / Business theorists', 'Society'),
  ('society-lists-employee-owned-companies', 'society-economy-and-business-companies-employee-owned', 'Society / Economy and business / Companies / Employee-owned', 'Society'),
  ('society-lists-feminist-economists', 'society-economy-and-business-economists-feminist-economists', 'Society / Economy and business / Economists / Feminist economists', 'Society'),
  ('society-lists-stock-exchanges', 'society-economy-and-business-finance-stock-exchanges', 'Society / Economy and business / Finance / Stock exchanges', 'Society'),
  ('society-lists-stock-market-indices', 'society-economy-and-business-finance-stock-market-indices', 'Society / Economy and business / Finance / Stock market indices', 'Society'),
  ('society-lists-traded-commodities', 'society-economy-and-business-finance-traded-commodities', 'Society / Economy and business / Finance / Traded commodities', 'Society'),
  ('society-lists-department-stores', 'society-economy-and-business-retail-department-stores', 'Society / Economy and business / Retail / Department stores', 'Society'),
  ('society-lists-store-brands', 'society-economy-and-business-retail-store-brands', 'Society / Economy and business / Retail / Store brands', 'Society'),
  ('society-lists-supermarkets', 'society-economy-and-business-retail-supermarkets', 'Society / Economy and business / Retail / Supermarkets', 'Society'),
  ('history-lists-foreign-policy-doctrines', 'society-government-foreign-policy-doctrines', 'Society / Government / Foreign policy / Doctrines', 'Society'),
  ('society-lists-national-anthems', 'society-government-national-symbols-anthems', 'Society / Government / National symbols / Anthems', 'Society'),
  ('society-lists-united-states-federal-agencies', 'society-government-united-states-federal-agencies', 'Society / Government / United States / Federal agencies', 'Society'),
  ('society-lists-united-states-mints', 'society-government-united-states-mints', 'Society / Government / United States / Mints', 'Society'),
  ('society-lists-consonants', 'society-linguistics-phonetics-consonants', 'Society / Linguistics / Phonetics / Consonants', 'Society'),
  ('society-lists-vowels-table', 'society-linguistics-phonetics-vowels', 'Society / Linguistics / Phonetics / Vowels', 'Society'),
  ('society-lists-generic-names-of-political-parties', 'society-politics-political-parties-generic-names', 'Society / Politics / Political parties / Generic names', 'Society'),
  ('society-lists-british-professional-bodies', 'society-social-institutions-professional-bodies-british', 'Society / Social institutions / Professional bodies / British', 'Society'),
  ('society-lists-trade-unions-list', 'society-social-movements-labor-trade-unions', 'Society / Social movements / Labor / Trade unions', 'Society'),
  ('society-lists-lgbt-related-organizations', 'society-social-movements-lgbt-organizations', 'Society / Social movements / LGBT / Organizations', 'Society'),
  ('society-lists-california-suffragists', 'society-social-movements-suffragists-california', 'Society / Social movements / Suffragists / California', 'Society'),
  ('society-lists-women-s-organizations', 'society-social-movements-women-organizations', 'Society / Social movements / Women / Organizations', 'Society'),
  ('society-lists-clinical-psychologists', 'society-social-sciences-psychology-clinical-psychologists', 'Society / Social sciences / Psychology / Clinical psychologists', 'Society'),
  ('society-lists-credentials-in-psychology', 'society-social-sciences-psychology-credentials', 'Society / Social sciences / Psychology / Credentials', 'Society'),
  ('society-lists-psychology-disciplines', 'society-social-sciences-psychology-disciplines', 'Society / Social sciences / Psychology / Disciplines', 'Society'),
  ('society-lists-emotions-list', 'society-social-sciences-psychology-emotions', 'Society / Social sciences / Psychology / Emotions', 'Society'),
  ('society-lists-memory-biases-list', 'society-social-sciences-psychology-memory-biases', 'Society / Social sciences / Psychology / Memory biases', 'Society'),
  ('society-lists-psychologists', 'society-social-sciences-psychology-psychologists', 'Society / Social sciences / Psychology / Psychologists', 'Society'),
  ('society-lists-psychological-schools', 'society-social-sciences-psychology-schools-of-thought', 'Society / Social sciences / Psychology / Schools of thought', 'Society'),
  ('society-lists-scientific-journals-in-psychology', 'society-social-sciences-psychology-scientific-journals', 'Society / Social sciences / Psychology / Scientific journals', 'Society'),
  ('society-lists-social-psychologists', 'society-social-sciences-psychology-social-psychologists', 'Society / Social sciences / Psychology / Social psychologists', 'Society'),
  ('society-lists-sociologists', 'society-social-sciences-sociology-sociologists', 'Society / Social sciences / Sociology / Sociologists', 'Society'),
  ('society-lists-subfields-of-sociology-list', 'society-social-sciences-sociology-subfields', 'Society / Social sciences / Sociology / Subfields', 'Society'),
  ('tech-lists-ascii', 'tech-computing-character-encoding-ascii', 'Tech / Computing / Character encoding / ASCII', 'Tech'),
  ('tech-lists-unicode', 'tech-computing-character-encoding-unicode', 'Tech / Computing / Character encoding / Unicode', 'Tech'),
  ('tech-lists-utf-8', 'tech-computing-character-encoding-utf-8', 'Tech / Computing / Character encoding / UTF-8', 'Tech'),
  ('tech-lists-xml-and-html-characters', 'tech-computing-character-encoding-xml-and-html-character-entities', 'Tech / Computing / Character encoding / XML and HTML character entities', 'Tech'),
  ('tech-lists-graphics-file-formats', 'tech-computing-file-formats-graphics', 'Tech / Computing / File formats / Graphics', 'Tech'),
  ('tech-lists-software-bugs-list', 'tech-computing-software-notable-software-bugs', 'Tech / Computing / Software / Notable software bugs', 'Tech'),
  ('tech-lists-open-source-software-packages', 'tech-computing-software-open-source', 'Tech / Computing / Software / Open source', 'Tech'),
  ('tech-lists-operating-systems-list', 'tech-computing-software-operating-systems', 'Tech / Computing / Software / Operating systems', 'Tech'),
  ('tech-lists-canals-list', 'tech-construction-and-built-environment-civil-engineering-canals', 'Tech / Construction and built environment / Civil engineering / Canals', 'Tech'),
  ('tech-lists-civil-engineering-landmarks', 'tech-construction-and-built-environment-civil-engineering-landmarks', 'Tech / Construction and built environment / Civil engineering / Landmarks', 'Tech'),
  ('tech-lists-reservoirs-and-dams-list', 'tech-construction-and-built-environment-civil-engineering-reservoirs-and-dams', 'Tech / Construction and built environment / Civil engineering / Reservoirs and dams', 'Tech'),
  ('tech-lists-world-heritage-sites', 'tech-construction-and-built-environment-heritage-registers-unesco-world-heritage-sites', 'Tech / Construction and built environment / Heritage registers / UNESCO World Heritage Sites', 'Tech'),
  ('tech-lists-tcp-and-udp-port-numbers', 'tech-internet-and-web-protocols-tcp-and-udp-port-numbers', 'Tech / Internet and Web / Protocols / TCP and UDP port numbers', 'Tech'),
  ('tech-lists-aircraft-manufacturers', 'tech-transport-technology-aircraft-manufacturers', 'Tech / Transport technology / Aircraft / Manufacturers', 'Tech'),
  ('tech-lists-lighthouses', 'tech-transport-technology-maritime-lighthouses', 'Tech / Transport technology / Maritime / Lighthouses', 'Tech'),
  ('tech-lists-famous-trains', 'tech-transport-technology-rail-transport-famous-trains', 'Tech / Transport technology / Rail transport / Famous trains', 'Tech'),
  ('culture-games-board-games-chess-lists-chess-books', 'culture-games-board-games-chess-books', 'Culture / Games / Board games / Chess / Books', 'Culture'),
  ('culture-games-board-games-chess-lists-fairy-pieces', 'culture-games-board-games-chess-fairy-pieces', 'Culture / Games / Board games / Chess / Fairy pieces', 'Culture'),
  ('culture-games-board-games-chess-lists-chess-games', 'culture-games-board-games-chess-notable-games', 'Culture / Games / Board games / Chess / Notable games', 'Culture'),
  ('culture-games-board-games-chess-lists-chess-openings', 'culture-games-board-games-chess-openings', 'Culture / Games / Board games / Chess / Openings', 'Culture'),
  ('culture-games-board-games-chess-lists-chess-players', 'culture-games-board-games-chess-players', 'Culture / Games / Board games / Chess / Players', 'Culture'),
  ('culture-games-board-games-chess-lists-chess-terms', 'culture-games-board-games-chess-terms', 'Culture / Games / Board games / Chess / Terms', 'Culture'),
  ('culture-games-board-games-chess-lists-chess-tournaments', 'culture-games-board-games-chess-tournaments', 'Culture / Games / Board games / Chess / Tournaments', 'Culture'),
  ('culture-games-board-games-chess-lists-world-championship-matches', 'culture-games-board-games-chess-world-championship-matches', 'Culture / Games / Board games / Chess / World Championship matches', 'Culture'),
  ('culture-games-board-games-chess-lists-chess-world-records', 'culture-games-board-games-chess-world-records', 'Culture / Games / Board games / Chess / World records', 'Culture'),
  ('culture-literature-lists-fiction-comics-comic-books', 'culture-literature-fiction-comics-comic-books', 'Culture / Literature / Fiction / Comics / Comic books', 'Culture'),
  ('culture-literature-lists-fiction-comics-comic-strips', 'culture-literature-fiction-comics-comic-strips', 'Culture / Literature / Fiction / Comics / Comic strips', 'Culture'),
  ('culture-literature-lists-fiction-comics-manga', 'culture-literature-fiction-comics-manga', 'Culture / Literature / Fiction / Comics / Manga', 'Culture'),
  ('culture-literature-lists-fiction-fictional-places-fictional-countries', 'culture-literature-fiction-fictional-places-countries', 'Culture / Literature / Fiction / Fictional places / Countries', 'Culture'),
  ('culture-literature-lists-fiction-fictional-places-imaginary-universes', 'culture-literature-fiction-fictional-places-imaginary-universes', 'Culture / Literature / Fiction / Fictional places / Imaginary universes', 'Culture'),
  ('culture-literature-lists-fiction-fictional-places-fictional-planets', 'culture-literature-fiction-fictional-places-planets', 'Culture / Literature / Fiction / Fictional places / Planets', 'Culture'),
  ('culture-literature-lists-fiction-major-themes-science-fiction', 'culture-literature-fiction-genres-science-fiction', 'Culture / Literature / Fiction / Genres / Science fiction', 'Culture'),
  ('culture-literature-lists-fiction-major-themes-adultery', 'culture-literature-fiction-major-themes-adultery', 'Culture / Literature / Fiction / Major themes / Adultery', 'Culture'),
  ('culture-literature-lists-fiction-major-themes-family', 'culture-literature-fiction-major-themes-family', 'Culture / Literature / Fiction / Major themes / Family', 'Culture'),
  ('culture-literature-lists-fiction-major-themes-sadomasochism', 'culture-literature-fiction-major-themes-sadomasochism', 'Culture / Literature / Fiction / Major themes / Sadomasochism', 'Culture'),
  ('culture-literature-lists-fiction-major-themes-travel', 'culture-literature-fiction-major-themes-travel', 'Culture / Literature / Fiction / Major themes / Travel', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-channels', 'culture-mass-media-broadcast-media-television-channels', 'Culture / Mass media / Broadcast media / Television / Channels', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-networks', 'culture-mass-media-broadcast-media-television-networks', 'Culture / Mass media / Broadcast media / Television / Networks', 'Culture'),
  ('culture-mass-media-broadcast-media-television-lists-television-programs', 'culture-mass-media-broadcast-media-television-programs', 'Culture / Mass media / Broadcast media / Television / Programs', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-computer-animated-films', 'culture-mass-media-film-and-cinema-films-computer-animated', 'Culture / Mass media / Film and cinema / Films / Computer-animated', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-film-series', 'culture-mass-media-film-and-cinema-films-film-series', 'Culture / Mass media / Film and cinema / Films / Film series', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-greatest', 'culture-mass-media-film-and-cinema-films-greatest', 'Culture / Mass media / Film and cinema / Films / Greatest', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-highest-grossing', 'culture-mass-media-film-and-cinema-films-highest-grossing', 'Culture / Mass media / Film and cinema / Films / Highest-grossing', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-most-expensive', 'culture-mass-media-film-and-cinema-films-most-expensive', 'Culture / Mass media / Film and cinema / Films / Most expensive', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-preserved-films', 'culture-mass-media-film-and-cinema-films-preserved-films', 'Culture / Mass media / Film and cinema / Films / Preserved films', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-rated-nc-17', 'culture-mass-media-film-and-cinema-films-rated-nc-17', 'Culture / Mass media / Film and cinema / Films / Rated NC-17', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-trilogies', 'culture-mass-media-film-and-cinema-films-trilogies', 'Culture / Mass media / Film and cinema / Films / Trilogies', 'Culture'),
  ('culture-mass-media-film-and-cinema-lists-films-worst', 'culture-mass-media-film-and-cinema-films-worst', 'Culture / Mass media / Film and cinema / Films / Worst', 'Culture');