-- =============================================================================
-- Migration 20260515000000 — origin_restricted column + bling_transactions.type
--                            CHECK extension for escrow_in / escrow_unlock
-- =============================================================================
-- Date:        2026-05-15
-- Author:      Code 3 (Claude Opus 4.7) — supervised by OG HUMAN
-- Branch:      feat/escrow-v1 (TheMANUAL.tech sibling repo)
-- Status:      UNAPPLIED. Author commits; OG HUMAN applies via Studio MCP after
--              review. DO NOT auto-apply.
-- Source:      ~/Documents/HONEYCOMB/escrow-mechanics-v1-spec.md (v1.0 RATIFIED
--              Thu 2026-05-14 late evening) — §8 single-hop mechanic; A4 v1.0
--              §9 "tainted at source, cleaned by movement"
-- Siblings:    20260515000100_escrow_retirement.sql      (Migration 2 — depends)
--              20260515000200_escrow_emergency_fund.sql  (Migration 3 — depends)
--              20260515000300_annual_unlock_check.sql    (Migration 4 — depends)
--
-- Purpose:
--   (a) Add `origin_restricted BOOLEAN` to `bling_transactions` for the single-
--       hop non-sellable mechanic (NewBEE welcome bonus per A4 §7, Emergency
--       Fund Escrow unlock per escrow-mechanics-v1-spec §8).
--   (b) Extend `bling_transactions.type` CHECK to include `'escrow_in'` and
--       `'escrow_unlock'` — required by Migration 2/3 RPC bodies.
--
-- Backfill: none. New column defaults to FALSE; existing rows acquire FALSE
--           silently (column add is metadata-only on Postgres ≥11).
--
-- Idempotency: ADD COLUMN IF NOT EXISTS; CHECK drop-and-recreate guarded by
--              name lookup (re-run produces equivalent CHECK definition).
-- =============================================================================

BEGIN;

-- ───────────────────────────────────────────────────────────────────────
-- (a) origin_restricted column on bling_transactions
-- ───────────────────────────────────────────────────────────────────────
ALTER TABLE public.bling_transactions
  ADD COLUMN IF NOT EXISTS origin_restricted BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN public.bling_transactions.origin_restricted IS
  'Single-hop non-sellable marker per A4 v1.0 §9 / escrow-mechanics-v1 §8. '
  'When TRUE, the BLiNG! credited by this row is un-sellable on the order book '
  'until the receiving wallet transfers it out (first hop clears restriction).';

-- Partial index — only restricted rows matter for fast lookup
CREATE INDEX IF NOT EXISTS bling_transactions_origin_restricted_idx
  ON public.bling_transactions(bee_id, created_at)
  WHERE origin_restricted = TRUE;

-- ───────────────────────────────────────────────────────────────────────
-- (b) Extend bling_transactions.type CHECK to include escrow_in/escrow_unlock
-- ───────────────────────────────────────────────────────────────────────
-- Drop existing type-CHECK by predicate match (constraint name was auto-
-- generated by the original CREATE TABLE); recreate with extended ARRAY.
DO $$
DECLARE
  v_check_name text;
BEGIN
  SELECT conname INTO v_check_name
    FROM pg_constraint
   WHERE conrelid = 'public.bling_transactions'::regclass
     AND contype  = 'c'
     AND pg_get_constraintdef(oid) LIKE '%type =%'
   LIMIT 1;

  IF v_check_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.bling_transactions DROP CONSTRAINT %I', v_check_name);
    RAISE NOTICE 'Dropped existing type CHECK: %', v_check_name;
  ELSE
    RAISE NOTICE 'No existing type CHECK found — adding fresh.';
  END IF;
END $$;

ALTER TABLE public.bling_transactions
  ADD CONSTRAINT bling_transactions_type_check
  CHECK (type = ANY (ARRAY[
    'free',
    'send_debit', 'send_credit',
    'escrow_hold', 'escrow_release', 'escrow_cancel', 'escrow_dispute',
    'order_reserve', 'order_fill_debit', 'order_fill_credit',
    'order_cancel_refund', 'order_donation',
    'stripe_credit', 'chargeback',
    'escrow_in', 'escrow_unlock'              -- NEW (retirement + emergency_fund)
  ]));

-- ───────────────────────────────────────────────────────────────────────
-- Post-migration sanity assertions
-- ───────────────────────────────────────────────────────────────────────
DO $$
BEGIN
  ASSERT EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name   = 'bling_transactions'
       AND column_name  = 'origin_restricted'
       AND data_type    = 'boolean'
       AND is_nullable  = 'NO'
  ), 'origin_restricted column missing or misshapen';

  ASSERT EXISTS (
    SELECT 1 FROM pg_indexes
     WHERE schemaname = 'public'
       AND tablename  = 'bling_transactions'
       AND indexname  = 'bling_transactions_origin_restricted_idx'
  ), 'bling_transactions_origin_restricted_idx index missing';

  ASSERT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'public.bling_transactions'::regclass
       AND contype  = 'c'
       AND pg_get_constraintdef(oid) LIKE '%escrow_in%'
       AND pg_get_constraintdef(oid) LIKE '%escrow_unlock%'
  ), 'bling_transactions.type CHECK does not include escrow_in / escrow_unlock';

  RAISE NOTICE 'Migration 20260515000000 OK: origin_restricted + type CHECK extension verified.';
END $$;

COMMIT;
