-- Science dedup stage 1 (clean tier, B convention): consolidate duplicated subdisciplines into "Branches of X".
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Biology / Branches of biology / Botany';
UPDATE atoms SET path='Science / Biology / Branches of biology / Botany' || substring(path from length('Science / Biology / Botany')+1) WHERE realm_id='science' AND path LIKE 'Science / Biology / Botany%';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Biology / Branches of biology / Ecology';
UPDATE atoms SET path='Science / Biology / Branches of biology / Ecology' || substring(path from length('Science / Biology / Ecology')+1) WHERE realm_id='science' AND path LIKE 'Science / Biology / Ecology%';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Biology / Branches of biology / Taxonomy';
UPDATE atoms SET path='Science / Biology / Branches of biology / Taxonomy' || substring(path from length('Science / Biology / Taxonomy')+1) WHERE realm_id='science' AND path LIKE 'Science / Biology / Taxonomy%';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Chemistry / Branches of chemistry / Electrochemistry';
UPDATE atoms SET path='Science / Chemistry / Branches of chemistry / Electrochemistry' || substring(path from length('Science / Chemistry / Electrochemistry')+1) WHERE realm_id='science' AND path LIKE 'Science / Chemistry / Electrochemistry%';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Chemistry / Branches of chemistry / Organic chemistry';
UPDATE atoms SET path='Science / Chemistry / Branches of chemistry / Organic chemistry' || substring(path from length('Science / Chemistry / Organic chemistry')+1) WHERE realm_id='science' AND path LIKE 'Science / Chemistry / Organic chemistry%';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Physics / Branches of physics / Electromagnetism';
UPDATE atoms SET path='Science / Physics / Branches of physics / Electromagnetism' || substring(path from length('Science / Physics / Electromagnetism')+1) WHERE realm_id='science' AND path LIKE 'Science / Physics / Electromagnetism%';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Physics / Branches of physics / Nuclear physics';
UPDATE atoms SET path='Science / Physics / Branches of physics / Nuclear physics' || substring(path from length('Science / Physics / Nuclear physics')+1) WHERE realm_id='science' AND path LIKE 'Science / Physics / Nuclear physics%';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Physics / Branches of physics / Particle physics';
UPDATE atoms SET path='Science / Physics / Branches of physics / Particle physics' || substring(path from length('Science / Physics / Particle physics')+1) WHERE realm_id='science' AND path LIKE 'Science / Physics / Particle physics%';
UPDATE atoms SET path='Science / Chemistry / Branches of chemistry / Biochemistry' || substring(path from length('Science / Chemistry / Biochemistry')+1) WHERE realm_id='science' AND path LIKE 'Science / Chemistry / Biochemistry / %';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Chemistry / Biochemistry';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Biology / Branches of biology / Biochemistry';
UPDATE atoms SET path='Science / Physics / Branches of physics / Thermodynamics' || substring(path from length('Science / Chemistry / Thermodynamics')+1) WHERE realm_id='science' AND path LIKE 'Science / Chemistry / Thermodynamics / %';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Chemistry / Thermodynamics';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Physics / Physics concepts / Thermodynamics';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Astronomy and space science / Solar System / Meteor showers';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Astronomy and space science / Solar System / Asteroids / Trans-Neptunian objects';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Physics / Physics concepts / Standard Model';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Physics / Branches of physics / General relativity';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Physics / Branches of physics / Special relativity';
DELETE FROM atoms WHERE realm_id='science' AND path='Science / Physics / Branches of physics / Quantum mechanics';
UPDATE atoms SET path_parts=string_to_array(path,' / '), depth=cardinality(string_to_array(path,' / ')) WHERE realm_id='science';
