-- Self realm add-missing v1: Big Five + two thin-branch fills. 9 new L4 concept atoms.
INSERT INTO atoms (id,name,path,path_parts,realm_id,realm_name,depth,type,kettle,is_leaf,theme_tags,realm_tags,pillar_tags,skin_tags,geo,note,meta,canonical_url,canonical_source,band,status,created_at,updated_at) VALUES
('self-personality-traits-and-temperament-openness-to-experience','Openness to experience','Self / Personality / Traits & temperament / Openness to experience',ARRAY['Self','Personality','Traits & temperament','Openness to experience'],'self','Self',4,'concept','Accepted',true,ARRAY[]::text[],ARRAY['Self'],ARRAY['MANUAL'],ARRAY['HoneyComb'],null,null,'{}'::jsonb,null,null,null,'live',now(),now()),
('self-personality-traits-and-temperament-conscientiousness','Conscientiousness','Self / Personality / Traits & temperament / Conscientiousness',ARRAY['Self','Personality','Traits & temperament','Conscientiousness'],'self','Self',4,'concept','Accepted',true,ARRAY[]::text[],ARRAY['Self'],ARRAY['MANUAL'],ARRAY['HoneyComb'],null,null,'{}'::jsonb,null,null,null,'live',now(),now()),
('self-personality-traits-and-temperament-extraversion','Extraversion','Self / Personality / Traits & temperament / Extraversion',ARRAY['Self','Personality','Traits & temperament','Extraversion'],'self','Self',4,'concept','Accepted',true,ARRAY[]::text[],ARRAY['Self'],ARRAY['MANUAL'],ARRAY['HoneyComb'],null,null,'{}'::jsonb,null,null,null,'live',now(),now()),
('self-personality-traits-and-temperament-agreeableness','Agreeableness','Self / Personality / Traits & temperament / Agreeableness',ARRAY['Self','Personality','Traits & temperament','Agreeableness'],'self','Self',4,'concept','Accepted',true,ARRAY[]::text[],ARRAY['Self'],ARRAY['MANUAL'],ARRAY['HoneyComb'],null,null,'{}'::jsonb,null,null,null,'live',now(),now()),
('self-personality-traits-and-temperament-neuroticism','Neuroticism','Self / Personality / Traits & temperament / Neuroticism',ARRAY['Self','Personality','Traits & temperament','Neuroticism'],'self','Self',4,'concept','Accepted',true,ARRAY[]::text[],ARRAY['Self'],ARRAY['MANUAL'],ARRAY['HoneyComb'],null,null,'{}'::jsonb,null,null,null,'live',now(),now()),
('self-mind-and-thought-motivation-and-goals-intrinsic-motivation','Intrinsic motivation','Self / Mind & thought / Motivation & goals / Intrinsic motivation',ARRAY['Self','Mind & thought','Motivation & goals','Intrinsic motivation'],'self','Self',4,'concept','Accepted',true,ARRAY[]::text[],ARRAY['Self'],ARRAY['MANUAL'],ARRAY['HoneyComb'],null,null,'{}'::jsonb,null,null,null,'live',now(),now()),
('self-mind-and-thought-motivation-and-goals-extrinsic-motivation','Extrinsic motivation','Self / Mind & thought / Motivation & goals / Extrinsic motivation',ARRAY['Self','Mind & thought','Motivation & goals','Extrinsic motivation'],'self','Self',4,'concept','Accepted',true,ARRAY[]::text[],ARRAY['Self'],ARRAY['MANUAL'],ARRAY['HoneyComb'],null,null,'{}'::jsonb,null,null,null,'live',now(),now()),
('self-mind-and-thought-motivation-and-goals-drive','Drive','Self / Mind & thought / Motivation & goals / Drive',ARRAY['Self','Mind & thought','Motivation & goals','Drive'],'self','Self',4,'concept','Accepted',true,ARRAY[]::text[],ARRAY['Self'],ARRAY['MANUAL'],ARRAY['HoneyComb'],null,null,'{}'::jsonb,null,null,null,'live',now(),now()),
('self-mind-and-thought-consciousness','Consciousness','Self / Mind & thought / Foundations of mind / Consciousness',ARRAY['Self','Mind & thought','Foundations of mind','Consciousness'],'self','Self',4,'concept','Accepted',true,ARRAY[]::text[],ARRAY['Philosophy','Science','Self'],ARRAY['MANUAL'],ARRAY['HoneyComb'],null,null,'{}'::jsonb,null,null,null,'live',now(),now());
