-- APPLIED to prod 2026-06-14 via MCP. PARITY file.
-- Emotion & affect deep pass: add canonical missing members to each group.
INSERT INTO public.atoms (id,name,path,path_parts,realm_id,realm_name,depth,type,kettle,is_leaf,realm_tags,pillar_tags,skin_tags,status) VALUES
 ('self-emotion-affect-basic-emotions-contempt','Contempt','Self / Emotion & affect / Basic emotions / Contempt',ARRAY['Self','Emotion & affect','Basic emotions','Contempt']::text[],'self','Self',4,'event','Accepted',true,ARRAY['Self']::text[],ARRAY['MANUAL']::text[],ARRAY['HoneyComb']::text[],'live'),
 ('self-emotion-affect-social-and-moral-emotions-embarrassment','Embarrassment','Self / Emotion & affect / Social & moral emotions / Embarrassment',ARRAY['Self','Emotion & affect','Social & moral emotions','Embarrassment']::text[],'self','Self',4,'event','Accepted',true,ARRAY['Self']::text[],ARRAY['MANUAL']::text[],ARRAY['HoneyComb']::text[],'live'),
 ('self-emotion-affect-social-and-moral-emotions-jealousy','Jealousy','Self / Emotion & affect / Social & moral emotions / Jealousy',ARRAY['Self','Emotion & affect','Social & moral emotions','Jealousy']::text[],'self','Self',4,'event','Accepted',true,ARRAY['Self']::text[],ARRAY['MANUAL']::text[],ARRAY['HoneyComb']::text[],'live'),
 ('self-emotion-affect-social-and-moral-emotions-compassion','Compassion','Self / Emotion & affect / Social & moral emotions / Compassion',ARRAY['Self','Emotion & affect','Social & moral emotions','Compassion']::text[],'self','Self',4,'event','Accepted',true,ARRAY['Self']::text[],ARRAY['MANUAL']::text[],ARRAY['HoneyComb']::text[],'live'),
 ('self-emotion-affect-affective-states-and-moods-happiness','Happiness','Self / Emotion & affect / Affective states & moods / Happiness',ARRAY['Self','Emotion & affect','Affective states & moods','Happiness']::text[],'self','Self',4,'event','Accepted',true,ARRAY['Self']::text[],ARRAY['MANUAL']::text[],ARRAY['HoneyComb']::text[],'live'),
 ('self-emotion-affect-emotional-processes-coping','Coping','Self / Emotion & affect / Emotional processes / Coping',ARRAY['Self','Emotion & affect','Emotional processes','Coping']::text[],'self','Self',4,'event','Accepted',true,ARRAY['Self']::text[],ARRAY['MANUAL']::text[],ARRAY['HoneyComb']::text[],'live');
