-- Geography: neighborhood build-out batch 02b — Denver 18 · Atlanta 18 · Detroit 16 · Portland 18 (70 atoms).
-- Parent city atoms flip is_leaf=false. Completes batch 02 (02a: Phoenix/San Antonio/Dallas/Austin).
INSERT INTO public.atoms (id, name, path, path_parts, depth, realm_id, realm_name, type, kettle, band, status, is_leaf, pillar_tags, skin_tags, realm_tags, geo)
SELECT v.id, v.name, v.path, string_to_array(v.path,' / '), array_length(string_to_array(v.path,' / '),1),
       'geography','Geography','neighborhood','Accepted',NULL,'live', true,
       ARRAY['MANUAL'], ARRAY['HoneyComb'], ARRAY['Geography'],
       jsonb_build_object('type','neighborhood','regionName',v.name,
         'parentCity',(string_to_array(v.path,' / '))[array_length(string_to_array(v.path,' / '),1)-1],
         'parentRegion',(string_to_array(v.path,' / '))[5],
         'parentCountry','US')
FROM (VALUES
  ('geo-us-den-downtown','Downtown','Geography / Countries / North America / United States / Colorado / Denver / Downtown'),
  ('geo-us-den-lodo','LoDo','Geography / Countries / North America / United States / Colorado / Denver / LoDo'),
  ('geo-us-den-rino','RiNo','Geography / Countries / North America / United States / Colorado / Denver / RiNo'),
  ('geo-us-den-capitol-hill','Capitol Hill','Geography / Countries / North America / United States / Colorado / Denver / Capitol Hill'),
  ('geo-us-den-five-points','Five Points','Geography / Countries / North America / United States / Colorado / Denver / Five Points'),
  ('geo-us-den-highland','Highland','Geography / Countries / North America / United States / Colorado / Denver / Highland'),
  ('geo-us-den-cherry-creek','Cherry Creek','Geography / Countries / North America / United States / Colorado / Denver / Cherry Creek'),
  ('geo-us-den-washington-park','Washington Park','Geography / Countries / North America / United States / Colorado / Denver / Washington Park'),
  ('geo-us-den-baker','Baker','Geography / Countries / North America / United States / Colorado / Denver / Baker'),
  ('geo-us-den-city-park','City Park','Geography / Countries / North America / United States / Colorado / Denver / City Park'),
  ('geo-us-den-congress-park','Congress Park','Geography / Countries / North America / United States / Colorado / Denver / Congress Park'),
  ('geo-us-den-park-hill','Park Hill','Geography / Countries / North America / United States / Colorado / Denver / Park Hill'),
  ('geo-us-den-central-park','Central Park','Geography / Countries / North America / United States / Colorado / Denver / Central Park'),
  ('geo-us-den-sunnyside','Sunnyside','Geography / Countries / North America / United States / Colorado / Denver / Sunnyside'),
  ('geo-us-den-berkeley','Berkeley','Geography / Countries / North America / United States / Colorado / Denver / Berkeley'),
  ('geo-us-den-sloans-lake','Sloan''s Lake','Geography / Countries / North America / United States / Colorado / Denver / Sloan''s Lake'),
  ('geo-us-den-uptown','Uptown','Geography / Countries / North America / United States / Colorado / Denver / Uptown'),
  ('geo-us-den-golden-triangle','Golden Triangle','Geography / Countries / North America / United States / Colorado / Denver / Golden Triangle'),
  ('geo-us-atl-downtown','Downtown','Geography / Countries / North America / United States / Georgia / Atlanta / Downtown'),
  ('geo-us-atl-midtown','Midtown','Geography / Countries / North America / United States / Georgia / Atlanta / Midtown'),
  ('geo-us-atl-buckhead','Buckhead','Geography / Countries / North America / United States / Georgia / Atlanta / Buckhead'),
  ('geo-us-atl-old-fourth-ward','Old Fourth Ward','Geography / Countries / North America / United States / Georgia / Atlanta / Old Fourth Ward'),
  ('geo-us-atl-inman-park','Inman Park','Geography / Countries / North America / United States / Georgia / Atlanta / Inman Park'),
  ('geo-us-atl-virginia-highland','Virginia-Highland','Geography / Countries / North America / United States / Georgia / Atlanta / Virginia-Highland'),
  ('geo-us-atl-little-five-points','Little Five Points','Geography / Countries / North America / United States / Georgia / Atlanta / Little Five Points'),
  ('geo-us-atl-east-atlanta-village','East Atlanta Village','Geography / Countries / North America / United States / Georgia / Atlanta / East Atlanta Village'),
  ('geo-us-atl-grant-park','Grant Park','Geography / Countries / North America / United States / Georgia / Atlanta / Grant Park'),
  ('geo-us-atl-cabbagetown','Cabbagetown','Geography / Countries / North America / United States / Georgia / Atlanta / Cabbagetown'),
  ('geo-us-atl-poncey-highland','Poncey-Highland','Geography / Countries / North America / United States / Georgia / Atlanta / Poncey-Highland'),
  ('geo-us-atl-west-end','West End','Geography / Countries / North America / United States / Georgia / Atlanta / West End'),
  ('geo-us-atl-castleberry-hill','Castleberry Hill','Geography / Countries / North America / United States / Georgia / Atlanta / Castleberry Hill'),
  ('geo-us-atl-kirkwood','Kirkwood','Geography / Countries / North America / United States / Georgia / Atlanta / Kirkwood'),
  ('geo-us-atl-edgewood','Edgewood','Geography / Countries / North America / United States / Georgia / Atlanta / Edgewood'),
  ('geo-us-atl-summerhill','Summerhill','Geography / Countries / North America / United States / Georgia / Atlanta / Summerhill'),
  ('geo-us-atl-vine-city','Vine City','Geography / Countries / North America / United States / Georgia / Atlanta / Vine City'),
  ('geo-us-atl-west-midtown','West Midtown','Geography / Countries / North America / United States / Georgia / Atlanta / West Midtown'),
  ('geo-us-det-downtown','Downtown','Geography / Countries / North America / United States / Michigan / Detroit / Downtown'),
  ('geo-us-det-midtown','Midtown','Geography / Countries / North America / United States / Michigan / Detroit / Midtown'),
  ('geo-us-det-corktown','Corktown','Geography / Countries / North America / United States / Michigan / Detroit / Corktown'),
  ('geo-us-det-eastern-market','Eastern Market','Geography / Countries / North America / United States / Michigan / Detroit / Eastern Market'),
  ('geo-us-det-new-center','New Center','Geography / Countries / North America / United States / Michigan / Detroit / New Center'),
  ('geo-us-det-greektown','Greektown','Geography / Countries / North America / United States / Michigan / Detroit / Greektown'),
  ('geo-us-det-mexicantown','Mexicantown','Geography / Countries / North America / United States / Michigan / Detroit / Mexicantown'),
  ('geo-us-det-rivertown','Rivertown','Geography / Countries / North America / United States / Michigan / Detroit / Rivertown'),
  ('geo-us-det-boston-edison','Boston-Edison','Geography / Countries / North America / United States / Michigan / Detroit / Boston-Edison'),
  ('geo-us-det-indian-village','Indian Village','Geography / Countries / North America / United States / Michigan / Detroit / Indian Village'),
  ('geo-us-det-palmer-woods','Palmer Woods','Geography / Countries / North America / United States / Michigan / Detroit / Palmer Woods'),
  ('geo-us-det-university-district','University District','Geography / Countries / North America / United States / Michigan / Detroit / University District'),
  ('geo-us-det-jefferson-chalmers','Jefferson Chalmers','Geography / Countries / North America / United States / Michigan / Detroit / Jefferson Chalmers'),
  ('geo-us-det-brush-park','Brush Park','Geography / Countries / North America / United States / Michigan / Detroit / Brush Park'),
  ('geo-us-det-woodbridge','Woodbridge','Geography / Countries / North America / United States / Michigan / Detroit / Woodbridge'),
  ('geo-us-det-southwest-detroit','Southwest Detroit','Geography / Countries / North America / United States / Michigan / Detroit / Southwest Detroit'),
  ('geo-us-pdx-downtown','Downtown','Geography / Countries / North America / United States / Oregon / Portland / Downtown'),
  ('geo-us-pdx-pearl-district','Pearl District','Geography / Countries / North America / United States / Oregon / Portland / Pearl District'),
  ('geo-us-pdx-old-town','Old Town','Geography / Countries / North America / United States / Oregon / Portland / Old Town'),
  ('geo-us-pdx-northwest-district','Northwest District','Geography / Countries / North America / United States / Oregon / Portland / Northwest District'),
  ('geo-us-pdx-goose-hollow','Goose Hollow','Geography / Countries / North America / United States / Oregon / Portland / Goose Hollow'),
  ('geo-us-pdx-hawthorne','Hawthorne','Geography / Countries / North America / United States / Oregon / Portland / Hawthorne'),
  ('geo-us-pdx-sunnyside','Sunnyside','Geography / Countries / North America / United States / Oregon / Portland / Sunnyside'),
  ('geo-us-pdx-richmond','Richmond','Geography / Countries / North America / United States / Oregon / Portland / Richmond'),
  ('geo-us-pdx-alberta-arts-district','Alberta Arts District','Geography / Countries / North America / United States / Oregon / Portland / Alberta Arts District'),
  ('geo-us-pdx-boise','Boise','Geography / Countries / North America / United States / Oregon / Portland / Boise'),
  ('geo-us-pdx-overlook','Overlook','Geography / Countries / North America / United States / Oregon / Portland / Overlook'),
  ('geo-us-pdx-sellwood-moreland','Sellwood-Moreland','Geography / Countries / North America / United States / Oregon / Portland / Sellwood-Moreland'),
  ('geo-us-pdx-st-johns','St. Johns','Geography / Countries / North America / United States / Oregon / Portland / St. Johns'),
  ('geo-us-pdx-laurelhurst','Laurelhurst','Geography / Countries / North America / United States / Oregon / Portland / Laurelhurst'),
  ('geo-us-pdx-irvington','Irvington','Geography / Countries / North America / United States / Oregon / Portland / Irvington'),
  ('geo-us-pdx-hollywood','Hollywood','Geography / Countries / North America / United States / Oregon / Portland / Hollywood'),
  ('geo-us-pdx-kenton','Kenton','Geography / Countries / North America / United States / Oregon / Portland / Kenton'),
  ('geo-us-pdx-montavilla','Montavilla','Geography / Countries / North America / United States / Oregon / Portland / Montavilla')
) AS v(id, name, path);

UPDATE public.atoms SET is_leaf = false
WHERE id IN ('geo-us-city-denver','geo-us-city-atlanta','geo-us-city-detroit','geo-us-city-portland-or');
