-- Geography: neighborhood build-out batch 04b — Louisville 16 · Kansas City 16 · St. Louis 18 · Minneapolis 16 (66 atoms).
-- Parent city atoms flip is_leaf=false. Completes batch 04 (04a: Memphis/Baltimore/Milwaukee/Oklahoma City).
INSERT INTO public.atoms (id, name, path, path_parts, depth, realm_id, realm_name, type, kettle, band, status, is_leaf, pillar_tags, skin_tags, realm_tags, geo)
SELECT v.id, v.name, v.path, string_to_array(v.path,' / '), array_length(string_to_array(v.path,' / '),1),
       'geography','Geography','neighborhood','Accepted',NULL,'live', true,
       ARRAY['MANUAL'], ARRAY['HoneyComb'], ARRAY['Geography'],
       jsonb_build_object('type','neighborhood','regionName',v.name,
         'parentCity',(string_to_array(v.path,' / '))[array_length(string_to_array(v.path,' / '),1)-1],
         'parentRegion',(string_to_array(v.path,' / '))[5],
         'parentCountry','US')
FROM (VALUES
  ('geo-us-lou-downtown','Downtown','Geography / Countries / North America / United States / Kentucky / Louisville / Downtown'),
  ('geo-us-lou-nulu','NuLu','Geography / Countries / North America / United States / Kentucky / Louisville / NuLu'),
  ('geo-us-lou-old-louisville','Old Louisville','Geography / Countries / North America / United States / Kentucky / Louisville / Old Louisville'),
  ('geo-us-lou-the-highlands','The Highlands','Geography / Countries / North America / United States / Kentucky / Louisville / The Highlands'),
  ('geo-us-lou-cherokee-triangle','Cherokee Triangle','Geography / Countries / North America / United States / Kentucky / Louisville / Cherokee Triangle'),
  ('geo-us-lou-germantown','Germantown','Geography / Countries / North America / United States / Kentucky / Louisville / Germantown'),
  ('geo-us-lou-clifton','Clifton','Geography / Countries / North America / United States / Kentucky / Louisville / Clifton'),
  ('geo-us-lou-crescent-hill','Crescent Hill','Geography / Countries / North America / United States / Kentucky / Louisville / Crescent Hill'),
  ('geo-us-lou-butchertown','Butchertown','Geography / Countries / North America / United States / Kentucky / Louisville / Butchertown'),
  ('geo-us-lou-portland','Portland','Geography / Countries / North America / United States / Kentucky / Louisville / Portland'),
  ('geo-us-lou-russell','Russell','Geography / Countries / North America / United States / Kentucky / Louisville / Russell'),
  ('geo-us-lou-shawnee','Shawnee','Geography / Countries / North America / United States / Kentucky / Louisville / Shawnee'),
  ('geo-us-lou-smoketown','Smoketown','Geography / Countries / North America / United States / Kentucky / Louisville / Smoketown'),
  ('geo-us-lou-shelby-park','Shelby Park','Geography / Countries / North America / United States / Kentucky / Louisville / Shelby Park'),
  ('geo-us-lou-phoenix-hill','Phoenix Hill','Geography / Countries / North America / United States / Kentucky / Louisville / Phoenix Hill'),
  ('geo-us-lou-iroquois','Iroquois','Geography / Countries / North America / United States / Kentucky / Louisville / Iroquois'),
  ('geo-us-kcm-downtown','Downtown','Geography / Countries / North America / United States / Missouri / Kansas City / Downtown'),
  ('geo-us-kcm-river-market','River Market','Geography / Countries / North America / United States / Missouri / Kansas City / River Market'),
  ('geo-us-kcm-crossroads-arts-district','Crossroads Arts District','Geography / Countries / North America / United States / Missouri / Kansas City / Crossroads Arts District'),
  ('geo-us-kcm-power-and-light-district','Power & Light District','Geography / Countries / North America / United States / Missouri / Kansas City / Power & Light District'),
  ('geo-us-kcm-westport','Westport','Geography / Countries / North America / United States / Missouri / Kansas City / Westport'),
  ('geo-us-kcm-country-club-plaza','Country Club Plaza','Geography / Countries / North America / United States / Missouri / Kansas City / Country Club Plaza'),
  ('geo-us-kcm-brookside','Brookside','Geography / Countries / North America / United States / Missouri / Kansas City / Brookside'),
  ('geo-us-kcm-waldo','Waldo','Geography / Countries / North America / United States / Missouri / Kansas City / Waldo'),
  ('geo-us-kcm-west-bottoms','West Bottoms','Geography / Countries / North America / United States / Missouri / Kansas City / West Bottoms'),
  ('geo-us-kcm-crown-center','Crown Center','Geography / Countries / North America / United States / Missouri / Kansas City / Crown Center'),
  ('geo-us-kcm-hyde-park','Hyde Park','Geography / Countries / North America / United States / Missouri / Kansas City / Hyde Park'),
  ('geo-us-kcm-midtown','Midtown','Geography / Countries / North America / United States / Missouri / Kansas City / Midtown'),
  ('geo-us-kcm-18th-and-vine','18th & Vine','Geography / Countries / North America / United States / Missouri / Kansas City / 18th & Vine'),
  ('geo-us-kcm-historic-northeast','Historic Northeast','Geography / Countries / North America / United States / Missouri / Kansas City / Historic Northeast'),
  ('geo-us-kcm-union-hill','Union Hill','Geography / Countries / North America / United States / Missouri / Kansas City / Union Hill'),
  ('geo-us-kcm-quality-hill','Quality Hill','Geography / Countries / North America / United States / Missouri / Kansas City / Quality Hill'),
  ('geo-us-stl-downtown','Downtown','Geography / Countries / North America / United States / Missouri / St. Louis / Downtown'),
  ('geo-us-stl-soulard','Soulard','Geography / Countries / North America / United States / Missouri / St. Louis / Soulard'),
  ('geo-us-stl-lafayette-square','Lafayette Square','Geography / Countries / North America / United States / Missouri / St. Louis / Lafayette Square'),
  ('geo-us-stl-the-hill','The Hill','Geography / Countries / North America / United States / Missouri / St. Louis / The Hill'),
  ('geo-us-stl-central-west-end','Central West End','Geography / Countries / North America / United States / Missouri / St. Louis / Central West End'),
  ('geo-us-stl-shaw','Shaw','Geography / Countries / North America / United States / Missouri / St. Louis / Shaw'),
  ('geo-us-stl-tower-grove-south','Tower Grove South','Geography / Countries / North America / United States / Missouri / St. Louis / Tower Grove South'),
  ('geo-us-stl-tower-grove-east','Tower Grove East','Geography / Countries / North America / United States / Missouri / St. Louis / Tower Grove East'),
  ('geo-us-stl-benton-park','Benton Park','Geography / Countries / North America / United States / Missouri / St. Louis / Benton Park'),
  ('geo-us-stl-the-grove','The Grove','Geography / Countries / North America / United States / Missouri / St. Louis / The Grove'),
  ('geo-us-stl-dogtown','Dogtown','Geography / Countries / North America / United States / Missouri / St. Louis / Dogtown'),
  ('geo-us-stl-dutchtown','Dutchtown','Geography / Countries / North America / United States / Missouri / St. Louis / Dutchtown'),
  ('geo-us-stl-old-north-st-louis','Old North St. Louis','Geography / Countries / North America / United States / Missouri / St. Louis / Old North St. Louis'),
  ('geo-us-stl-carondelet','Carondelet','Geography / Countries / North America / United States / Missouri / St. Louis / Carondelet'),
  ('geo-us-stl-bevo-mill','Bevo Mill','Geography / Countries / North America / United States / Missouri / St. Louis / Bevo Mill'),
  ('geo-us-stl-skinker-debaliviere','Skinker DeBaliviere','Geography / Countries / North America / United States / Missouri / St. Louis / Skinker DeBaliviere'),
  ('geo-us-stl-compton-heights','Compton Heights','Geography / Countries / North America / United States / Missouri / St. Louis / Compton Heights'),
  ('geo-us-stl-midtown','Midtown','Geography / Countries / North America / United States / Missouri / St. Louis / Midtown'),
  ('geo-us-msp-downtown','Downtown','Geography / Countries / North America / United States / Minnesota / Minneapolis / Downtown'),
  ('geo-us-msp-north-loop','North Loop','Geography / Countries / North America / United States / Minnesota / Minneapolis / North Loop'),
  ('geo-us-msp-northeast','Northeast','Geography / Countries / North America / United States / Minnesota / Minneapolis / Northeast'),
  ('geo-us-msp-uptown','Uptown','Geography / Countries / North America / United States / Minnesota / Minneapolis / Uptown'),
  ('geo-us-msp-dinkytown','Dinkytown','Geography / Countries / North America / United States / Minnesota / Minneapolis / Dinkytown'),
  ('geo-us-msp-loring-park','Loring Park','Geography / Countries / North America / United States / Minnesota / Minneapolis / Loring Park'),
  ('geo-us-msp-whittier','Whittier','Geography / Countries / North America / United States / Minnesota / Minneapolis / Whittier'),
  ('geo-us-msp-powderhorn','Powderhorn','Geography / Countries / North America / United States / Minnesota / Minneapolis / Powderhorn'),
  ('geo-us-msp-longfellow','Longfellow','Geography / Countries / North America / United States / Minnesota / Minneapolis / Longfellow'),
  ('geo-us-msp-seward','Seward','Geography / Countries / North America / United States / Minnesota / Minneapolis / Seward'),
  ('geo-us-msp-linden-hills','Linden Hills','Geography / Countries / North America / United States / Minnesota / Minneapolis / Linden Hills'),
  ('geo-us-msp-kingfield','Kingfield','Geography / Countries / North America / United States / Minnesota / Minneapolis / Kingfield'),
  ('geo-us-msp-tangletown','Tangletown','Geography / Countries / North America / United States / Minnesota / Minneapolis / Tangletown'),
  ('geo-us-msp-prospect-park','Prospect Park','Geography / Countries / North America / United States / Minnesota / Minneapolis / Prospect Park'),
  ('geo-us-msp-camden','Camden','Geography / Countries / North America / United States / Minnesota / Minneapolis / Camden'),
  ('geo-us-msp-phillips','Phillips','Geography / Countries / North America / United States / Minnesota / Minneapolis / Phillips')
) AS v(id, name, path);

UPDATE public.atoms SET is_leaf = false
WHERE id IN ('geo-us-city-louisville-ky','geo-us-city-kansas-city-mo','geo-us-city-st-louis-mo','geo-us-city-minneapolis-mn');
