-- Geography: neighborhood build-out batch 01 — 8 US cities, 163 atoms.
-- Applied to prod 2026-07-02 as version 20260702205621.
-- Houston 17 · Philadelphia 20 · San Francisco 24 · Boston 21 · Washington D.C. 20 (depth 6; DC sits at state slot)
-- Seattle 25 · Miami 15 · San Diego 21. Parent city atoms flip is_leaf=false.
INSERT INTO public.atoms (id, name, path, path_parts, depth, realm_id, realm_name, type, kettle, band, status, is_leaf, pillar_tags, skin_tags, realm_tags, geo)
SELECT v.id, v.name, v.path, string_to_array(v.path,' / '), array_length(string_to_array(v.path,' / '),1),
       'geography','Geography','neighborhood','Accepted',NULL,'live', true,
       ARRAY['MANUAL'], ARRAY['HoneyComb'], ARRAY['Geography'],
       jsonb_build_object('type','neighborhood','regionName',v.name,
         'parentCity',(string_to_array(v.path,' / '))[array_length(string_to_array(v.path,' / '),1)-1],
         'parentRegion',(string_to_array(v.path,' / '))[5],
         'parentCountry','US')
FROM (VALUES
  ('geo-us-hou-downtown','Downtown','Geography / Countries / North America / United States / Texas / Houston / Downtown'),
  ('geo-us-hou-midtown','Midtown','Geography / Countries / North America / United States / Texas / Houston / Midtown'),
  ('geo-us-hou-montrose','Montrose','Geography / Countries / North America / United States / Texas / Houston / Montrose'),
  ('geo-us-hou-the-heights','The Heights','Geography / Countries / North America / United States / Texas / Houston / The Heights'),
  ('geo-us-hou-river-oaks','River Oaks','Geography / Countries / North America / United States / Texas / Houston / River Oaks'),
  ('geo-us-hou-museum-district','Museum District','Geography / Countries / North America / United States / Texas / Houston / Museum District'),
  ('geo-us-hou-texas-medical-center','Texas Medical Center','Geography / Countries / North America / United States / Texas / Houston / Texas Medical Center'),
  ('geo-us-hou-eado','EaDo','Geography / Countries / North America / United States / Texas / Houston / EaDo'),
  ('geo-us-hou-third-ward','Third Ward','Geography / Countries / North America / United States / Texas / Houston / Third Ward'),
  ('geo-us-hou-fifth-ward','Fifth Ward','Geography / Countries / North America / United States / Texas / Houston / Fifth Ward'),
  ('geo-us-hou-second-ward','Second Ward','Geography / Countries / North America / United States / Texas / Houston / Second Ward'),
  ('geo-us-hou-uptown','Uptown','Geography / Countries / North America / United States / Texas / Houston / Uptown'),
  ('geo-us-hou-memorial','Memorial','Geography / Countries / North America / United States / Texas / Houston / Memorial'),
  ('geo-us-hou-sharpstown','Sharpstown','Geography / Countries / North America / United States / Texas / Houston / Sharpstown'),
  ('geo-us-hou-westchase','Westchase','Geography / Countries / North America / United States / Texas / Houston / Westchase'),
  ('geo-us-hou-clear-lake','Clear Lake','Geography / Countries / North America / United States / Texas / Houston / Clear Lake'),
  ('geo-us-hou-kingwood','Kingwood','Geography / Countries / North America / United States / Texas / Houston / Kingwood'),
  ('geo-us-phl-center-city','Center City','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Center City'),
  ('geo-us-phl-old-city','Old City','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Old City'),
  ('geo-us-phl-society-hill','Society Hill','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Society Hill'),
  ('geo-us-phl-rittenhouse-square','Rittenhouse Square','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Rittenhouse Square'),
  ('geo-us-phl-queen-village','Queen Village','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Queen Village'),
  ('geo-us-phl-bella-vista','Bella Vista','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Bella Vista'),
  ('geo-us-phl-east-passyunk','East Passyunk','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / East Passyunk'),
  ('geo-us-phl-south-philadelphia','South Philadelphia','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / South Philadelphia'),
  ('geo-us-phl-fishtown','Fishtown','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Fishtown'),
  ('geo-us-phl-northern-liberties','Northern Liberties','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Northern Liberties'),
  ('geo-us-phl-kensington','Kensington','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Kensington'),
  ('geo-us-phl-port-richmond','Port Richmond','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Port Richmond'),
  ('geo-us-phl-fairmount','Fairmount','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Fairmount'),
  ('geo-us-phl-manayunk','Manayunk','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Manayunk'),
  ('geo-us-phl-roxborough','Roxborough','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Roxborough'),
  ('geo-us-phl-chestnut-hill','Chestnut Hill','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Chestnut Hill'),
  ('geo-us-phl-mount-airy','Mount Airy','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Mount Airy'),
  ('geo-us-phl-germantown','Germantown','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / Germantown'),
  ('geo-us-phl-university-city','University City','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / University City'),
  ('geo-us-phl-west-philadelphia','West Philadelphia','Geography / Countries / North America / United States / Pennsylvania / Philadelphia / West Philadelphia'),
  ('geo-us-sf-mission-district','Mission District','Geography / Countries / North America / United States / California / San Francisco / Mission District'),
  ('geo-us-sf-the-castro','The Castro','Geography / Countries / North America / United States / California / San Francisco / The Castro'),
  ('geo-us-sf-haight-ashbury','Haight-Ashbury','Geography / Countries / North America / United States / California / San Francisco / Haight-Ashbury'),
  ('geo-us-sf-nob-hill','Nob Hill','Geography / Countries / North America / United States / California / San Francisco / Nob Hill'),
  ('geo-us-sf-russian-hill','Russian Hill','Geography / Countries / North America / United States / California / San Francisco / Russian Hill'),
  ('geo-us-sf-north-beach','North Beach','Geography / Countries / North America / United States / California / San Francisco / North Beach'),
  ('geo-us-sf-chinatown','Chinatown','Geography / Countries / North America / United States / California / San Francisco / Chinatown'),
  ('geo-us-sf-financial-district','Financial District','Geography / Countries / North America / United States / California / San Francisco / Financial District'),
  ('geo-us-sf-soma','SoMa','Geography / Countries / North America / United States / California / San Francisco / SoMa'),
  ('geo-us-sf-tenderloin','Tenderloin','Geography / Countries / North America / United States / California / San Francisco / Tenderloin'),
  ('geo-us-sf-pacific-heights','Pacific Heights','Geography / Countries / North America / United States / California / San Francisco / Pacific Heights'),
  ('geo-us-sf-marina-district','Marina District','Geography / Countries / North America / United States / California / San Francisco / Marina District'),
  ('geo-us-sf-richmond-district','Richmond District','Geography / Countries / North America / United States / California / San Francisco / Richmond District'),
  ('geo-us-sf-sunset-district','Sunset District','Geography / Countries / North America / United States / California / San Francisco / Sunset District'),
  ('geo-us-sf-noe-valley','Noe Valley','Geography / Countries / North America / United States / California / San Francisco / Noe Valley'),
  ('geo-us-sf-bernal-heights','Bernal Heights','Geography / Countries / North America / United States / California / San Francisco / Bernal Heights'),
  ('geo-us-sf-potrero-hill','Potrero Hill','Geography / Countries / North America / United States / California / San Francisco / Potrero Hill'),
  ('geo-us-sf-dogpatch','Dogpatch','Geography / Countries / North America / United States / California / San Francisco / Dogpatch'),
  ('geo-us-sf-hayes-valley','Hayes Valley','Geography / Countries / North America / United States / California / San Francisco / Hayes Valley'),
  ('geo-us-sf-fillmore','Fillmore','Geography / Countries / North America / United States / California / San Francisco / Fillmore'),
  ('geo-us-sf-japantown','Japantown','Geography / Countries / North America / United States / California / San Francisco / Japantown'),
  ('geo-us-sf-excelsior','Excelsior','Geography / Countries / North America / United States / California / San Francisco / Excelsior'),
  ('geo-us-sf-bayview-hunters-point','Bayview-Hunters Point','Geography / Countries / North America / United States / California / San Francisco / Bayview-Hunters Point'),
  ('geo-us-sf-glen-park','Glen Park','Geography / Countries / North America / United States / California / San Francisco / Glen Park'),
  ('geo-us-bos-back-bay','Back Bay','Geography / Countries / North America / United States / Massachusetts / Boston / Back Bay'),
  ('geo-us-bos-beacon-hill','Beacon Hill','Geography / Countries / North America / United States / Massachusetts / Boston / Beacon Hill'),
  ('geo-us-bos-north-end','North End','Geography / Countries / North America / United States / Massachusetts / Boston / North End'),
  ('geo-us-bos-west-end','West End','Geography / Countries / North America / United States / Massachusetts / Boston / West End'),
  ('geo-us-bos-south-end','South End','Geography / Countries / North America / United States / Massachusetts / Boston / South End'),
  ('geo-us-bos-south-boston','South Boston','Geography / Countries / North America / United States / Massachusetts / Boston / South Boston'),
  ('geo-us-bos-east-boston','East Boston','Geography / Countries / North America / United States / Massachusetts / Boston / East Boston'),
  ('geo-us-bos-charlestown','Charlestown','Geography / Countries / North America / United States / Massachusetts / Boston / Charlestown'),
  ('geo-us-bos-fenway','Fenway','Geography / Countries / North America / United States / Massachusetts / Boston / Fenway'),
  ('geo-us-bos-jamaica-plain','Jamaica Plain','Geography / Countries / North America / United States / Massachusetts / Boston / Jamaica Plain'),
  ('geo-us-bos-mission-hill','Mission Hill','Geography / Countries / North America / United States / Massachusetts / Boston / Mission Hill'),
  ('geo-us-bos-roxbury','Roxbury','Geography / Countries / North America / United States / Massachusetts / Boston / Roxbury'),
  ('geo-us-bos-dorchester','Dorchester','Geography / Countries / North America / United States / Massachusetts / Boston / Dorchester'),
  ('geo-us-bos-mattapan','Mattapan','Geography / Countries / North America / United States / Massachusetts / Boston / Mattapan'),
  ('geo-us-bos-hyde-park','Hyde Park','Geography / Countries / North America / United States / Massachusetts / Boston / Hyde Park'),
  ('geo-us-bos-roslindale','Roslindale','Geography / Countries / North America / United States / Massachusetts / Boston / Roslindale'),
  ('geo-us-bos-west-roxbury','West Roxbury','Geography / Countries / North America / United States / Massachusetts / Boston / West Roxbury'),
  ('geo-us-bos-allston','Allston','Geography / Countries / North America / United States / Massachusetts / Boston / Allston'),
  ('geo-us-bos-brighton','Brighton','Geography / Countries / North America / United States / Massachusetts / Boston / Brighton'),
  ('geo-us-bos-seaport','Seaport','Geography / Countries / North America / United States / Massachusetts / Boston / Seaport'),
  ('geo-us-bos-downtown','Downtown','Geography / Countries / North America / United States / Massachusetts / Boston / Downtown'),
  ('geo-us-dc-georgetown','Georgetown','Geography / Countries / North America / United States / Washington, D.C. / Georgetown'),
  ('geo-us-dc-dupont-circle','Dupont Circle','Geography / Countries / North America / United States / Washington, D.C. / Dupont Circle'),
  ('geo-us-dc-adams-morgan','Adams Morgan','Geography / Countries / North America / United States / Washington, D.C. / Adams Morgan'),
  ('geo-us-dc-capitol-hill','Capitol Hill','Geography / Countries / North America / United States / Washington, D.C. / Capitol Hill'),
  ('geo-us-dc-foggy-bottom','Foggy Bottom','Geography / Countries / North America / United States / Washington, D.C. / Foggy Bottom'),
  ('geo-us-dc-shaw','Shaw','Geography / Countries / North America / United States / Washington, D.C. / Shaw'),
  ('geo-us-dc-u-street-corridor','U Street Corridor','Geography / Countries / North America / United States / Washington, D.C. / U Street Corridor'),
  ('geo-us-dc-columbia-heights','Columbia Heights','Geography / Countries / North America / United States / Washington, D.C. / Columbia Heights'),
  ('geo-us-dc-petworth','Petworth','Geography / Countries / North America / United States / Washington, D.C. / Petworth'),
  ('geo-us-dc-anacostia','Anacostia','Geography / Countries / North America / United States / Washington, D.C. / Anacostia'),
  ('geo-us-dc-navy-yard','Navy Yard','Geography / Countries / North America / United States / Washington, D.C. / Navy Yard'),
  ('geo-us-dc-noma','NoMa','Geography / Countries / North America / United States / Washington, D.C. / NoMa'),
  ('geo-us-dc-logan-circle','Logan Circle','Geography / Countries / North America / United States / Washington, D.C. / Logan Circle'),
  ('geo-us-dc-brookland','Brookland','Geography / Countries / North America / United States / Washington, D.C. / Brookland'),
  ('geo-us-dc-tenleytown','Tenleytown','Geography / Countries / North America / United States / Washington, D.C. / Tenleytown'),
  ('geo-us-dc-cleveland-park','Cleveland Park','Geography / Countries / North America / United States / Washington, D.C. / Cleveland Park'),
  ('geo-us-dc-woodley-park','Woodley Park','Geography / Countries / North America / United States / Washington, D.C. / Woodley Park'),
  ('geo-us-dc-penn-quarter','Penn Quarter','Geography / Countries / North America / United States / Washington, D.C. / Penn Quarter'),
  ('geo-us-dc-chinatown','Chinatown','Geography / Countries / North America / United States / Washington, D.C. / Chinatown'),
  ('geo-us-dc-h-street-corridor','H Street Corridor','Geography / Countries / North America / United States / Washington, D.C. / H Street Corridor'),
  ('geo-us-sea-downtown','Downtown','Geography / Countries / North America / United States / Washington / Seattle / Downtown'),
  ('geo-us-sea-pioneer-square','Pioneer Square','Geography / Countries / North America / United States / Washington / Seattle / Pioneer Square'),
  ('geo-us-sea-belltown','Belltown','Geography / Countries / North America / United States / Washington / Seattle / Belltown'),
  ('geo-us-sea-south-lake-union','South Lake Union','Geography / Countries / North America / United States / Washington / Seattle / South Lake Union'),
  ('geo-us-sea-capitol-hill','Capitol Hill','Geography / Countries / North America / United States / Washington / Seattle / Capitol Hill'),
  ('geo-us-sea-first-hill','First Hill','Geography / Countries / North America / United States / Washington / Seattle / First Hill'),
  ('geo-us-sea-queen-anne','Queen Anne','Geography / Countries / North America / United States / Washington / Seattle / Queen Anne'),
  ('geo-us-sea-ballard','Ballard','Geography / Countries / North America / United States / Washington / Seattle / Ballard'),
  ('geo-us-sea-fremont','Fremont','Geography / Countries / North America / United States / Washington / Seattle / Fremont'),
  ('geo-us-sea-wallingford','Wallingford','Geography / Countries / North America / United States / Washington / Seattle / Wallingford'),
  ('geo-us-sea-green-lake','Green Lake','Geography / Countries / North America / United States / Washington / Seattle / Green Lake'),
  ('geo-us-sea-greenwood','Greenwood','Geography / Countries / North America / United States / Washington / Seattle / Greenwood'),
  ('geo-us-sea-phinney-ridge','Phinney Ridge','Geography / Countries / North America / United States / Washington / Seattle / Phinney Ridge'),
  ('geo-us-sea-university-district','University District','Geography / Countries / North America / United States / Washington / Seattle / University District'),
  ('geo-us-sea-ravenna','Ravenna','Geography / Countries / North America / United States / Washington / Seattle / Ravenna'),
  ('geo-us-sea-laurelhurst','Laurelhurst','Geography / Countries / North America / United States / Washington / Seattle / Laurelhurst'),
  ('geo-us-sea-magnolia','Magnolia','Geography / Countries / North America / United States / Washington / Seattle / Magnolia'),
  ('geo-us-sea-madrona','Madrona','Geography / Countries / North America / United States / Washington / Seattle / Madrona'),
  ('geo-us-sea-madison-park','Madison Park','Geography / Countries / North America / United States / Washington / Seattle / Madison Park'),
  ('geo-us-sea-west-seattle','West Seattle','Geography / Countries / North America / United States / Washington / Seattle / West Seattle'),
  ('geo-us-sea-georgetown','Georgetown','Geography / Countries / North America / United States / Washington / Seattle / Georgetown'),
  ('geo-us-sea-beacon-hill','Beacon Hill','Geography / Countries / North America / United States / Washington / Seattle / Beacon Hill'),
  ('geo-us-sea-columbia-city','Columbia City','Geography / Countries / North America / United States / Washington / Seattle / Columbia City'),
  ('geo-us-sea-rainier-beach','Rainier Beach','Geography / Countries / North America / United States / Washington / Seattle / Rainier Beach'),
  ('geo-us-sea-chinatown-international-district','Chinatown-International District','Geography / Countries / North America / United States / Washington / Seattle / Chinatown-International District'),
  ('geo-us-mia-downtown','Downtown','Geography / Countries / North America / United States / Florida / Miami / Downtown'),
  ('geo-us-mia-brickell','Brickell','Geography / Countries / North America / United States / Florida / Miami / Brickell'),
  ('geo-us-mia-wynwood','Wynwood','Geography / Countries / North America / United States / Florida / Miami / Wynwood'),
  ('geo-us-mia-design-district','Design District','Geography / Countries / North America / United States / Florida / Miami / Design District'),
  ('geo-us-mia-edgewater','Edgewater','Geography / Countries / North America / United States / Florida / Miami / Edgewater'),
  ('geo-us-mia-midtown','Midtown','Geography / Countries / North America / United States / Florida / Miami / Midtown'),
  ('geo-us-mia-little-havana','Little Havana','Geography / Countries / North America / United States / Florida / Miami / Little Havana'),
  ('geo-us-mia-little-haiti','Little Haiti','Geography / Countries / North America / United States / Florida / Miami / Little Haiti'),
  ('geo-us-mia-overtown','Overtown','Geography / Countries / North America / United States / Florida / Miami / Overtown'),
  ('geo-us-mia-allapattah','Allapattah','Geography / Countries / North America / United States / Florida / Miami / Allapattah'),
  ('geo-us-mia-coconut-grove','Coconut Grove','Geography / Countries / North America / United States / Florida / Miami / Coconut Grove'),
  ('geo-us-mia-coral-way','Coral Way','Geography / Countries / North America / United States / Florida / Miami / Coral Way'),
  ('geo-us-mia-upper-eastside','Upper Eastside','Geography / Countries / North America / United States / Florida / Miami / Upper Eastside'),
  ('geo-us-mia-flagami','Flagami','Geography / Countries / North America / United States / Florida / Miami / Flagami'),
  ('geo-us-mia-liberty-city','Liberty City','Geography / Countries / North America / United States / Florida / Miami / Liberty City'),
  ('geo-us-sd-downtown','Downtown','Geography / Countries / North America / United States / California / San Diego / Downtown'),
  ('geo-us-sd-gaslamp-quarter','Gaslamp Quarter','Geography / Countries / North America / United States / California / San Diego / Gaslamp Quarter'),
  ('geo-us-sd-little-italy','Little Italy','Geography / Countries / North America / United States / California / San Diego / Little Italy'),
  ('geo-us-sd-east-village','East Village','Geography / Countries / North America / United States / California / San Diego / East Village'),
  ('geo-us-sd-hillcrest','Hillcrest','Geography / Countries / North America / United States / California / San Diego / Hillcrest'),
  ('geo-us-sd-north-park','North Park','Geography / Countries / North America / United States / California / San Diego / North Park'),
  ('geo-us-sd-south-park','South Park','Geography / Countries / North America / United States / California / San Diego / South Park'),
  ('geo-us-sd-mission-hills','Mission Hills','Geography / Countries / North America / United States / California / San Diego / Mission Hills'),
  ('geo-us-sd-old-town','Old Town','Geography / Countries / North America / United States / California / San Diego / Old Town'),
  ('geo-us-sd-mission-valley','Mission Valley','Geography / Countries / North America / United States / California / San Diego / Mission Valley'),
  ('geo-us-sd-mission-beach','Mission Beach','Geography / Countries / North America / United States / California / San Diego / Mission Beach'),
  ('geo-us-sd-pacific-beach','Pacific Beach','Geography / Countries / North America / United States / California / San Diego / Pacific Beach'),
  ('geo-us-sd-ocean-beach','Ocean Beach','Geography / Countries / North America / United States / California / San Diego / Ocean Beach'),
  ('geo-us-sd-la-jolla','La Jolla','Geography / Countries / North America / United States / California / San Diego / La Jolla'),
  ('geo-us-sd-point-loma','Point Loma','Geography / Countries / North America / United States / California / San Diego / Point Loma'),
  ('geo-us-sd-normal-heights','Normal Heights','Geography / Countries / North America / United States / California / San Diego / Normal Heights'),
  ('geo-us-sd-university-heights','University Heights','Geography / Countries / North America / United States / California / San Diego / University Heights'),
  ('geo-us-sd-kensington','Kensington','Geography / Countries / North America / United States / California / San Diego / Kensington'),
  ('geo-us-sd-city-heights','City Heights','Geography / Countries / North America / United States / California / San Diego / City Heights'),
  ('geo-us-sd-barrio-logan','Barrio Logan','Geography / Countries / North America / United States / California / San Diego / Barrio Logan'),
  ('geo-us-sd-clairemont','Clairemont','Geography / Countries / North America / United States / California / San Diego / Clairemont')
) AS v(id, name, path);

UPDATE public.atoms SET is_leaf = false
 WHERE id IN ('geo-us-city-houston','geo-us-city-philadelphia','geo-us-city-san-francisco','geo-us-city-boston',
              'geography-countries-united-states-subdivisions-washington-d-c',
              'geo-us-city-seattle','geo-us-city-miami','geo-us-city-san-diego');
