-- Geography: NYC neighborhoods at depth 8 under the five boroughs (158 atoms).
-- Applied to prod 2026-07-02 as version 20260702204135.
-- Manhattan 34 · Brooklyn 41 · Queens 37 · The Bronx 28 · Staten Island 18.
-- Boroughs flip is_leaf=false. Geo jsonb matches megacity-neighborhood shape + parentBorough.
INSERT INTO public.atoms (id, name, path, path_parts, depth, realm_id, realm_name, type, kettle, band, status, is_leaf, pillar_tags, skin_tags, realm_tags, geo)
SELECT v.id, v.name, v.path, string_to_array(v.path,' / '), array_length(string_to_array(v.path,' / '),1),
       'geography','Geography','neighborhood','Accepted',NULL,'live', true,
       ARRAY['MANUAL'], ARRAY['HoneyComb'], ARRAY['Geography'],
       jsonb_build_object('type','neighborhood','regionName',v.name,
         'parentBorough',(string_to_array(v.path,' / '))[7],
         'parentCity','New York City','parentRegion','New York','parentCountry','US')
FROM (VALUES
  ('geo-us-nyc-mn-harlem','Harlem','Geography / Countries / North America / United States / New York / New York City / Manhattan / Harlem'),
  ('geo-us-nyc-mn-east-harlem','East Harlem','Geography / Countries / North America / United States / New York / New York City / Manhattan / East Harlem'),
  ('geo-us-nyc-mn-washington-heights','Washington Heights','Geography / Countries / North America / United States / New York / New York City / Manhattan / Washington Heights'),
  ('geo-us-nyc-mn-inwood','Inwood','Geography / Countries / North America / United States / New York / New York City / Manhattan / Inwood'),
  ('geo-us-nyc-mn-hamilton-heights','Hamilton Heights','Geography / Countries / North America / United States / New York / New York City / Manhattan / Hamilton Heights'),
  ('geo-us-nyc-mn-morningside-heights','Morningside Heights','Geography / Countries / North America / United States / New York / New York City / Manhattan / Morningside Heights'),
  ('geo-us-nyc-mn-upper-west-side','Upper West Side','Geography / Countries / North America / United States / New York / New York City / Manhattan / Upper West Side'),
  ('geo-us-nyc-mn-upper-east-side','Upper East Side','Geography / Countries / North America / United States / New York / New York City / Manhattan / Upper East Side'),
  ('geo-us-nyc-mn-yorkville','Yorkville','Geography / Countries / North America / United States / New York / New York City / Manhattan / Yorkville'),
  ('geo-us-nyc-mn-lenox-hill','Lenox Hill','Geography / Countries / North America / United States / New York / New York City / Manhattan / Lenox Hill'),
  ('geo-us-nyc-mn-midtown','Midtown','Geography / Countries / North America / United States / New York / New York City / Manhattan / Midtown'),
  ('geo-us-nyc-mn-hells-kitchen','Hell''s Kitchen','Geography / Countries / North America / United States / New York / New York City / Manhattan / Hell''s Kitchen'),
  ('geo-us-nyc-mn-murray-hill','Murray Hill','Geography / Countries / North America / United States / New York / New York City / Manhattan / Murray Hill'),
  ('geo-us-nyc-mn-kips-bay','Kips Bay','Geography / Countries / North America / United States / New York / New York City / Manhattan / Kips Bay'),
  ('geo-us-nyc-mn-chelsea','Chelsea','Geography / Countries / North America / United States / New York / New York City / Manhattan / Chelsea'),
  ('geo-us-nyc-mn-gramercy','Gramercy','Geography / Countries / North America / United States / New York / New York City / Manhattan / Gramercy'),
  ('geo-us-nyc-mn-flatiron-district','Flatiron District','Geography / Countries / North America / United States / New York / New York City / Manhattan / Flatiron District'),
  ('geo-us-nyc-mn-nomad','NoMad','Geography / Countries / North America / United States / New York / New York City / Manhattan / NoMad'),
  ('geo-us-nyc-mn-east-village','East Village','Geography / Countries / North America / United States / New York / New York City / Manhattan / East Village'),
  ('geo-us-nyc-mn-alphabet-city','Alphabet City','Geography / Countries / North America / United States / New York / New York City / Manhattan / Alphabet City'),
  ('geo-us-nyc-mn-greenwich-village','Greenwich Village','Geography / Countries / North America / United States / New York / New York City / Manhattan / Greenwich Village'),
  ('geo-us-nyc-mn-west-village','West Village','Geography / Countries / North America / United States / New York / New York City / Manhattan / West Village'),
  ('geo-us-nyc-mn-soho','SoHo','Geography / Countries / North America / United States / New York / New York City / Manhattan / SoHo'),
  ('geo-us-nyc-mn-noho','NoHo','Geography / Countries / North America / United States / New York / New York City / Manhattan / NoHo'),
  ('geo-us-nyc-mn-nolita','Nolita','Geography / Countries / North America / United States / New York / New York City / Manhattan / Nolita'),
  ('geo-us-nyc-mn-little-italy','Little Italy','Geography / Countries / North America / United States / New York / New York City / Manhattan / Little Italy'),
  ('geo-us-nyc-mn-chinatown','Chinatown','Geography / Countries / North America / United States / New York / New York City / Manhattan / Chinatown'),
  ('geo-us-nyc-mn-lower-east-side','Lower East Side','Geography / Countries / North America / United States / New York / New York City / Manhattan / Lower East Side'),
  ('geo-us-nyc-mn-two-bridges','Two Bridges','Geography / Countries / North America / United States / New York / New York City / Manhattan / Two Bridges'),
  ('geo-us-nyc-mn-tribeca','Tribeca','Geography / Countries / North America / United States / New York / New York City / Manhattan / Tribeca'),
  ('geo-us-nyc-mn-financial-district','Financial District','Geography / Countries / North America / United States / New York / New York City / Manhattan / Financial District'),
  ('geo-us-nyc-mn-battery-park-city','Battery Park City','Geography / Countries / North America / United States / New York / New York City / Manhattan / Battery Park City'),
  ('geo-us-nyc-mn-roosevelt-island','Roosevelt Island','Geography / Countries / North America / United States / New York / New York City / Manhattan / Roosevelt Island'),
  ('geo-us-nyc-mn-marble-hill','Marble Hill','Geography / Countries / North America / United States / New York / New York City / Manhattan / Marble Hill'),
  ('geo-us-nyc-bk-williamsburg','Williamsburg','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Williamsburg'),
  ('geo-us-nyc-bk-greenpoint','Greenpoint','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Greenpoint'),
  ('geo-us-nyc-bk-bushwick','Bushwick','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Bushwick'),
  ('geo-us-nyc-bk-bedford-stuyvesant','Bedford-Stuyvesant','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Bedford-Stuyvesant'),
  ('geo-us-nyc-bk-crown-heights','Crown Heights','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Crown Heights'),
  ('geo-us-nyc-bk-prospect-heights','Prospect Heights','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Prospect Heights'),
  ('geo-us-nyc-bk-park-slope','Park Slope','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Park Slope'),
  ('geo-us-nyc-bk-gowanus','Gowanus','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Gowanus'),
  ('geo-us-nyc-bk-carroll-gardens','Carroll Gardens','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Carroll Gardens'),
  ('geo-us-nyc-bk-cobble-hill','Cobble Hill','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Cobble Hill'),
  ('geo-us-nyc-bk-boerum-hill','Boerum Hill','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Boerum Hill'),
  ('geo-us-nyc-bk-brooklyn-heights','Brooklyn Heights','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Brooklyn Heights'),
  ('geo-us-nyc-bk-dumbo','DUMBO','Geography / Countries / North America / United States / New York / New York City / Brooklyn / DUMBO'),
  ('geo-us-nyc-bk-vinegar-hill','Vinegar Hill','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Vinegar Hill'),
  ('geo-us-nyc-bk-downtown-brooklyn','Downtown Brooklyn','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Downtown Brooklyn'),
  ('geo-us-nyc-bk-fort-greene','Fort Greene','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Fort Greene'),
  ('geo-us-nyc-bk-clinton-hill','Clinton Hill','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Clinton Hill'),
  ('geo-us-nyc-bk-red-hook','Red Hook','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Red Hook'),
  ('geo-us-nyc-bk-sunset-park','Sunset Park','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Sunset Park'),
  ('geo-us-nyc-bk-bay-ridge','Bay Ridge','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Bay Ridge'),
  ('geo-us-nyc-bk-dyker-heights','Dyker Heights','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Dyker Heights'),
  ('geo-us-nyc-bk-bensonhurst','Bensonhurst','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Bensonhurst'),
  ('geo-us-nyc-bk-bath-beach','Bath Beach','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Bath Beach'),
  ('geo-us-nyc-bk-gravesend','Gravesend','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Gravesend'),
  ('geo-us-nyc-bk-sheepshead-bay','Sheepshead Bay','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Sheepshead Bay'),
  ('geo-us-nyc-bk-brighton-beach','Brighton Beach','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Brighton Beach'),
  ('geo-us-nyc-bk-coney-island','Coney Island','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Coney Island'),
  ('geo-us-nyc-bk-flatbush','Flatbush','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Flatbush'),
  ('geo-us-nyc-bk-east-flatbush','East Flatbush','Geography / Countries / North America / United States / New York / New York City / Brooklyn / East Flatbush'),
  ('geo-us-nyc-bk-midwood','Midwood','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Midwood'),
  ('geo-us-nyc-bk-borough-park','Borough Park','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Borough Park'),
  ('geo-us-nyc-bk-kensington','Kensington','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Kensington'),
  ('geo-us-nyc-bk-windsor-terrace','Windsor Terrace','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Windsor Terrace'),
  ('geo-us-nyc-bk-prospect-lefferts-gardens','Prospect Lefferts Gardens','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Prospect Lefferts Gardens'),
  ('geo-us-nyc-bk-brownsville','Brownsville','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Brownsville'),
  ('geo-us-nyc-bk-east-new-york','East New York','Geography / Countries / North America / United States / New York / New York City / Brooklyn / East New York'),
  ('geo-us-nyc-bk-cypress-hills','Cypress Hills','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Cypress Hills'),
  ('geo-us-nyc-bk-canarsie','Canarsie','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Canarsie'),
  ('geo-us-nyc-bk-flatlands','Flatlands','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Flatlands'),
  ('geo-us-nyc-bk-marine-park','Marine Park','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Marine Park'),
  ('geo-us-nyc-bk-mill-basin','Mill Basin','Geography / Countries / North America / United States / New York / New York City / Brooklyn / Mill Basin'),
  ('geo-us-nyc-qn-astoria','Astoria','Geography / Countries / North America / United States / New York / New York City / Queens / Astoria'),
  ('geo-us-nyc-qn-long-island-city','Long Island City','Geography / Countries / North America / United States / New York / New York City / Queens / Long Island City'),
  ('geo-us-nyc-qn-sunnyside','Sunnyside','Geography / Countries / North America / United States / New York / New York City / Queens / Sunnyside'),
  ('geo-us-nyc-qn-woodside','Woodside','Geography / Countries / North America / United States / New York / New York City / Queens / Woodside'),
  ('geo-us-nyc-qn-jackson-heights','Jackson Heights','Geography / Countries / North America / United States / New York / New York City / Queens / Jackson Heights'),
  ('geo-us-nyc-qn-east-elmhurst','East Elmhurst','Geography / Countries / North America / United States / New York / New York City / Queens / East Elmhurst'),
  ('geo-us-nyc-qn-elmhurst','Elmhurst','Geography / Countries / North America / United States / New York / New York City / Queens / Elmhurst'),
  ('geo-us-nyc-qn-corona','Corona','Geography / Countries / North America / United States / New York / New York City / Queens / Corona'),
  ('geo-us-nyc-qn-flushing','Flushing','Geography / Countries / North America / United States / New York / New York City / Queens / Flushing'),
  ('geo-us-nyc-qn-college-point','College Point','Geography / Countries / North America / United States / New York / New York City / Queens / College Point'),
  ('geo-us-nyc-qn-whitestone','Whitestone','Geography / Countries / North America / United States / New York / New York City / Queens / Whitestone'),
  ('geo-us-nyc-qn-bayside','Bayside','Geography / Countries / North America / United States / New York / New York City / Queens / Bayside'),
  ('geo-us-nyc-qn-douglaston','Douglaston','Geography / Countries / North America / United States / New York / New York City / Queens / Douglaston'),
  ('geo-us-nyc-qn-little-neck','Little Neck','Geography / Countries / North America / United States / New York / New York City / Queens / Little Neck'),
  ('geo-us-nyc-qn-fresh-meadows','Fresh Meadows','Geography / Countries / North America / United States / New York / New York City / Queens / Fresh Meadows'),
  ('geo-us-nyc-qn-forest-hills','Forest Hills','Geography / Countries / North America / United States / New York / New York City / Queens / Forest Hills'),
  ('geo-us-nyc-qn-rego-park','Rego Park','Geography / Countries / North America / United States / New York / New York City / Queens / Rego Park'),
  ('geo-us-nyc-qn-kew-gardens','Kew Gardens','Geography / Countries / North America / United States / New York / New York City / Queens / Kew Gardens'),
  ('geo-us-nyc-qn-richmond-hill','Richmond Hill','Geography / Countries / North America / United States / New York / New York City / Queens / Richmond Hill'),
  ('geo-us-nyc-qn-woodhaven','Woodhaven','Geography / Countries / North America / United States / New York / New York City / Queens / Woodhaven'),
  ('geo-us-nyc-qn-ozone-park','Ozone Park','Geography / Countries / North America / United States / New York / New York City / Queens / Ozone Park'),
  ('geo-us-nyc-qn-south-ozone-park','South Ozone Park','Geography / Countries / North America / United States / New York / New York City / Queens / South Ozone Park'),
  ('geo-us-nyc-qn-howard-beach','Howard Beach','Geography / Countries / North America / United States / New York / New York City / Queens / Howard Beach'),
  ('geo-us-nyc-qn-jamaica','Jamaica','Geography / Countries / North America / United States / New York / New York City / Queens / Jamaica'),
  ('geo-us-nyc-qn-st-albans','St. Albans','Geography / Countries / North America / United States / New York / New York City / Queens / St. Albans'),
  ('geo-us-nyc-qn-hollis','Hollis','Geography / Countries / North America / United States / New York / New York City / Queens / Hollis'),
  ('geo-us-nyc-qn-queens-village','Queens Village','Geography / Countries / North America / United States / New York / New York City / Queens / Queens Village'),
  ('geo-us-nyc-qn-ridgewood','Ridgewood','Geography / Countries / North America / United States / New York / New York City / Queens / Ridgewood'),
  ('geo-us-nyc-qn-maspeth','Maspeth','Geography / Countries / North America / United States / New York / New York City / Queens / Maspeth'),
  ('geo-us-nyc-qn-middle-village','Middle Village','Geography / Countries / North America / United States / New York / New York City / Queens / Middle Village'),
  ('geo-us-nyc-qn-glendale','Glendale','Geography / Countries / North America / United States / New York / New York City / Queens / Glendale'),
  ('geo-us-nyc-qn-springfield-gardens','Springfield Gardens','Geography / Countries / North America / United States / New York / New York City / Queens / Springfield Gardens'),
  ('geo-us-nyc-qn-laurelton','Laurelton','Geography / Countries / North America / United States / New York / New York City / Queens / Laurelton'),
  ('geo-us-nyc-qn-rosedale','Rosedale','Geography / Countries / North America / United States / New York / New York City / Queens / Rosedale'),
  ('geo-us-nyc-qn-rockaway-beach','Rockaway Beach','Geography / Countries / North America / United States / New York / New York City / Queens / Rockaway Beach'),
  ('geo-us-nyc-qn-far-rockaway','Far Rockaway','Geography / Countries / North America / United States / New York / New York City / Queens / Far Rockaway'),
  ('geo-us-nyc-qn-breezy-point','Breezy Point','Geography / Countries / North America / United States / New York / New York City / Queens / Breezy Point'),
  ('geo-us-nyc-bx-riverdale','Riverdale','Geography / Countries / North America / United States / New York / New York City / The Bronx / Riverdale'),
  ('geo-us-nyc-bx-kingsbridge','Kingsbridge','Geography / Countries / North America / United States / New York / New York City / The Bronx / Kingsbridge'),
  ('geo-us-nyc-bx-fordham','Fordham','Geography / Countries / North America / United States / New York / New York City / The Bronx / Fordham'),
  ('geo-us-nyc-bx-belmont','Belmont','Geography / Countries / North America / United States / New York / New York City / The Bronx / Belmont'),
  ('geo-us-nyc-bx-tremont','Tremont','Geography / Countries / North America / United States / New York / New York City / The Bronx / Tremont'),
  ('geo-us-nyc-bx-mott-haven','Mott Haven','Geography / Countries / North America / United States / New York / New York City / The Bronx / Mott Haven'),
  ('geo-us-nyc-bx-melrose','Melrose','Geography / Countries / North America / United States / New York / New York City / The Bronx / Melrose'),
  ('geo-us-nyc-bx-morrisania','Morrisania','Geography / Countries / North America / United States / New York / New York City / The Bronx / Morrisania'),
  ('geo-us-nyc-bx-hunts-point','Hunts Point','Geography / Countries / North America / United States / New York / New York City / The Bronx / Hunts Point'),
  ('geo-us-nyc-bx-longwood','Longwood','Geography / Countries / North America / United States / New York / New York City / The Bronx / Longwood'),
  ('geo-us-nyc-bx-concourse','Concourse','Geography / Countries / North America / United States / New York / New York City / The Bronx / Concourse'),
  ('geo-us-nyc-bx-highbridge','Highbridge','Geography / Countries / North America / United States / New York / New York City / The Bronx / Highbridge'),
  ('geo-us-nyc-bx-morris-heights','Morris Heights','Geography / Countries / North America / United States / New York / New York City / The Bronx / Morris Heights'),
  ('geo-us-nyc-bx-university-heights','University Heights','Geography / Countries / North America / United States / New York / New York City / The Bronx / University Heights'),
  ('geo-us-nyc-bx-bedford-park','Bedford Park','Geography / Countries / North America / United States / New York / New York City / The Bronx / Bedford Park'),
  ('geo-us-nyc-bx-norwood','Norwood','Geography / Countries / North America / United States / New York / New York City / The Bronx / Norwood'),
  ('geo-us-nyc-bx-wakefield','Wakefield','Geography / Countries / North America / United States / New York / New York City / The Bronx / Wakefield'),
  ('geo-us-nyc-bx-williamsbridge','Williamsbridge','Geography / Countries / North America / United States / New York / New York City / The Bronx / Williamsbridge'),
  ('geo-us-nyc-bx-baychester','Baychester','Geography / Countries / North America / United States / New York / New York City / The Bronx / Baychester'),
  ('geo-us-nyc-bx-coop-city','Co-op City','Geography / Countries / North America / United States / New York / New York City / The Bronx / Co-op City'),
  ('geo-us-nyc-bx-pelham-bay','Pelham Bay','Geography / Countries / North America / United States / New York / New York City / The Bronx / Pelham Bay'),
  ('geo-us-nyc-bx-throgs-neck','Throgs Neck','Geography / Countries / North America / United States / New York / New York City / The Bronx / Throgs Neck'),
  ('geo-us-nyc-bx-castle-hill','Castle Hill','Geography / Countries / North America / United States / New York / New York City / The Bronx / Castle Hill'),
  ('geo-us-nyc-bx-soundview','Soundview','Geography / Countries / North America / United States / New York / New York City / The Bronx / Soundview'),
  ('geo-us-nyc-bx-parkchester','Parkchester','Geography / Countries / North America / United States / New York / New York City / The Bronx / Parkchester'),
  ('geo-us-nyc-bx-westchester-square','Westchester Square','Geography / Countries / North America / United States / New York / New York City / The Bronx / Westchester Square'),
  ('geo-us-nyc-bx-city-island','City Island','Geography / Countries / North America / United States / New York / New York City / The Bronx / City Island'),
  ('geo-us-nyc-bx-morris-park','Morris Park','Geography / Countries / North America / United States / New York / New York City / The Bronx / Morris Park'),
  ('geo-us-nyc-si-st-george','St. George','Geography / Countries / North America / United States / New York / New York City / Staten Island / St. George'),
  ('geo-us-nyc-si-tompkinsville','Tompkinsville','Geography / Countries / North America / United States / New York / New York City / Staten Island / Tompkinsville'),
  ('geo-us-nyc-si-stapleton','Stapleton','Geography / Countries / North America / United States / New York / New York City / Staten Island / Stapleton'),
  ('geo-us-nyc-si-new-brighton','New Brighton','Geography / Countries / North America / United States / New York / New York City / Staten Island / New Brighton'),
  ('geo-us-nyc-si-west-brighton','West Brighton','Geography / Countries / North America / United States / New York / New York City / Staten Island / West Brighton'),
  ('geo-us-nyc-si-port-richmond','Port Richmond','Geography / Countries / North America / United States / New York / New York City / Staten Island / Port Richmond'),
  ('geo-us-nyc-si-mariners-harbor','Mariners Harbor','Geography / Countries / North America / United States / New York / New York City / Staten Island / Mariners Harbor'),
  ('geo-us-nyc-si-willowbrook','Willowbrook','Geography / Countries / North America / United States / New York / New York City / Staten Island / Willowbrook'),
  ('geo-us-nyc-si-bulls-head','Bulls Head','Geography / Countries / North America / United States / New York / New York City / Staten Island / Bulls Head'),
  ('geo-us-nyc-si-todt-hill','Todt Hill','Geography / Countries / North America / United States / New York / New York City / Staten Island / Todt Hill'),
  ('geo-us-nyc-si-grasmere','Grasmere','Geography / Countries / North America / United States / New York / New York City / Staten Island / Grasmere'),
  ('geo-us-nyc-si-south-beach','South Beach','Geography / Countries / North America / United States / New York / New York City / Staten Island / South Beach'),
  ('geo-us-nyc-si-new-dorp','New Dorp','Geography / Countries / North America / United States / New York / New York City / Staten Island / New Dorp'),
  ('geo-us-nyc-si-great-kills','Great Kills','Geography / Countries / North America / United States / New York / New York City / Staten Island / Great Kills'),
  ('geo-us-nyc-si-eltingville','Eltingville','Geography / Countries / North America / United States / New York / New York City / Staten Island / Eltingville'),
  ('geo-us-nyc-si-annadale','Annadale','Geography / Countries / North America / United States / New York / New York City / Staten Island / Annadale'),
  ('geo-us-nyc-si-rossville','Rossville','Geography / Countries / North America / United States / New York / New York City / Staten Island / Rossville'),
  ('geo-us-nyc-si-tottenville','Tottenville','Geography / Countries / North America / United States / New York / New York City / Staten Island / Tottenville')
) AS v(id, name, path);

UPDATE public.atoms SET is_leaf = false
 WHERE id IN ('geo-us-nyc-manhattan','geo-us-nyc-brooklyn','geo-us-nyc-queens','geo-us-nyc-bronx','geo-us-nyc-staten-island');
