-- Geography: neighborhood build-out batch 02a — Phoenix 18 · San Antonio 16 · Dallas 18 · Austin 18 (70 atoms).
-- Parent city atoms flip is_leaf=false. Same shape as batch 01. Batch 02b covers Denver/Atlanta/Detroit/Portland.
INSERT INTO public.atoms (id, name, path, path_parts, depth, realm_id, realm_name, type, kettle, band, status, is_leaf, pillar_tags, skin_tags, realm_tags, geo)
SELECT v.id, v.name, v.path, string_to_array(v.path,' / '), array_length(string_to_array(v.path,' / '),1),
       'geography','Geography','neighborhood','Accepted',NULL,'live', true,
       ARRAY['MANUAL'], ARRAY['HoneyComb'], ARRAY['Geography'],
       jsonb_build_object('type','neighborhood','regionName',v.name,
         'parentCity',(string_to_array(v.path,' / '))[array_length(string_to_array(v.path,' / '),1)-1],
         'parentRegion',(string_to_array(v.path,' / '))[5],
         'parentCountry','US')
FROM (VALUES
  ('geo-us-phx-downtown','Downtown','Geography / Countries / North America / United States / Arizona / Phoenix / Downtown'),
  ('geo-us-phx-midtown','Midtown','Geography / Countries / North America / United States / Arizona / Phoenix / Midtown'),
  ('geo-us-phx-roosevelt-row','Roosevelt Row','Geography / Countries / North America / United States / Arizona / Phoenix / Roosevelt Row'),
  ('geo-us-phx-arcadia','Arcadia','Geography / Countries / North America / United States / Arizona / Phoenix / Arcadia'),
  ('geo-us-phx-biltmore','Biltmore','Geography / Countries / North America / United States / Arizona / Phoenix / Biltmore'),
  ('geo-us-phx-encanto','Encanto','Geography / Countries / North America / United States / Arizona / Phoenix / Encanto'),
  ('geo-us-phx-coronado','Coronado','Geography / Countries / North America / United States / Arizona / Phoenix / Coronado'),
  ('geo-us-phx-willo','Willo','Geography / Countries / North America / United States / Arizona / Phoenix / Willo'),
  ('geo-us-phx-garfield','Garfield','Geography / Countries / North America / United States / Arizona / Phoenix / Garfield'),
  ('geo-us-phx-sunnyslope','Sunnyslope','Geography / Countries / North America / United States / Arizona / Phoenix / Sunnyslope'),
  ('geo-us-phx-ahwatukee','Ahwatukee','Geography / Countries / North America / United States / Arizona / Phoenix / Ahwatukee'),
  ('geo-us-phx-maryvale','Maryvale','Geography / Countries / North America / United States / Arizona / Phoenix / Maryvale'),
  ('geo-us-phx-laveen','Laveen','Geography / Countries / North America / United States / Arizona / Phoenix / Laveen'),
  ('geo-us-phx-south-mountain','South Mountain','Geography / Countries / North America / United States / Arizona / Phoenix / South Mountain'),
  ('geo-us-phx-desert-ridge','Desert Ridge','Geography / Countries / North America / United States / Arizona / Phoenix / Desert Ridge'),
  ('geo-us-phx-deer-valley','Deer Valley','Geography / Countries / North America / United States / Arizona / Phoenix / Deer Valley'),
  ('geo-us-phx-alhambra','Alhambra','Geography / Countries / North America / United States / Arizona / Phoenix / Alhambra'),
  ('geo-us-phx-camelback-east','Camelback East','Geography / Countries / North America / United States / Arizona / Phoenix / Camelback East'),
  ('geo-us-sat-downtown','Downtown','Geography / Countries / North America / United States / Texas / San Antonio / Downtown'),
  ('geo-us-sat-southtown','Southtown','Geography / Countries / North America / United States / Texas / San Antonio / Southtown'),
  ('geo-us-sat-king-william','King William','Geography / Countries / North America / United States / Texas / San Antonio / King William'),
  ('geo-us-sat-pearl','Pearl','Geography / Countries / North America / United States / Texas / San Antonio / Pearl'),
  ('geo-us-sat-monte-vista','Monte Vista','Geography / Countries / North America / United States / Texas / San Antonio / Monte Vista'),
  ('geo-us-sat-tobin-hill','Tobin Hill','Geography / Countries / North America / United States / Texas / San Antonio / Tobin Hill'),
  ('geo-us-sat-dignowity-hill','Dignowity Hill','Geography / Countries / North America / United States / Texas / San Antonio / Dignowity Hill'),
  ('geo-us-sat-beacon-hill','Beacon Hill','Geography / Countries / North America / United States / Texas / San Antonio / Beacon Hill'),
  ('geo-us-sat-alta-vista','Alta Vista','Geography / Countries / North America / United States / Texas / San Antonio / Alta Vista'),
  ('geo-us-sat-lavaca','Lavaca','Geography / Countries / North America / United States / Texas / San Antonio / Lavaca'),
  ('geo-us-sat-government-hill','Government Hill','Geography / Countries / North America / United States / Texas / San Antonio / Government Hill'),
  ('geo-us-sat-stone-oak','Stone Oak','Geography / Countries / North America / United States / Texas / San Antonio / Stone Oak'),
  ('geo-us-sat-medical-center','Medical Center','Geography / Countries / North America / United States / Texas / San Antonio / Medical Center'),
  ('geo-us-sat-prospect-hill','Prospect Hill','Geography / Countries / North America / United States / Texas / San Antonio / Prospect Hill'),
  ('geo-us-sat-denver-heights','Denver Heights','Geography / Countries / North America / United States / Texas / San Antonio / Denver Heights'),
  ('geo-us-sat-great-northwest','Great Northwest','Geography / Countries / North America / United States / Texas / San Antonio / Great Northwest'),
  ('geo-us-dal-downtown','Downtown','Geography / Countries / North America / United States / Texas / Dallas / Downtown'),
  ('geo-us-dal-deep-ellum','Deep Ellum','Geography / Countries / North America / United States / Texas / Dallas / Deep Ellum'),
  ('geo-us-dal-uptown','Uptown','Geography / Countries / North America / United States / Texas / Dallas / Uptown'),
  ('geo-us-dal-oak-lawn','Oak Lawn','Geography / Countries / North America / United States / Texas / Dallas / Oak Lawn'),
  ('geo-us-dal-bishop-arts-district','Bishop Arts District','Geography / Countries / North America / United States / Texas / Dallas / Bishop Arts District'),
  ('geo-us-dal-oak-cliff','Oak Cliff','Geography / Countries / North America / United States / Texas / Dallas / Oak Cliff'),
  ('geo-us-dal-lakewood','Lakewood','Geography / Countries / North America / United States / Texas / Dallas / Lakewood'),
  ('geo-us-dal-lower-greenville','Lower Greenville','Geography / Countries / North America / United States / Texas / Dallas / Lower Greenville'),
  ('geo-us-dal-knox-henderson','Knox-Henderson','Geography / Countries / North America / United States / Texas / Dallas / Knox-Henderson'),
  ('geo-us-dal-design-district','Design District','Geography / Countries / North America / United States / Texas / Dallas / Design District'),
  ('geo-us-dal-victory-park','Victory Park','Geography / Countries / North America / United States / Texas / Dallas / Victory Park'),
  ('geo-us-dal-trinity-groves','Trinity Groves','Geography / Countries / North America / United States / Texas / Dallas / Trinity Groves'),
  ('geo-us-dal-fair-park','Fair Park','Geography / Countries / North America / United States / Texas / Dallas / Fair Park'),
  ('geo-us-dal-pleasant-grove','Pleasant Grove','Geography / Countries / North America / United States / Texas / Dallas / Pleasant Grove'),
  ('geo-us-dal-preston-hollow','Preston Hollow','Geography / Countries / North America / United States / Texas / Dallas / Preston Hollow'),
  ('geo-us-dal-lake-highlands','Lake Highlands','Geography / Countries / North America / United States / Texas / Dallas / Lake Highlands'),
  ('geo-us-dal-m-streets','M Streets','Geography / Countries / North America / United States / Texas / Dallas / M Streets'),
  ('geo-us-dal-the-cedars','The Cedars','Geography / Countries / North America / United States / Texas / Dallas / The Cedars'),
  ('geo-us-aus-downtown','Downtown','Geography / Countries / North America / United States / Texas / Austin / Downtown'),
  ('geo-us-aus-south-congress','South Congress','Geography / Countries / North America / United States / Texas / Austin / South Congress'),
  ('geo-us-aus-east-austin','East Austin','Geography / Countries / North America / United States / Texas / Austin / East Austin'),
  ('geo-us-aus-hyde-park','Hyde Park','Geography / Countries / North America / United States / Texas / Austin / Hyde Park'),
  ('geo-us-aus-zilker','Zilker','Geography / Countries / North America / United States / Texas / Austin / Zilker'),
  ('geo-us-aus-barton-hills','Barton Hills','Geography / Countries / North America / United States / Texas / Austin / Barton Hills'),
  ('geo-us-aus-clarksville','Clarksville','Geography / Countries / North America / United States / Texas / Austin / Clarksville'),
  ('geo-us-aus-tarrytown','Tarrytown','Geography / Countries / North America / United States / Texas / Austin / Tarrytown'),
  ('geo-us-aus-mueller','Mueller','Geography / Countries / North America / United States / Texas / Austin / Mueller'),
  ('geo-us-aus-north-loop','North Loop','Geography / Countries / North America / United States / Texas / Austin / North Loop'),
  ('geo-us-aus-hancock','Hancock','Geography / Countries / North America / United States / Texas / Austin / Hancock'),
  ('geo-us-aus-bouldin-creek','Bouldin Creek','Geography / Countries / North America / United States / Texas / Austin / Bouldin Creek'),
  ('geo-us-aus-travis-heights','Travis Heights','Geography / Countries / North America / United States / Texas / Austin / Travis Heights'),
  ('geo-us-aus-rainey-street','Rainey Street','Geography / Countries / North America / United States / Texas / Austin / Rainey Street'),
  ('geo-us-aus-west-campus','West Campus','Geography / Countries / North America / United States / Texas / Austin / West Campus'),
  ('geo-us-aus-allandale','Allandale','Geography / Countries / North America / United States / Texas / Austin / Allandale'),
  ('geo-us-aus-crestview','Crestview','Geography / Countries / North America / United States / Texas / Austin / Crestview'),
  ('geo-us-aus-rosedale','Rosedale','Geography / Countries / North America / United States / Texas / Austin / Rosedale')
) AS v(id, name, path);

UPDATE public.atoms SET is_leaf = false
WHERE id IN ('geo-us-city-phoenix','geo-us-city-san-antonio','geo-us-city-dallas','geo-us-city-austin');
