-- Geography: neighborhood build-out batch 04a — Memphis 16 · Baltimore 18 · Milwaukee 16 · Oklahoma City 16 (66 atoms).
-- Parent city atoms flip is_leaf=false. Batch 04b covers Louisville/Kansas City/St. Louis/Minneapolis.
INSERT INTO public.atoms (id, name, path, path_parts, depth, realm_id, realm_name, type, kettle, band, status, is_leaf, pillar_tags, skin_tags, realm_tags, geo)
SELECT v.id, v.name, v.path, string_to_array(v.path,' / '), array_length(string_to_array(v.path,' / '),1),
       'geography','Geography','neighborhood','Accepted',NULL,'live', true,
       ARRAY['MANUAL'], ARRAY['HoneyComb'], ARRAY['Geography'],
       jsonb_build_object('type','neighborhood','regionName',v.name,
         'parentCity',(string_to_array(v.path,' / '))[array_length(string_to_array(v.path,' / '),1)-1],
         'parentRegion',(string_to_array(v.path,' / '))[5],
         'parentCountry','US')
FROM (VALUES
  ('geo-us-mem-downtown','Downtown','Geography / Countries / North America / United States / Tennessee / Memphis / Downtown'),
  ('geo-us-mem-beale-street','Beale Street','Geography / Countries / North America / United States / Tennessee / Memphis / Beale Street'),
  ('geo-us-mem-south-main','South Main','Geography / Countries / North America / United States / Tennessee / Memphis / South Main'),
  ('geo-us-mem-midtown','Midtown','Geography / Countries / North America / United States / Tennessee / Memphis / Midtown'),
  ('geo-us-mem-cooper-young','Cooper-Young','Geography / Countries / North America / United States / Tennessee / Memphis / Cooper-Young'),
  ('geo-us-mem-overton-square','Overton Square','Geography / Countries / North America / United States / Tennessee / Memphis / Overton Square'),
  ('geo-us-mem-victorian-village','Victorian Village','Geography / Countries / North America / United States / Tennessee / Memphis / Victorian Village'),
  ('geo-us-mem-uptown','Uptown','Geography / Countries / North America / United States / Tennessee / Memphis / Uptown'),
  ('geo-us-mem-harbor-town','Harbor Town','Geography / Countries / North America / United States / Tennessee / Memphis / Harbor Town'),
  ('geo-us-mem-orange-mound','Orange Mound','Geography / Countries / North America / United States / Tennessee / Memphis / Orange Mound'),
  ('geo-us-mem-binghampton','Binghampton','Geography / Countries / North America / United States / Tennessee / Memphis / Binghampton'),
  ('geo-us-mem-east-memphis','East Memphis','Geography / Countries / North America / United States / Tennessee / Memphis / East Memphis'),
  ('geo-us-mem-whitehaven','Whitehaven','Geography / Countries / North America / United States / Tennessee / Memphis / Whitehaven'),
  ('geo-us-mem-frayser','Frayser','Geography / Countries / North America / United States / Tennessee / Memphis / Frayser'),
  ('geo-us-mem-raleigh','Raleigh','Geography / Countries / North America / United States / Tennessee / Memphis / Raleigh'),
  ('geo-us-mem-hickory-hill','Hickory Hill','Geography / Countries / North America / United States / Tennessee / Memphis / Hickory Hill'),
  ('geo-us-bal-inner-harbor','Inner Harbor','Geography / Countries / North America / United States / Maryland / Baltimore / Inner Harbor'),
  ('geo-us-bal-fells-point','Fells Point','Geography / Countries / North America / United States / Maryland / Baltimore / Fells Point'),
  ('geo-us-bal-canton','Canton','Geography / Countries / North America / United States / Maryland / Baltimore / Canton'),
  ('geo-us-bal-federal-hill','Federal Hill','Geography / Countries / North America / United States / Maryland / Baltimore / Federal Hill'),
  ('geo-us-bal-mount-vernon','Mount Vernon','Geography / Countries / North America / United States / Maryland / Baltimore / Mount Vernon'),
  ('geo-us-bal-hampden','Hampden','Geography / Countries / North America / United States / Maryland / Baltimore / Hampden'),
  ('geo-us-bal-charles-village','Charles Village','Geography / Countries / North America / United States / Maryland / Baltimore / Charles Village'),
  ('geo-us-bal-roland-park','Roland Park','Geography / Countries / North America / United States / Maryland / Baltimore / Roland Park'),
  ('geo-us-bal-bolton-hill','Bolton Hill','Geography / Countries / North America / United States / Maryland / Baltimore / Bolton Hill'),
  ('geo-us-bal-little-italy','Little Italy','Geography / Countries / North America / United States / Maryland / Baltimore / Little Italy'),
  ('geo-us-bal-highlandtown','Highlandtown','Geography / Countries / North America / United States / Maryland / Baltimore / Highlandtown'),
  ('geo-us-bal-patterson-park','Patterson Park','Geography / Countries / North America / United States / Maryland / Baltimore / Patterson Park'),
  ('geo-us-bal-locust-point','Locust Point','Geography / Countries / North America / United States / Maryland / Baltimore / Locust Point'),
  ('geo-us-bal-station-north','Station North','Geography / Countries / North America / United States / Maryland / Baltimore / Station North'),
  ('geo-us-bal-pigtown','Pigtown','Geography / Countries / North America / United States / Maryland / Baltimore / Pigtown'),
  ('geo-us-bal-remington','Remington','Geography / Countries / North America / United States / Maryland / Baltimore / Remington'),
  ('geo-us-bal-downtown','Downtown','Geography / Countries / North America / United States / Maryland / Baltimore / Downtown'),
  ('geo-us-bal-mount-washington','Mount Washington','Geography / Countries / North America / United States / Maryland / Baltimore / Mount Washington'),
  ('geo-us-mke-downtown','Downtown','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Downtown'),
  ('geo-us-mke-historic-third-ward','Historic Third Ward','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Historic Third Ward'),
  ('geo-us-mke-walkers-point','Walker''s Point','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Walker''s Point'),
  ('geo-us-mke-bay-view','Bay View','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Bay View'),
  ('geo-us-mke-east-side','East Side','Geography / Countries / North America / United States / Wisconsin / Milwaukee / East Side'),
  ('geo-us-mke-riverwest','Riverwest','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Riverwest'),
  ('geo-us-mke-brewers-hill','Brewers Hill','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Brewers Hill'),
  ('geo-us-mke-bronzeville','Bronzeville','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Bronzeville'),
  ('geo-us-mke-washington-heights','Washington Heights','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Washington Heights'),
  ('geo-us-mke-sherman-park','Sherman Park','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Sherman Park'),
  ('geo-us-mke-harambee','Harambee','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Harambee'),
  ('geo-us-mke-lindsay-heights','Lindsay Heights','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Lindsay Heights'),
  ('geo-us-mke-menomonee-valley','Menomonee Valley','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Menomonee Valley'),
  ('geo-us-mke-story-hill','Story Hill','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Story Hill'),
  ('geo-us-mke-jackson-park','Jackson Park','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Jackson Park'),
  ('geo-us-mke-silver-city','Silver City','Geography / Countries / North America / United States / Wisconsin / Milwaukee / Silver City'),
  ('geo-us-okc-downtown','Downtown','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Downtown'),
  ('geo-us-okc-bricktown','Bricktown','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Bricktown'),
  ('geo-us-okc-midtown','Midtown','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Midtown'),
  ('geo-us-okc-automobile-alley','Automobile Alley','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Automobile Alley'),
  ('geo-us-okc-deep-deuce','Deep Deuce','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Deep Deuce'),
  ('geo-us-okc-paseo-arts-district','Paseo Arts District','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Paseo Arts District'),
  ('geo-us-okc-plaza-district','Plaza District','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Plaza District'),
  ('geo-us-okc-uptown-23rd','Uptown 23rd','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Uptown 23rd'),
  ('geo-us-okc-film-row','Film Row','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Film Row'),
  ('geo-us-okc-capitol-hill','Capitol Hill','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Capitol Hill'),
  ('geo-us-okc-stockyards-city','Stockyards City','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Stockyards City'),
  ('geo-us-okc-classen-ten-penn','Classen Ten Penn','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Classen Ten Penn'),
  ('geo-us-okc-mesta-park','Mesta Park','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Mesta Park'),
  ('geo-us-okc-heritage-hills','Heritage Hills','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Heritage Hills'),
  ('geo-us-okc-crown-heights','Crown Heights','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Crown Heights'),
  ('geo-us-okc-windsor-hills','Windsor Hills','Geography / Countries / North America / United States / Oklahoma / Oklahoma City / Windsor Hills')
) AS v(id, name, path);

UPDATE public.atoms SET is_leaf = false
WHERE id IN ('geo-us-city-memphis-tn','geo-us-city-baltimore-md','geo-us-city-milwaukee-wi','geo-us-city-oklahoma-city-ok');
